// English — written by hand, app-store quality. Same keys as pt.js: the
// Spanish phrase is the key; anything missing shows up in window.__faltantes.
export const DICCIONARIO_EN = {
  "Acceso privado": "Private access",
  "Tus finanzas, en un solo lugar.": "Your finances, all in one place.",
  "Email": "Email",
  "Contraseña": "Password",
  "Entrar": "Sign in",
  "tu@email.com": "you@email.com",
  "tu@correo.com": "you@email.com",
  "Cerrar sesión": "Sign out",
  "Cargando tus datos…": "Loading your data…",

  "Tu día": "Your day",
  "Tu dinero": "Your money",
  "Hoy": "Today",
  "Calendario": "Calendar",
  "Entreno": "Training",
  "Menú": "Meal plan",
  "Compras": "Groceries",
  "Ciclo": "Cycle",
  "Oficina": "Office",
  "Progreso": "Progress",
  "Dashboard": "Dashboard",
  "Movimientos": "Transactions",
  "Cuentas": "Accounts",
  "Gastos fijos": "Fixed expenses",
  "Préstamos": "Loans",
  "Metas": "Goals",
  "Gráficos": "Charts",
  "Categorías": "Categories",
  "Cartera": "Portfolio",
  // ---------- Préstamos · avisos de cobro ----------
  "💰 Cobros que te deben":
    "💰 Payments owed to you",
  "± Apuntar el pago":
    "± Log the payment",
  "Pasar a la siguiente fecha":
    "Skip to the next date",
  "Quitar el aviso":
    "Remove the reminder",
  "márcalo en su plan de abajo":
    "mark it in its plan below",
  "¿Qué día te tiene que pagar? (opcional)":
    "What day are they due to pay you? (optional)",
  "¿Ese cobro se repite?":
    "Does that payment repeat?",
  "No, es un cobro único":
    "No, it's a one-off",
  "Cada semana":
    "Every week",
  "Cada mes":
    "Every month",
  "El día del cobro te sale un aviso en Préstamos y en el Dashboard. Al apuntar el pago, la fecha salta sola a la siguiente.":
    "On the due day a reminder shows up in Loans and on the Dashboard. When you log the payment, the date jumps to the next one by itself.",
  "Toca para apuntarlo en Préstamos":
    "Tap to log it in Loans",
  // ---------- Cartera · glosario y avisos ----------
  "Posición": "Position",
  "Último precio": "Last price",
  "Variación": "Change",
  "Cuántas participaciones tienes de esa cosa. Puede ser un número con decimales: 0,5 participaciones de un ETF es la mitad de una, y es completamente normal — se compra por euros, no por unidades enteras.":
    "How many shares of that thing you own. It can have decimals: 0.5 shares of an ETF is half of one, and that's completely normal — you buy by euros, not whole units.",
  "Lo que cuesta UNA participación ahora mismo. Tu dinero es este precio multiplicado por tu posición. Sube y baja constantemente; no hace falta mirarlo cada día.":
    "What ONE share costs right now. Your money is this price times your position. It moves constantly; no need to check it every day.",
  "Cuánto ha cambiado el precio. 'Hoy' compara con ayer: es ruido, sube y baja sin razón que te importe. 'Desde la compra' compara con lo que pagaste: esa es la única que dice si vas ganando o perdiendo de verdad.":
    "How much the price has changed. 'Today' compares with yesterday: it's noise, up and down for no reason that matters to you. 'Since purchase' compares with what you paid: that's the only one that says whether you're truly up or down.",
  "¿Qué es un ETF?":
    "What is an ETF?",
  "Una cesta con cientos o miles de empresas dentro. Comprar un ETF 'mundial' es comprar un trocito de las mayores empresas del planeta de golpe. Si una quiebra, ni lo notas. Por eso es la forma más tranquila de empezar: no hay que acertar cuál ganará.":
    "A basket with hundreds or thousands of companies inside. Buying a 'world' ETF is buying a little piece of the planet's biggest companies at once. If one goes bankrupt, you barely notice. That's why it's the calmest way to start: you don't have to guess the winner.",
  "(Acc) y (Dist)":
    "(Acc) and (Dist)",
  "Acc = acumulación: los dividendos que pagan las empresas se reinvierten solos dentro del fondo, y crece más rápido. Dist = distribución: te los pagan en efectivo. Para acumular a largo plazo, Acc suele convenir más en España (no pagas impuestos por dividendos que no cobras).":
    "Acc = accumulating: the dividends companies pay are reinvested automatically inside the fund, and it grows faster. Dist = distributing: they're paid out to you in cash. For long-term saving, Acc usually works out better in Spain (you don't pay tax on dividends you never receive).",
  "Lo más volátil de esta pantalla: puede caer un 50 % en meses y también subirlo. Regla simple: que sea solo una parte pequeña de la cartera y nunca dinero que puedas necesitar.":
    "The most volatile thing on this screen: it can drop 50 % in months and rise as much. Simple rule: keep it a small part of the portfolio and never money you might need.",
  "¿Qué es esta estimación?":
    "What is this estimate?",
  "Parte de lo que tienes invertido AHORA MISMO y calcula qué haría el mercado con ello si diera de media ese % al año (interés compuesto). La aportación mensual es opcional: a 0 ves solo crecer lo tuyo; ponle algo para jugar con '¿y si además aporto?'. La bolsa mundial ha dado ~7 % anual de media histórica, con años de −20 % y de +25 % por el camino. Es para hacerse una idea, no una promesa.":
    "It takes what you have invested RIGHT NOW and works out what the market would do with it at that average % per year (compound interest). The monthly amount is optional: at 0 you watch only yours grow; add something to play with 'what if I also contribute?'. The world market has averaged ~7 % a year historically, with −20 % and +25 % years along the way. It's to get an idea, not a promise.",
  "Las señales":
    "The signals",
  "Reglas fijas sobre TUS números: concentración, caídas grandes, precios sin actualizar. No predicen nada — nadie puede — pero avisan de lo que a cualquiera se le pasaría por alto.":
    "Fixed rules about YOUR numbers: concentration, big drops, stale prices. They predict nothing — nobody can — but they flag what anyone would overlook.",
  "El símbolo":
    "The symbol",
  "El código con el que la app busca el precio automáticamente. Acciones de EE. UU.: su ticker (AAPL, AMZN…) con la clave de Finnhub. Cripto: su id de CoinGecko en minúsculas (bitcoin, ethereum). Los ETF europeos no están en el plan gratuito: su precio se copia de Trade Republic con el lápiz, y todo lo demás se calcula igual.":
    "The code the app uses to look up the price automatically. US stocks: their ticker (AAPL, AMZN…) with the Finnhub key. Crypto: their CoinGecko id in lowercase (bitcoin, ethereum). European ETFs aren't in the free plan: their price is copied from Trade Republic with the pencil, and everything else is calculated the same.",
  "Sin criptomonedas apuntadas. Si compras bitcoin en Trade Republic, apúntalo aquí y su precio se refresca solo.":
    "No crypto logged. If you buy bitcoin on Trade Republic, log it here and its price refreshes on its own.",
  "Todavía nada. Cuando compres tu primer ETF o acción en Trade Republic, apúntalo con + Añadir: qué es, cuántas participaciones y a qué precio.":
    "Nothing yet. When you buy your first ETF or stock on Trade Republic, log it with + Add: what it is, how many shares and at what price.",
  "Todavía no hay nada invertido, así que de momento no hay nada que proyectar. En cuanto apuntes tu primera compra, aquí verás lo que podría llegar a ser con los años. Si quieres jugar mientras tanto, pon una aportación al mes.":
    "Nothing invested yet, so there's nothing to project for now. As soon as you log your first buy, here you'll see what it could become over the years. If you want to play meanwhile, set a monthly amount.",
  "Pocas posiciones y ningún fondo indexado. Un ETF mundial (tipo MSCI World) es la forma más simple de diversificar sin pensar.":
    "Few positions and no index fund. A world ETF (like MSCI World) is the simplest way to diversify without thinking.",
  "Hay precios sin actualizar desde hace más de una semana: la ganancia que ves puede no ser la real.":
    "Some prices haven't been refreshed in over a week: the gain you see may not be the real one.",
  "No se pudo guardar. ¿Están publicadas las reglas nuevas de Firebase?":
    "Couldn't save. Are the new Firebase rules published?",
  "Clave de Finnhub (gratis en finnhub.io → Get free API key). Se guarda una vez y sirve para refrescar acciones de EE. UU.:":
    "Finnhub key (free at finnhub.io → Get free API key). Saved once, used to refresh US stocks:",
  // ---------- Cartera · vista ----------
  "Editar posición": "Edit position",
  "Nueva posición": "New position",
  "Elegir de la lista (opcional)": "Pick from the list (optional)",
  "— Escribir a mano —": "— Type it in —",
  "ETF / fondo": "ETF / fund",
  "Acción": "Stock",
  "Cripto": "Crypto",
  "Símbolo (opcional)": "Symbol (optional)",
  "Participaciones": "Shares",
  "Precio de compra (€/ud)": "Purchase price (€/share)",
  "Precio actual (€/ud)": "Current price (€/share)",
  "Vacío = el de compra": "Empty = purchase price",
  "El símbolo cotiza en…": "The symbol trades in…",
  "Dólares (EE. UU.)": "US dollars",
  "Euros": "Euros",
  "Cuenta de valores": "Securities account",
  "Criptomonedas": "Crypto",
  "Instrumento": "Instrument",
  "Desde la compra": "Since purchase",
  "Variación hoy": "Change today",
  "↻ Actualizar": "↻ Refresh",
  "+ Añadir": "+ Add",
  "Señales": "Signals",
  "— hoy sin dato": "— no data today",
  "Toca una fila para editarla. Último precio": "Tap a row to edit it. Last price",
  "· ETF": "· ETF",
  "· (Acc)/(Dist)": "· (Acc)/(Dist)",
  "· Cripto": "· Crypto",
  "poner clave de Finnhub": "set Finnhub key",
  "¿Cuánto podría llegar a ser?": "How much could it become?",
  "Parte de lo que tienes invertido ahora mismo:": "It starts from what you have invested right now:",
  ". La aportación al mes es opcional — a 0, ves solo lo que haría el mercado con lo tuyo.": ". The monthly amount is optional — at 0 you see only what the market would do with what's yours.",
  "Aportación al mes (€, opcional)": "Monthly amount (€, optional)",
  "Rentabilidad anual estimada": "Estimated annual return",
  "Con el mercado": "With the market",
  "Solo aportado": "Just what you put in",
  "¿Eliminar esta posición de la cartera?": "Remove this position from the portfolio?",
  "Actualizando…": "Refreshing…",
  "y tendrías": "and you'd have",
  "¿Qué es esto?": "What is this?",
  "Entendido": "Got it",
  // ---------- Cartera · aportaciones ----------
  "Aportación":
    "Contribution",
  "Dinero nuevo que metes en algo que ya tienes — la compra de cada mes. Apuntas cuánto metes y a qué precio estaba ese día: la app calcula las participaciones (dinero ÷ precio), las suma a tu posición y te lleva la cuenta EXACTA de lo que has puesto en cada sitio. Lo ganado o perdido siempre se compara contra ese total real.":
    "New money you put into something you already own — the monthly buy. You log how much you put in and that day's price: the app works out the shares (money ÷ price), adds them to your position and keeps an EXACT count of what you've put in each place. Gains or losses are always measured against that real total.",
  "Aportaciones":
    "Contributions",
  "+ Apuntar aportación":
    "+ Log a contribution",
  "Posición inicial":
    "Starting position",
  "Sin aportaciones apuntadas todavía. Cada vez que metas dinero, apúntalo aquí y el total invertido será exacto.":
    "No contributions logged yet. Every time you put money in, log it here and the invested total will be exact.",
  "Cuánto metes (€)":
    "How much you're putting in (€)",
  "Precio por unidad ese día (€)":
    "Price per share that day (€)",
  "Apuntar":
    "Log it",
  "¿Quitar esta aportación? Se restan sus participaciones y su dinero de la posición.":
    "Remove this contribution? Its shares and its money will be subtracted from the position.",
  "Quitar":
    "Remove",
  "Abrir menú": "Open menu",
  "Mi cuenta": "My account",

  "Añadir": "Add",
  "+ Añadir": "+ Add",
  "Guardar": "Save",
  "Cancelar": "Cancel",
  "Cerrar": "Close",
  "Editar": "Edit",
  "Eliminar": "Delete",
  "Nombre": "Name",
  "Fecha": "Date",
  "Importe": "Amount",
  "Importe total": "Total amount",
  "Tipo": "Type",
  "Estado": "Status",
  "Cuenta": "Account",
  "Categoría": "Category",
  "Frecuencia": "Frequency",
  "Nota (opcional)": "Note (optional)",
  "Icono (opcional)": "Icon (optional)",
  "Subcategoría (opcional)": "Subcategory (optional)",
  "Total": "Total",
  "Todo": "All",
  "Mes": "Month",
  "Año": "Year",
  "Mes anterior": "Previous month",
  "Mes siguiente": "Next month",
  "Ver todas": "View all",
  "Ver todos": "View all",
  "Historial": "History",
  "Activo": "Active",
  "Pagado": "Paid",
  "pendiente": "outstanding",
  "Debe": "Owes",
  "Importando…": "Importing…",

  "Lun": "Mon",
  "Mar": "Tue",
  "Mié": "Wed",
  "Jue": "Thu",
  "Vie": "Fri",
  "Sáb": "Sat",
  "Dom": "Sun",

  "Saldo total": "Total balance",
  "Gastos por categoría · este mes": "Spending by category · this month",
  "Toca una porción para ver de qué gastos sale.": "Tap a slice to see which expenses it comes from.",
  "Total del mes": "Month total",
  "Si alguno no cuadra (repetido o con la fecha de otro mes), corrígelo tocando su día en Movimientos.":
    "If one looks wrong (duplicated or dated in another month), fix it by tapping its day in Transactions.",
  "Límites del mes": "Monthly limits",
  "Movimientos recientes": "Recent transactions",
  "Préstamos activos": "Active loans",
  "Suscripciones activas": "Active subscriptions",
  "Top gastos por lugar · este mes": "Top spending by place · this month",
  "Es tu primera vez aquí": "It's your first time here",
  "Puedo rellenar tus cuentas, categorías, suscripciones fijas y préstamos con los datos que ya me pasaste, para que no tengas que escribirlo todo a mano.":
    "I can fill in your accounts, categories, fixed subscriptions and loans with the data you already gave me, so you don't have to type it all by hand.",
  "Importar mis datos iniciales": "Import my starting data",
  "Este mes": "This month",
  "Ingresos": "Income",
  "Gastos": "Expenses",
  "Ingreso": "Income",
  "Gasto": "Expense",
  "Estimado": "Estimated",

  "Añadir movimiento": "Add transaction",
  "+ Añadir movimiento": "+ Add transaction",
  "Ingresos del mes": "Income this month",
  "Gastos del mes": "Expenses this month",
  "Diferencia": "Difference",
  "Ingresos vs. Gastos este mes": "Income vs. expenses this month",
  "Balance del día": "Day balance",
  "Transferencia entre cuentas": "Transfer between accounts",
  "Transferencia": "Transfer",
  "Cuenta destino": "Destination account",
  "Mercadona, Glovo, nómina…": "Groceries, delivery, payday…",
  "Five Guys, Zara…": "Five Guys, Zara…",
  "Editar movimiento": "Edit transaction",
  "Nuevo movimiento": "New transaction",
  "¿Eliminar este movimiento? El saldo de su cuenta se ajustará al quitarlo.":
    "Delete this transaction? The account balance will adjust once it's removed.",

  "+ Añadir cuenta": "+ Add account",
  "Nueva cuenta": "New account",
  "Editar cuenta": "Edit account",
  "Saldo inicial": "Starting balance",
  "Fecha de ese saldo": "Date of that balance",
  "Cuenta activa": "Active account",
  "Corriente": "Checking",
  "Ahorro": "Savings",
  "Efectivo": "Cash",
  "Otra": "Other",
  "Sin límite mensual": "No monthly limit",
  "Cuadrar": "Reconcile",
  "Cuadrar la cuenta": "Reconcile account",
  "¿Cuánto tienes de verdad?": "How much do you really have?",
  "Según la app tienes": "According to the app you have",
  ". Escribe lo que tienes DE VERDAD (lo que dice el banco o el efectivo contado) y el saldo se ajusta solo. Los movimientos no se tocan.":
    ". Type what you REALLY have (what the bank says, or the cash you counted) and the balance adjusts itself. Your transactions are left untouched.",
  "Ya cuadra: no hay nada que ajustar.": "It already matches: nothing to adjust.",
  "Copiar ID de Firestore": "Copy Firestore ID",
  "¿Eliminar esta cuenta? No se borrarán sus movimientos.":
    "Delete this account? Its transactions will not be erased.",

  "+ Añadir gasto fijo": "+ Add fixed expense",
  "Nuevo gasto fijo": "New fixed expense",
  "Editar gasto fijo": "Edit fixed expense",
  "Gasto fijo activo": "Active fixed expense",
  "Mensual": "Monthly",
  "Anual": "Yearly",
  "Bimensual": "Every two months",
  "Trimestral": "Quarterly",
  "Semestral": "Twice a year",
  "Precio habitual": "Usual price",
  "Gastos fijos por cuenta": "Fixed expenses by account",
  "Glovo Prime, Préstamo Bankinter, Luz…": "Streaming, car loan, electricity…",
  "¿Eliminar este gasto fijo? No se borrarán los gastos ya registrados.":
    "Delete this fixed expense? Expenses already recorded will not be erased.",

  "+ Nuevo préstamo": "+ New loan",
  "Nuevo préstamo": "New loan",
  "Editar préstamo": "Edit loan",
  "Pendiente de cobrar": "Outstanding to collect",
  "Intereses a tu favor": "Interest in your favor",
  "Persona": "Person",
  "Nombre de la persona": "Person's name",
  "Capital prestado": "Amount lent",
  "Interés (%)": "Interest (%)",
  "Interés fijo (€, opcional)": "Fixed interest (€, optional)",
  "Vacío = se calcula con el %": "Empty = calculated from the %",
  "Ya pagado hasta ahora (€)": "Paid so far (€)",
  "¿Para cuándo debería pagarlo? (opcional)": "When should it be paid by? (optional)",
  "Notas del préstamo (opcional)": "Loan notes (optional)",
  "Los detalles para tenerlo controlado: qué acordasteis, cuándo prometió pagar, si dejó algo a cuenta…":
    "The details to stay on top of it: what you agreed, when they promised to pay, whether they left a deposit…",
  "¿De qué cuenta sale el dinero?": "Which account does the money come from?",
  "No descontarlo de ninguna cuenta": "Don't deduct it from any account",
  "¿Qué día se lo diste?": "What day did you lend it?",
  "El capital sale de esa cuenta y cuenta como gasto del día: ese dinero ya no lo tienes. Cuando te lo devuelvan, entrará como ingreso.":
    "The amount leaves that account and counts as an expense for the day: that money is no longer yours to spend. When it's paid back, it comes in as income.",
  "± Ha pagado una parte": "± They paid a part",
  "💰 Ha pagado todo lo pendiente (liquidar)": "💰 They paid everything outstanding (settle)",
  "¿Cuánto ha pagado?": "How much did they pay?",
  "¿A qué cuenta entra?": "Which account does it go into?",
  "Registrar el abono": "Record the payment",
  ". Escribe cuánto ha pagado.": ". Type how much they paid.",
  "Liquidar y cerrar préstamo": "Settle and close loan",
  "Le quedan por pagar": "They still owe",
  "(capital + interés). Esto registra un ingreso por el total y cierra el préstamo como Pagado.":
    "(principal + interest). This records income for the total and closes the loan as Paid.",
  "Esto registra un ingreso por el total y cierra el préstamo como Pagado.":
    "This records income for the total and closes the loan as Paid.",
  "Préstamo cerrado.": "Loan closed.",
  "— saldado": "— settled",
  "¿Eliminar este préstamo? Los pagos ya registrados se quedan en Movimientos (ese dinero entró de verdad). Solo si nunca cobró nada, se borra también el gasto de cuando salió el dinero.":
    "Delete this loan? Recorded payments stay in Transactions (that money really came in). Only if nothing was ever collected, the expense from when the money went out is deleted too.",
  "Abono": "Payment",
  "Cuota del plan": "Plan installment",
  "Liquidación": "Settlement",
  "Interés": "Interest",
  "Pago": "Payment",
  "Cobrado este mes ▾": "Collected this month ▾",
  "Intereses este mes ▾": "Interest this month ▾",
  "Toca para ver el desglose por persona": "Tap to see the breakdown by person",
  "Este mes todavía no has cobrado ningún pago.": "You haven't collected any payments this month yet.",
  "Listo": "Done",
  "(tu ganancia). Cada cobro se reparte según su préstamo: en uno de 100 € al 20 %, de cada 30 € cobrados, 5 € son interés.":
    "(your earnings). Each payment is split according to its loan: on €100 at 20%, of every €30 collected, €5 is interest.",

  "+ Nueva meta": "+ New goal",
  "Nueva meta": "New goal",
  "Editar meta": "Edit goal",
  "Crear la meta": "Create goal",
  "¿Para qué ahorras?": "What are you saving for?",
  "¿Cuánto necesitas?": "How much do you need?",
  "¿Para cuándo? (opcional)": "By when? (optional)",
  "Viaje a Bolivia, arreglar el baño…": "A trip, fixing the bathroom…",
  "Huchas para lo que quieres conseguir: un viaje, una reparación, un capricho. El dinero sigue en tus cuentas — aquí solo lo apartas.":
    "Money jars for what you want: a trip, a repair, a treat. The money stays in your accounts — here you just set it aside.",
  "Todavía no tienes ninguna meta. Un viaje, una reparación de casa, un capricho grande… ponle nombre y una cantidad, y ve apartando.":
    "You don't have any goals yet. A trip, a home repair, a big treat… give it a name and an amount, and start setting money aside.",
  "¿Eliminar esta meta? El dinero sigue en tus cuentas — solo se borra la hucha.":
    "Delete this goal? The money stays in your accounts — only the jar is removed.",
  "¿Borrar esta aportación?": "Delete this contribution?",

  "Total de gastos": "Total expenses",
  "Total de ingresos": "Total income",
  "Gastos por categoría": "Expenses by category",
  "Ingresos por categoría": "Income by category",
  "Gastos por lugar": "Spending by place",
  "Buscar: Five Guys, KFC, Taco Bell…": "Search: Five Guys, KFC, Taco Bell…",

  "+ Añadir categoría": "+ Add category",
  "Nueva categoría": "New category",
  "Editar categoría": "Edit category",
  "Límite mensual (opcional)": "Monthly limit (optional)",
  "Fijo": "Fixed",
  "Variable": "Variable",
  "Ocio": "Leisure",
  "PrestamoDado": "Loan given",
  "Comida a domicilio": "Food delivery",
  "¿Eliminar esta categoría? Sus movimientos no se borran: quedarán como 'sin categoría'.":
    "Delete this category? Its transactions are not erased: they'll show as 'uncategorized'.",

  "Sesión iniciada con Firebase Auth": "Signed in with Firebase Auth",
  "Cambiar contraseña": "Change password",
  "Idioma": "Language",
  "El idioma de toda la app en este dispositivo.": "The language of the whole app on this device.",
  "Temas": "Themes",
  "Cambia el aspecto de toda la app. «Original» la deja como estaba.":
    "Change the look of the whole app. “Dark (original)” puts it back the way it was.",
  "Configuración": "Settings",
  "Ver la guía de la app otra vez": "See the app guide again",
  "Exportar mis datos": "Export my data",
  "Importar desde una copia": "Import from a backup",
  "Datos importados correctamente.": "Data imported successfully.",
  "No se pudo importar el archivo. ¿Es una copia válida exportada desde aquí?":
    "The file couldn't be imported. Is it a valid backup exported from here?",
  "Esto añadirá todo lo que haya en el archivo a tus datos actuales (no borra nada existente). ¿Continuar?":
    "This will add everything in the file to your current data (nothing existing is deleted). Continue?",
  "No se pudo enviar el email. Inténtalo de nuevo.": "The email couldn't be sent. Try again.",
  "No se pudo guardar. Inténtalo de nuevo.": "Couldn't save. Try again.",

  "Oscuro (original)": "Dark (original)",
  "Claro": "Light",
  "Por defecto": "Default",
  "Países": "Countries",
  "España": "Spain",
  "Bolivia": "Bolivia",
  "Brasil": "Brazil",
  "Italia": "Italy",
  "Francia": "France",
  "Rosa pastel": "Pastel pink",
  "Español": "Español",
  "Português (Brasil)": "Português (Brasil)",

  "¡Bienvenido! 👋": "Welcome! 👋",
  "Esta es tu app: tu día a día y tu dinero, en un solo sitio y a tu manera. Te enseño lo básico en cuatro pasos — medio minuto.":
    "This is your app: your daily life and your money, in one place and your way. Let me show you the basics in four steps — half a minute.",
  "El menú": "The menu",
  "Aquí está TODO, en dos bloques: «Tu día» (rutina, calendario, comidas…) y «Tu dinero» (cuentas, movimientos, préstamos…). Ninguna pantalla escondida.":
    "EVERYTHING is here, in two blocks: “Your day” (routine, calendar, meals…) and “Your money” (accounts, transactions, loans…). No hidden screens.",
  "Tu cuenta y tus colores": "Your account and your colors",
  "Desde aquí eliges el tema de la app — claro u oscuro, o uno con carácter (países y más) — y gestionas tu perfil.":
    "From here you pick the app's theme — light or dark, or one with character (countries and more) — and manage your profile.",
  "Tuya de verdad": "Truly yours",
  "Toca todo sin miedo: cualquier cosa que borre algo te pregunta antes y te dice qué va a pasar. Y si algo no encaja con tu vida, se cambia — para eso es tuya. ¡A por ello!":
    "Tap everything without fear: anything that deletes something asks you first and tells you what will happen. And if something doesn't fit your life, it gets changed — that's why it's yours. Go for it!",
  "Saltar": "Skip",
  "Siguiente →": "Next →",
  "¡Listo!": "Done!",

  "Balance": "Balance",
  "sin fecha": "no date",
  "Sin categoría": "Uncategorized",
  "sin categoría": "uncategorized",

  "Ayer quedó sin cerrar.": "Yesterday was left open.",
  "Cerrar ayer": "Close yesterday",
  "Los 4 innegociables": "The 4 non-negotiables",
  "Los cuatro = día cumplido. No hay medias tintas.": "All four = day complete. No half measures.",
  "Sin comida fuera sin planificar": "No unplanned eating out",
  "El entreno que toque": "The day's workout",
  "En la cama antes de las 23:15": "In bed before 11:15 pm",
  "4 piezas de fruta": "4 pieces of fruit",
  "Dientes 3 veces": "Teeth 3 times",
  "Cena dejada preparada": "Dinner left ready",
  "Algo de verdura": "Some vegetables",
  "Bonus": "Bonus",
  "Cerrar el día": "Close the day",
  "Guardar cambios": "Save changes",
  "Corregir": "Fix",
  "✎ Corregir otro día": "✎ Fix another day",
  "✎ Ajustar este horario": "✎ Adjust this schedule",
  "✎ Editar ejercicios": "✎ Edit exercises",
  "Apuntes del día (opcional)": "Day notes (optional)",
  "Peso (kg) — 1 vez por semana basta": "Weight (kg) — once a week is enough",
  "Racha:": "Streak:",
  "Racha": "Streak",
  "días · Día": "days · Day",
  "Día · hoy": "Day · today",
  "Día": "Day",
  "Semana": "Week",
  "Qué toca hoy": "What's on today",
  "Hoy toca:": "Today:",
  "Tocar para registrarlo": "Tap to log it",
  "El día, hora a hora": "The day, hour by hour",
  "Marcar como hecho": "Mark as done",
  "Desmarcar todo": "Unmark all",
  "☑ Para hacer hoy": "☑ To do today",
  "＋ Cita o imprevisto": "＋ Appointment or surprise",
  "⏳ Algo quedó a medias": "⏳ Something was left halfway",
  "🍎 Fruta 1": "🍎 Fruit 1",
  "🍊 Fruta 2": "🍊 Fruit 2",
  "🍌 Fruta 3": "🍌 Fruit 3",
  "🍇 Fruta 4": "🍇 Fruit 4",
  "🪒 Rasurarse": "🪒 Shave",
  "La del bonus: con esta van las 4 piezas": "The bonus one: with this you hit all 4 pieces",
  "Comida:": "Lunch:",
  "Cena:": "Dinner:",
  "Comer": "Lunch",
  "Dormir": "Sleep",
  "Levantarte con calma": "Get up unhurried",
  "Descanso de verdad": "Real rest",
  "Es el día que sostiene la semana": "It's the day that holds up the week",
  "Preparar la semana": "Set up the week",
  "Batch cooking (hasta las 13:00)": "Batch cooking (until 1 pm)",
  "Las comidas de la semana, del menú": "The week's meals, from the plan",
  "Platos y cocina recogida": "Dishes done, kitchen tidy",
  "Mochila del gimnasio hecha · menú a la vista": "Gym bag packed · meal plan in sight",
  "Todo listo. Falta que tú digas YA.": "All set. It just needs your GO.",
  "START · empezar hoy 💪": "START · begin today 💪",
  "La racha y los puntos del día": "The streak and daily points",
  "El bote de recompensas": "The rewards jar",
  "La fase de estudio (30 → 60 min)": "The study phase (30 → 60 min)",
  "Las semanas 6/7 y los logros": "The 6/7 weeks and achievements",
  "Día 1": "Day 1",
  "Un momento, están llegando de Firebase. Tu racha y tus días están guardados. Si esto no avanza, revisa la conexión.":
    "One moment, it's arriving from Firebase. Your streak and your days are saved. If this doesn't move, check your connection.",
  "Estudio": "Study",
  "· 30 min (fase 1)": "· 30 min (phase 1)",
  "Estudio: fase 1 · 30 min/día. Sube sola con 2 semanas seguidas a 6 de 7.":
    "Study: phase 1 · 30 min/day. It levels up on its own after 2 straight weeks at 6 of 7.",

  "Guardar el entreno": "Save workout",
  "¿De qué día es?": "Which day is it from?",
  "Si lo apuntas tarde (o pasada la medianoche), pon el día en que entrenaste":
    "If you log it late (or past midnight), set the day you actually trained",
  "Duración (min)": "Duration (min)",
  "reps": "reps",
  "Peso": "Weight",
  "Los kg de la serie 1": "Kg for set 1",
  "Los kg de la serie 2": "Kg for set 2",
  "Los kg de la serie 3": "Kg for set 3",
  "Últimos entrenos": "Recent workouts",
  "Pierna": "Legs",
  "Tirón": "Pull",
  "Empuje": "Push",
  "Core + caminata": "Core + walk",
  "Piscina": "Swimming",
  "Caminata": "Walk",
  "En casa": "At home",
  "Cómo se hace": "How it's done",
  "Plan de serie ·": "Standard plan ·",
  "Press banca": "Bench press",
  "Press de hombro": "Shoulder press",
  "Press de hombro (máquina o mancuernas)": "Shoulder press (machine or dumbbells)",
  "Jalón al pecho": "Lat pulldown",
  "Jalón agarre cerrado (puños mirándose)": "Close-grip pulldown (palms facing)",
  "Remo en máquina": "Machine row",
  "Remo en máquina (la barra hacia ti)": "Machine row (bar toward you)",
  "Remo a una mano con el chaleco": "One-arm row with the vest",
  "Curl en máquina": "Machine curl",
  "Curl martillo con mancuernas": "Hammer curl with dumbbells",
  "Curl femoral (tumbado o sentado)": "Leg curl (lying or seated)",
  "Extensiones de cuádriceps": "Leg extensions",
  "Hacka (o prensa)": "Hack squat (or leg press)",
  "Hacka / prensa": "Hack squat / leg press",
  "Peso muerto rumano con mancuernas": "Romanian deadlift with dumbbells",
  "Gemelos de pie": "Standing calf raises",
  "Abductor o aductor (alterna semanas)": "Abductor or adductor (alternate weeks)",
  "Lumbar (espalda baja)": "Lower back",
  "Elevaciones laterales (máquina o mancuernas)": "Lateral raises (machine or dumbbells)",
  "Cruces en polea (alta o baja, alterna)": "Cable crossover (high or low, alternate)",
  "Posterior en polea cruzada": "Rear delt cross cable",
  "Tríceps en polea (cuerda o barra, alterna)": "Cable triceps (rope or bar, alternate)",
  "Crunch en máquina": "Machine crunch",
  "Elevaciones de piernas (tumbado o colgado)": "Leg raises (lying or hanging)",
  "Plancha": "Plank",
  "Flexiones": "Push-ups",
  "Flexiones diamante": "Diamond push-ups",
  "Flexiones seguidas": "Push-ups in a row",
  "Sentadillas con el chaleco": "Squats with the vest",
  "Zancadas alternas": "Alternating lunges",
  "Caminata en cuesta (cinta 10–12 % · 5 km/h)": "Incline walk (treadmill 10–12% · 5 km/h)",
  "La primera vez apunta tu peso; desde entonces la app te lo trae puesto y avisa cuando toque subir":
    "The first time, enter your weight; from then on the app pre-fills it and tells you when it's time to go up",
  "Si está imposible: ejercicios 1 y 2 se esperan, del 3 en adelante cualquier máquina del mismo grupo vale, y si no hay manera → piscina. Cuenta igual.":
    "If it's packed: wait for exercises 1 and 2; from 3 on, any machine for the same muscle group works, and if there's no way → swimming. It counts the same.",
  "El gimnasio estaba lleno": "The gym was packed",
  "¿Te ha molestado la ingle hoy? 0 = nada · 10 = mucho": "Did your groin bother you today? 0 = not at all · 10 = a lot",
  "El aductor con suavidad mientras la ingle esté delicada; si molesta, fuera y punto":
    "Adductor gently while the groin is tender; if it hurts, drop it, period",
  "Lo único nuevo: glúteo y femoral de verdad. Si la ingle avisa, menos peso y menos recorrido":
    "The only new thing: real glute and hamstring work. If the groin complains, less weight and less range",
  "Si vas justo de tiempo, este es el que se cae": "If you're short on time, this is the one to drop",
  "~10 min · vale mientras trabajas": "~10 min · fine while you work",
  "Crear una rutina propia": "Create your own routine",
  "＋ Rutina": "＋ Routine",
  "Cambiar": "Change",

  "El duelo de la semana": "This week's duel",
  "Puntos de esta semana, de lunes a hoy. Gana quien se cuida — no quien se machaca: los puntos salen de dormir, moverse, comer bien y cumplir lo tuyo. Un día redondo = los 4 innegociables cumplidos. Perder este duelo también es ganar.":
    "Points this week, Monday through today. Whoever takes care of themselves wins — not whoever grinds hardest: points come from sleeping, moving, eating well and keeping your own promises. A perfect day = all 4 non-negotiables done. Losing this duel is winning too.",
  "Empate": "Tie",
  "Puntos": "Points",
  "Días redondos": "Perfect days",
  "Entrenos": "Workouts",
  "Semanas 6/7": "6/7 weeks",
  "El bote": "The jar",
  "bote total": "jar total",
  "disponible para gastar": "available to spend",
  "· Cada día cumplido suma lo que NO te gastas en comida fuera.": "· Every completed day adds what you DIDN'T spend eating out.",
  "Nueva recompensa": "New reward",
  "Añade recompensas: pavos, piezas del PC, el voucher del AZ-900… Nunca comida.":
    "Add rewards: game credits, PC parts, the AZ-900 voucher… Never food.",
  "Cuesta (€)": "Costs (€)",
  "Retos de fuerza": "Strength challenges",
  "Apunta el peso una vez por semana en Hoy → Apuntes del día.": "Log your weight once a week in Today → Day notes.",
  "Apunta tu peso en Hoy y salen sus niveles (van en proporción a tu peso).":
    "Log your weight in Today and the levels appear (they scale with your body weight).",
  "Aún sin marca: registra un entreno con este ejercicio. Primer reto:": "No record yet: log a workout with this exercise. First challenge:",
  "Valoraciones estimadas con estándares de fuerza internacionales, entre gente que entrena — comparado con la población general estás bastante más arriba. Los retos con kilos van en proporción a tu peso corporal: si tú bajas, ellos bajan contigo.":
    "Ratings estimated with international strength standards, among people who train — compared with the general population you're well above. Weighted challenges scale with your body weight: if you go down, they go down with you.",
  "🏅 0 medallas": "🏅 0 medals",
  "Fuerza — mejor serie por sesión": "Strength — best set per session",
  "Peso — hacia 84 kg": "Weight — toward 84 kg",
  "objetivo 84": "target 84",
  "mejor: 0": "best: 0",
  "Logros · 0/18": "Achievements · 0/18",
  "Primer día cumplido": "First day complete",
  "Primera semana 6 de 7": "First 6-of-7 week",
  "Primer mes cumplido": "First month complete",
  "Racha de 7 días": "7-day streak",
  "Racha de 14 días": "14-day streak",
  "Racha de 30 días": "30-day streak",
  "10 entrenos": "10 workouts",
  "25 entrenos": "25 workouts",
  "50 entrenos": "50 workouts",
  "Primera piscina": "First swim",
  "Primera subida de peso": "First weight increase",
  "Subida en 5 ejercicios": "Increase on 5 exercises",
  "Primera recompensa canjeada": "First reward redeemed",
  "Fase 2 de estudio": "Study phase 2",
  "Fase 4: una hora al día": "Phase 4: an hour a day",
  "Teórico de moto aprobado": "Motorcycle theory passed",
  "AZ-900 aprobado": "AZ-900 passed",
  "Carnet A2": "A2 license",
  "Tasa DGT pagada": "DMV fee paid",
  "Psicotécnico": "Medical exam",
  "Práctico de circuito": "Track practical",
  "Práctico de circulación": "Road practical",
  "Consulta de fisio por la ingle": "Physio visit for the groin",
  "Todavía no hay ninguno. El primero es hoy.": "None yet. The first one is today.",
  "Ver mi progreso y el bote →": "See my progress and the jar →",

  "El menú de la semana": "This week's meal plan",
  "¿Qué coméis en casa esta semana?": "What are you eating at home this week?",
  "Hacer el menú de esta semana": "Build this week's meal plan",
  "El menú es": "The meal plan is",
  "de casa": "for the household",
  ": el mismo para los dos, se mire desde la app que se mire — nadie cocina dos veces. Marcad juntos lo que os apetezca: con lo marcado salen ahora":
    ": the same for both of you, whichever app you look from — nobody cooks twice. Tick together whatever you feel like: with what's ticked you now get",
  "8 desayunos, 14 comidas y 15 cenas": "8 breakfasts, 14 lunches and 15 dinners",
  "Todavía no hay menú para esta semana. Marcad los ingredientes y dadle al botón: saldrá priorizando lo rápido (AirFryer, horno o pocos pasos), y luego cada día se puede retocar con el lápiz.":
    "No plan for this week yet. Tick your ingredients and hit the button: it prioritizes quick dishes (air fryer, oven or few steps), and each day can then be tweaked with the pencil.",
  "Haz tu menú de la semana con TUS ingredientes →": "Build your weekly plan with YOUR ingredients →",
  "Platos vuestros": "Your own dishes",
  "＋ Plato vuestro": "＋ Your own dish",
  "Comida fuera esta semana:": "Eating out this week:",
  "Proteína": "Protein",
  "Hidratos": "Carbs",
  "Verdura": "Vegetables",
  "Legumbres": "Legumes",
  "Lácteos y básicos": "Dairy and basics",
  "De postre": "For dessert",
  "Pollo": "Chicken",
  "Ternera picada": "Ground beef",
  "Lomo de cerdo": "Pork loin",
  "Salchichas": "Sausages",
  "Bacon": "Bacon",
  "Chorizo": "Chorizo",
  "Jamón / fiambre de pavo": "Ham / turkey slices",
  "Atún en lata": "Canned tuna",
  "Merluza": "Hake",
  "Salmón": "Salmon",
  "Huevos": "Eggs",
  "Arroz": "Rice",
  "Pasta": "Pasta",
  "Patatas": "Potatoes",
  "Pan": "Bread",
  "Avena": "Oats",
  "Cuscús": "Couscous",
  "Harina (crepes y pancakes)": "Flour (crepes and pancakes)",
  "Base de pizza": "Pizza base",
  "Tortillas de trigo (wraps)": "Wheat tortillas (wraps)",
  "Tomate frito / triturado": "Tomato sauce / crushed",
  "Lechuga (ensalada)": "Lettuce (salad)",
  "Zanahoria (triturada)": "Carrot (grated)",
  "Cebolla (en la salsa)": "Onion (in the sauce)",
  "Brócoli (con queso)": "Broccoli (with cheese)",
  "Calabacín (en crema)": "Zucchini (as soup)",
  "Espinacas (trituradas)": "Spinach (blended)",
  "Lentejas": "Lentils",
  "Garbanzos": "Chickpeas",
  "Alubias": "Beans",
  "Leche": "Milk",
  "Queso": "Cheese",
  "Yogur griego": "Greek yogurt",
  "Mantequilla": "Butter",
  "ColaCao / Cacaolat": "Chocolate milk mix",
  "Caldo de pollo": "Chicken stock",
  "Fruta (todas)": "Fruit (all)",
  "Frutos secos": "Nuts",
  "Pasta boloñesa (verdura en la salsa)": "Pasta bolognese (veg in the sauce)",
  "Sándwich integral de pollo": "Whole-wheat chicken sandwich",
  "¿Qué falta en casa?": "What's missing at home?",
  "+ Añadir a la lista": "+ Add to the list",
  "Elige categoría, escribe y dale a intro · toca para marcar o reponer · mantén pulsado para borrar":
    "Pick a category, type and hit enter · tap to tick or restock · press and hold to delete",
  "No falta nada ✨": "Nothing's missing ✨",
  "Quitar de la lista": "Remove from list",
  "Crear una categoría": "Create a category",
  "Limpieza": "Cleaning",
  "Cosas para la casa": "Things for the house",
  "Muebles": "Furniture",
  "Electrodomésticos": "Appliances",

  "La mochila de la oficina": "The office bag",
  "Repásala la noche de antes (el lunes te lo recuerda el horario) y un vistazo por la mañana. Las marcas se borran solas al día siguiente, listas para la próxima.":
    "Check it the night before (Monday's schedule reminds you) and glance in the morning. Ticks clear themselves the next day, ready for next time.",
  "Portátil y cargador": "Laptop and charger",
  "Auriculares": "Headphones",
  "Botella de agua": "Water bottle",
  "Tupper o comida": "Lunchbox or food",
  "Tarjeta o llaves de la oficina": "Office card or keys",
  "Cartera y transporte": "Wallet and transit pass",
  "Ropa de mañana lista": "Tomorrow's clothes ready",
  "Para el camino": "For the way",
  "¿Algo más que llevar?": "Anything else to bring?",
  "+ Apuntar regla": "+ Log period",
  "Calendario personal": "Personal calendar",
  "＋ Añadir": "＋ Add",
};

export const PATRONES_EN = [
  [/^💰 A (.+) le toca pagarte hoy$/, "💰 $1 is due to pay you today"],
  [/^💰 (.+) tenía que pagarte el (.+)$/, "💰 $1 was due to pay you on $2"],
  [/^A (.+) le toca pagarte hoy$/, "$1 is due to pay you today"],
  [/^(.+) tenía que pagarte el (.+)$/, "$1 was due to pay you on $2"],
  [/^· quedan (.+)$/, "· $1 left"],
  [/^"(.+)" es el (\d+) % de tu cartera\. Mucho peso en una sola cosa: si cae, cae todo contigo\.$/, "\"$1\" is $2 % of your portfolio. A lot of weight in one thing: if it falls, everything falls with you."],
  [/^Más de la mitad de la cartera es cripto \((\d+) %\)\. Es lo más volátil que hay: que no sea dinero que puedas necesitar\.$/, "More than half the portfolio is crypto ($1 %). It's the most volatile thing there is: make sure it's not money you might need."],
  [/^"(.+)" cae un (\d+) %\. Antes de vender por miedo, recuerda por qué la compraste: vender abajo convierte una caída en una pérdida\.$/, "\"$1\" is down $2 %. Before selling out of fear, remember why you bought it: selling at the bottom turns a dip into a loss."],
  [/^(.+ %\)) desde la compra$/, "$1 since purchase"],
  [/^(.+) uds · (.+) \(precio de compra\)$/, "$1 shares · $2 (purchase price)"],
  [/^(.+) uds · (.+)$/, "$1 shares · $2"],
  [/^(.+) uds$/, "$1 shares"],
  [/^Años: (\d+)$/, "Years: $1"],
  [/^Partiendo de (.+) y aportando (.+) al mes: en (\d+) años habrías aportado$/, "Starting from $1 and adding $2 a month: in $3 years you'd have put in"],
  [/^si el mercado diera un (\d+) % anual de media\.$/, "if the market averaged $1 % a year."],
  [/^Tus (.+) de hoy, sin aportar nada más, serían$/, "Your $1 today, without adding anything more, would be"],
  [/^en (\d+) años si el mercado diera un (\d+) % anual de media\.$/, "in $1 years if the market averaged $2 % a year."],
  [/^✓ (\d+) precio actualizado\.$/, "✓ $1 price refreshed."],
  [/^✓ (\d+) precios actualizados\.$/, "✓ $1 prices refreshed."],
  [/^Invertido (.+)$/, "Invested $1"],
  [/^Has metido (.+) en total$/, "You've put in $1 in total"],
  [/^Aportación a (.+)$/, "Contribution to $1"],
  [/^Eso son (.+) participaciones\.$/, "That's $1 shares."],
  [/^Gastos de esta categoría · (.+)$/, "This category's expenses · $1"],
  [/^Hola, (.+)$/, "Hi, $1"],
  [/^Límite mensual (.+)$/, "Monthly limit $1"],
  [/^Saldo inicial (.+) · desde (.+)$/, "Starting balance $1 · since $2"],
  [/^Prestado (.+) · para el (.+)$/, "Lent $1 · due $2"],
  [/^Prestado (.+?) \+ interés (.+?) = debe (.+?) · ya ha pagado (.+)$/, "Lent $1 + interest $2 = owes $3 · already paid $4"],
  [/^Prestado (.+?) \+ interés (.+?) = debe (.+)$/, "Lent $1 + interest $2 = owes $3"],
  [/^Prestado (.+?) · ya ha pagado (.+)$/, "Lent $1 · already paid $2"],
  [/^Prestado (.+)$/, "Lent $1"],
  [/^pendiente de (.+)$/, "of $1 outstanding"],
  [/^Pagado este mes: (.+?) \((.+?)\) · Pendiente: (.+)$/, "Paid this month: $1 ($2) · Outstanding: $3"],
  [/^Historial: (\d+) pagos? · (.+) cobrados$/, "History: $1 payments · $2 collected"],
  [/^Historial · (.+)$/, "History · $1"],
  [/^Cobrado en (.+)$/, "Collected in $1"],
  [/^Total (.+?) — capital (.+?) \+ intereses$/, "Total $1 — principal $2 + interest"],
  [/^Capital (.+?) · interés (.+)$/, "Principal $1 · interest $2"],
  [/^Capital (.+)$/, "Principal $1"],
  [/^Cuadrar · (.+)$/, "Reconcile · $1"],
  [/^Abono · (.+)$/, "Payment · $1"],
  [/^Liquidar deuda · (.+)$/, "Settle debt · $1"],
  [/^Interés pagado · (.+)$/, "Interest paid · $1"],
  [/^Transferencia enviada a (.+)$/, "Transfer sent to $1"],
  [/^Transferencia recibida de (.+)$/, "Transfer received from $1"],
  [/^Transferencia · (.+)$/, "Transfer · $1"],
  [/^Con (.+?) queda$/, "With $1 it's"],
  [/^todo saldado$/, "fully settled"],
  [/^: el préstamo se cerrará como Pagado\.$/, ": the loan will be closed as Paid."],
  [/^Quedarán por pagar$/, "Still to pay:"],
  [/^Se ajustará$/, "It will adjust by"],
  [/^para que el saldo diga (.+)\.$/, "so the balance reads $1."],
  [/^\(de (.+) en total\)\. Escribe cuánto ha pagado\.$/, "(of $1 in total). Type how much they paid."],
  [/^\(de (.+?) en total, ya había pagado (.+?)\)\.$/, "(of $1 in total, $2 already paid)."],
  [/^Te hemos enviado un email a (.+) para cambiar la contraseña\.$/, "We've sent an email to $1 to change your password."],
  [/^(\d+) de (\d+) pantallas?$/, "$1 of $2 screens"],
  [/^(\d+) de (\d+)$/, "$1 of $2"],
  [/^Debe (.+)$/, "Owes $1"],
  [/^ya ha pagado (.+)$/, "already paid $1"],
  [/^· ya ha pagado (.+)$/, "· already paid $1"],
  [/^· para el (.+)$/, "· due $1"],
  [/^AHORA · (.+)$/, "NOW · $1"],
  [/^Ahora: (.+)$/, "Now: $1"],
  [/^Pierna — tus máquinas de siempre$/, "Legs — your usual machines"],
  [/^Tirón — espalda y bíceps$/, "Pull — back and biceps"],
  [/^Empuje — pecho, hombro y tríceps$/, "Push — chest, shoulders and triceps"],
  [/^Caminata \+ core — el día ligero$/, "Walk + core — the light day"],
  [/^Piscina con tu hermano$/, "Swimming with your brother"],
  [/^Libre o caminata suave$/, "Free or easy walk"],
  [/^Descanso · batch cooking$/, "Rest · batch cooking"],
  [/^· empezaste el (.+)$/, "· you started on $1"],
  [/^· media de las (\d+) anteriores: (.+)$/, "· average of the last $1: $2"],
  [/^Referencia: (.+)\/día$/, "Reference: $1/day"],
  [/^(\d+) días? · Día (\d+)$/, "$1 days · Day $2"],
  [/^Día (\d+)$/, "Day $1"],
  [/^mejor: (\d+)$/, "best: $1"],
  [/^objetivo (\d+)$/, "target $1"],
  [/^🏅 (\d+) medallas?$/, "🏅 $1 medals"],
  [/^Logros · (\d+)\/(\d+)$/, "Achievements · $1/$2"],
  [/^Racha de (\d+) días$/, "$1-day streak"],
  [/^(\d+) entrenos$/, "$1 workouts"],
  [/^Los kg de la serie (\d+)$/, "Kg for set $1"],
  [/^Faltó: (.+)$/, "Missing: $1"],
  [/^Día cerrado \(no cumplido\) · (\d+) puntos$/, "Day closed (not complete) · $1 points"],
  [/^✓ Día cumplido · (\d+) puntos$/, "✓ Day complete · $1 points"],
  [/^(\d+) puntos$/, "$1 points"],
  [/^Aún sin marcar: (.+)\. Un toque ahora y el día no se escapa\.$/, "Still unmarked: $1. One tap now and the day doesn't slip away."],
  [/^Cerrando AYER · (.+)$/, "Closing YESTERDAY · $1"],
  [/^Corrigiendo · (.+)$/, "Fixing · $1"],
];
