// Italiano — scritto a mano, qualità da app nativa. Stesse chiavi di pt.js.
export const DICCIONARIO_IT = {
  "Acceso privado": "Accesso privato",
  "Tus finanzas, en un solo lugar.": "Le tue finanze, in un unico posto.",
  "Email": "Email",
  "Contraseña": "Password",
  "Entrar": "Accedi",
  "tu@email.com": "tu@email.com",
  "tu@correo.com": "tu@email.com",
  "Cerrar sesión": "Esci",
  "Cargando tus datos…": "Caricamento dei tuoi dati…",

  "Tu día": "La tua giornata",
  "Tu dinero": "I tuoi soldi",
  "Hoy": "Oggi",
  "Calendario": "Calendario",
  "Entreno": "Allenamento",
  "Menú": "Menù",
  "Compras": "Spesa",
  "Ciclo": "Ciclo",
  "Oficina": "Ufficio",
  "Progreso": "Progressi",
  "Dashboard": "Dashboard",
  "Movimientos": "Movimenti",
  "Cuentas": "Conti",
  "Gastos fijos": "Spese fisse",
  "Préstamos": "Prestiti",
  "Metas": "Obiettivi",
  "Gráficos": "Grafici",
  "Categorías": "Categorie",
  "Cartera": "Portafoglio",
  "Abrir menú": "Apri il menù",
  "Mi cuenta": "Il mio account",

  "Añadir": "Aggiungi",
  "+ Añadir": "+ Aggiungi",
  "Guardar": "Salva",
  "Cancelar": "Annulla",
  "Cerrar": "Chiudi",
  "Editar": "Modifica",
  "Eliminar": "Elimina",
  "Nombre": "Nome",
  "Fecha": "Data",
  "Importe": "Importo",
  "Importe total": "Importo totale",
  "Tipo": "Tipo",
  "Estado": "Stato",
  "Cuenta": "Conto",
  "Categoría": "Categoria",
  "Frecuencia": "Frequenza",
  "Nota (opcional)": "Nota (facoltativa)",
  "Icono (opcional)": "Icona (facoltativa)",
  "Subcategoría (opcional)": "Sottocategoria (facoltativa)",
  "Total": "Totale",
  "Todo": "Tutto",
  "Mes": "Mese",
  "Año": "Anno",
  "Mes anterior": "Mese precedente",
  "Mes siguiente": "Mese successivo",
  "Ver todas": "Vedi tutte",
  "Ver todos": "Vedi tutti",
  "Historial": "Cronologia",
  "Activo": "Attivo",
  "Pagado": "Pagato",
  "pendiente": "da incassare",
  "Debe": "Deve",
  "Importando…": "Importazione…",

  "Lun": "Lun",
  "Mar": "Mar",
  "Mié": "Mer",
  "Jue": "Gio",
  "Vie": "Ven",
  "Sáb": "Sab",
  "Dom": "Dom",

  "Saldo total": "Saldo totale",
  "Gastos por categoría · este mes": "Spese per categoria · questo mese",
  "Límites del mes": "Limiti del mese",
  "Movimientos recientes": "Movimenti recenti",
  "Préstamos activos": "Prestiti attivi",
  "Suscripciones activas": "Abbonamenti attivi",
  "Top gastos por lugar · este mes": "Top spese per luogo · questo mese",
  "Es tu primera vez aquí": "È la tua prima volta qui",
  "Puedo rellenar tus cuentas, categorías, suscripciones fijas y préstamos con los datos que ya me pasaste, para que no tengas que escribirlo todo a mano.":
    "Posso riempire i tuoi conti, categorie, abbonamenti fissi e prestiti con i dati che mi hai già passato, così non devi scrivere tutto a mano.",
  "Importar mis datos iniciales": "Importa i miei dati iniziali",
  "Este mes": "Questo mese",
  "Ingresos": "Entrate",
  "Gastos": "Uscite",
  "Ingreso": "Entrata",
  "Gasto": "Uscita",
  "Estimado": "Stimato",

  "Añadir movimiento": "Aggiungi movimento",
  "+ Añadir movimiento": "+ Aggiungi movimento",
  "Ingresos del mes": "Entrate del mese",
  "Gastos del mes": "Uscite del mese",
  "Diferencia": "Differenza",
  "Ingresos vs. Gastos este mes": "Entrate vs uscite questo mese",
  "Balance del día": "Bilancio del giorno",
  "Transferencia entre cuentas": "Trasferimento tra conti",
  "Transferencia": "Trasferimento",
  "Cuenta destino": "Conto di destinazione",
  "Mercadona, Glovo, nómina…": "Spesa, delivery, stipendio…",
  "Five Guys, Zara…": "Five Guys, Zara…",
  "Editar movimiento": "Modifica movimento",
  "Nuevo movimiento": "Nuovo movimento",
  "¿Eliminar este movimiento? El saldo de su cuenta se ajustará al quitarlo.":
    "Eliminare questo movimento? Il saldo del conto si aggiusterà rimuovendolo.",

  "+ Añadir cuenta": "+ Aggiungi conto",
  "Nueva cuenta": "Nuovo conto",
  "Editar cuenta": "Modifica conto",
  "Saldo inicial": "Saldo iniziale",
  "Fecha de ese saldo": "Data di quel saldo",
  "Cuenta activa": "Conto attivo",
  "Corriente": "Conto corrente",
  "Ahorro": "Risparmio",
  "Efectivo": "Contanti",
  "Otra": "Altro",
  "Sin límite mensual": "Senza limite mensile",
  "Cuadrar": "Quadra il saldo",
  "Cuadrar la cuenta": "Quadra il conto",
  "¿Cuánto tienes de verdad?": "Quanto hai davvero?",
  "Según la app tienes": "Secondo l'app hai",
  ". Escribe lo que tienes DE VERDAD (lo que dice el banco o el efectivo contado) y el saldo se ajusta solo. Los movimientos no se tocan.":
    ". Scrivi quello che hai DAVVERO (quello che dice la banca, o i contanti contati) e il saldo si aggiusta da solo. I movimenti non si toccano.",
  "Ya cuadra: no hay nada que ajustar.": "Torna già: niente da aggiustare.",
  "Copiar ID de Firestore": "Copia ID Firestore",
  "¿Eliminar esta cuenta? No se borrarán sus movimientos.":
    "Eliminare questo conto? I suoi movimenti non verranno cancellati.",

  "+ Añadir gasto fijo": "+ Aggiungi spesa fissa",
  "Nuevo gasto fijo": "Nuova spesa fissa",
  "Editar gasto fijo": "Modifica spesa fissa",
  "Gasto fijo activo": "Spesa fissa attiva",
  "Mensual": "Mensile",
  "Anual": "Annuale",
  "Bimensual": "Bimestrale",
  "Trimestral": "Trimestrale",
  "Semestral": "Semestrale",
  "Precio habitual": "Prezzo abituale",
  "Gastos fijos por cuenta": "Spese fisse per conto",
  "Glovo Prime, Préstamo Bankinter, Luz…": "Streaming, rata dell'auto, luce…",
  "¿Eliminar este gasto fijo? No se borrarán los gastos ya registrados.":
    "Eliminare questa spesa fissa? Le spese già registrate non verranno cancellate.",

  "+ Nuevo préstamo": "+ Nuovo prestito",
  "Nuevo préstamo": "Nuovo prestito",
  "Editar préstamo": "Modifica prestito",
  "Pendiente de cobrar": "Da incassare",
  "Intereses a tu favor": "Interessi a tuo favore",
  "Persona": "Persona",
  "Nombre de la persona": "Nome della persona",
  "Capital prestado": "Importo prestato",
  "Interés (%)": "Interessi (%)",
  "Interés fijo (€, opcional)": "Interessi fissi (€, facoltativo)",
  "Vacío = se calcula con el %": "Vuoto = calcolato con la %",
  "Ya pagado hasta ahora (€)": "Già pagato finora (€)",
  "¿Para cuándo debería pagarlo? (opcional)": "Entro quando dovrebbe pagare? (facoltativo)",
  "Notas del préstamo (opcional)": "Note del prestito (facoltative)",
  "Los detalles para tenerlo controlado: qué acordasteis, cuándo prometió pagar, si dejó algo a cuenta…":
    "I dettagli per tenerlo sotto controllo: cosa avete concordato, quando ha promesso di pagare, se ha lasciato un acconto…",
  "¿De qué cuenta sale el dinero?": "Da quale conto escono i soldi?",
  "No descontarlo de ninguna cuenta": "Non scalarlo da nessun conto",
  "¿Qué día se lo diste?": "Che giorno glieli hai prestati?",
  "El capital sale de esa cuenta y cuenta como gasto del día: ese dinero ya no lo tienes. Cuando te lo devuelvan, entrará como ingreso.":
    "L'importo esce da quel conto e conta come uscita del giorno: quei soldi non li hai più. Quando te li restituiranno, entreranno come entrata.",
  "± Ha pagado una parte": "± Ha pagato una parte",
  "💰 Ha pagado todo lo pendiente (liquidar)": "💰 Ha pagato tutto il resto (saldare)",
  "¿Cuánto ha pagado?": "Quanto ha pagato?",
  "¿A qué cuenta entra?": "Su quale conto entra?",
  "Registrar el abono": "Registra il pagamento",
  ". Escribe cuánto ha pagado.": ". Scrivi quanto ha pagato.",
  "Liquidar y cerrar préstamo": "Salda e chiudi il prestito",
  "Le quedan por pagar": "Gli restano da pagare",
  "(capital + interés). Esto registra un ingreso por el total y cierra el préstamo como Pagado.":
    "(capitale + interessi). Questo registra un'entrata per il totale e chiude il prestito come Pagato.",
  "Esto registra un ingreso por el total y cierra el préstamo como Pagado.":
    "Questo registra un'entrata per il totale e chiude il prestito come Pagato.",
  "Préstamo cerrado.": "Prestito chiuso.",
  "— saldado": "— saldato",
  "¿Eliminar este préstamo? Los pagos ya registrados se quedan en Movimientos (ese dinero entró de verdad). Solo si nunca cobró nada, se borra también el gasto de cuando salió el dinero.":
    "Eliminare questo prestito? I pagamenti registrati restano in Movimenti (quei soldi sono entrati davvero). Solo se non ha mai restituito nulla, viene cancellata anche l'uscita di quando i soldi sono usciti.",
  "Abono": "Pagamento",
  "Cuota del plan": "Rata del piano",
  "Liquidación": "Saldo finale",
  "Interés": "Interessi",
  "Pago": "Pagamento",
  "Cobrado este mes ▾": "Incassato questo mese ▾",
  "Intereses este mes ▾": "Interessi questo mese ▾",
  "Toca para ver el desglose por persona": "Tocca per vedere il dettaglio per persona",
  "Este mes todavía no has cobrado ningún pago.": "Questo mese non hai ancora incassato nessun pagamento.",
  "Listo": "Fatto",
  "(tu ganancia). Cada cobro se reparte según su préstamo: en uno de 100 € al 20 %, de cada 30 € cobrados, 5 € son interés.":
    "(il tuo guadagno). Ogni incasso si divide secondo il suo prestito: su 100 € al 20 %, di ogni 30 € incassati, 5 € sono interessi.",

  "+ Nueva meta": "+ Nuovo obiettivo",
  "Nueva meta": "Nuovo obiettivo",
  "Editar meta": "Modifica obiettivo",
  "Crear la meta": "Crea l'obiettivo",
  "¿Para qué ahorras?": "Per cosa risparmi?",
  "¿Cuánto necesitas?": "Quanto ti serve?",
  "¿Para cuándo? (opcional)": "Entro quando? (facoltativo)",
  "Viaje a Bolivia, arreglar el baño…": "Un viaggio, sistemare il bagno…",
  "Huchas para lo que quieres conseguir: un viaje, una reparación, un capricho. El dinero sigue en tus cuentas — aquí solo lo apartas.":
    "Salvadanai per ciò che vuoi ottenere: un viaggio, una riparazione, uno sfizio. I soldi restano sui tuoi conti — qui li metti solo da parte.",
  "Todavía no tienes ninguna meta. Un viaje, una reparación de casa, un capricho grande… ponle nombre y una cantidad, y ve apartando.":
    "Non hai ancora nessun obiettivo. Un viaggio, una riparazione, un grande sfizio… dagli un nome e una cifra, e comincia a mettere da parte.",
  "¿Eliminar esta meta? El dinero sigue en tus cuentas — solo se borra la hucha.":
    "Eliminare questo obiettivo? I soldi restano sui tuoi conti — si cancella solo il salvadanaio.",
  "¿Borrar esta aportación?": "Cancellare questo versamento?",

  "Total de gastos": "Totale uscite",
  "Total de ingresos": "Totale entrate",
  "Gastos por categoría": "Uscite per categoria",
  "Ingresos por categoría": "Entrate per categoria",
  "Gastos por lugar": "Spese per luogo",
  "Buscar: Five Guys, KFC, Taco Bell…": "Cerca: Five Guys, KFC, Taco Bell…",

  "+ Añadir categoría": "+ Aggiungi categoria",
  "Nueva categoría": "Nuova categoria",
  "Editar categoría": "Modifica categoria",
  "Límite mensual (opcional)": "Limite mensile (facoltativo)",
  "Fijo": "Fissa",
  "Variable": "Variabile",
  "Ocio": "Svago",
  "PrestamoDado": "Prestito concesso",
  "Comida a domicilio": "Cibo a domicilio",
  "¿Eliminar esta categoría? Sus movimientos no se borran: quedarán como 'sin categoría'.":
    "Eliminare questa categoria? I suoi movimenti non si cancellano: resteranno come 'senza categoria'.",

  "Sesión iniciada con Firebase Auth": "Sessione avviata con Firebase Auth",
  "Cambiar contraseña": "Cambia password",
  "Idioma": "Lingua",
  "El idioma de toda la app en este dispositivo.": "La lingua di tutta l'app su questo dispositivo.",
  "Temas": "Temi",
  "Cambia el aspecto de toda la app. «Original» la deja como estaba.":
    "Cambia l'aspetto di tutta l'app. «Scuro (originale)» la rimette com'era.",
  "Configuración": "Impostazioni",
  "Ver la guía de la app otra vez": "Rivedi la guida dell'app",
  "Exportar mis datos": "Esporta i miei dati",
  "Importar desde una copia": "Importa da un backup",
  "Datos importados correctamente.": "Dati importati correttamente.",
  "No se pudo importar el archivo. ¿Es una copia válida exportada desde aquí?":
    "Impossibile importare il file. È un backup valido esportato da qui?",
  "Esto añadirá todo lo que haya en el archivo a tus datos actuales (no borra nada existente). ¿Continuar?":
    "Questo aggiungerà tutto il contenuto del file ai tuoi dati attuali (non cancella nulla di esistente). Continuare?",
  "No se pudo enviar el email. Inténtalo de nuevo.": "Impossibile inviare l'email. Riprova.",
  "No se pudo guardar. Inténtalo de nuevo.": "Impossibile salvare. Riprova.",

  "Oscuro (original)": "Scuro (originale)",
  "Claro": "Chiaro",
  "Por defecto": "Predefiniti",
  "Países": "Paesi",
  "España": "Spagna",
  "Bolivia": "Bolivia",
  "Brasil": "Brasile",
  "Italia": "Italia",
  "Francia": "Francia",
  "Rosa pastel": "Rosa pastello",
  "Español": "Español",
  "Português (Brasil)": "Português (Brasil)",

  "¡Bienvenido! 👋": "Benvenuto! 👋",
  "Esta es tu app: tu día a día y tu dinero, en un solo sitio y a tu manera. Te enseño lo básico en cuatro pasos — medio minuto.":
    "Questa è la tua app: la tua vita quotidiana e i tuoi soldi, in un unico posto e a modo tuo. Ti mostro le basi in quattro passi — mezzo minuto.",
  "El menú": "Il menù",
  "Aquí está TODO, en dos bloques: «Tu día» (rutina, calendario, comidas…) y «Tu dinero» (cuentas, movimientos, préstamos…). Ninguna pantalla escondida.":
    "Qui c'è TUTTO, in due blocchi: «La tua giornata» (routine, calendario, pasti…) e «I tuoi soldi» (conti, movimenti, prestiti…). Nessuna schermata nascosta.",
  "Tu cuenta y tus colores": "Il tuo account e i tuoi colori",
  "Desde aquí eliges el tema de la app — claro u oscuro, o uno con carácter (países y más) — y gestionas tu perfil.":
    "Da qui scegli il tema dell'app — chiaro o scuro, o uno con carattere (paesi e altro) — e gestisci il tuo profilo.",
  "Tuya de verdad": "Davvero tua",
  "Toca todo sin miedo: cualquier cosa que borre algo te pregunta antes y te dice qué va a pasar. Y si algo no encaja con tu vida, se cambia — para eso es tuya. ¡A por ello!":
    "Tocca tutto senza paura: qualsiasi cosa cancelli qualcosa te lo chiede prima e ti dice cosa succederà. E se qualcosa non si adatta alla tua vita, si cambia — per questo è tua. Vai!",
  "Saltar": "Salta",
  "Siguiente →": "Avanti →",
  "¡Listo!": "Fatto!",

  "Balance": "Bilancio",
  "sin fecha": "senza data",
  "Sin categoría": "Senza categoria",
  "sin categoría": "senza categoria",

  "Ayer quedó sin cerrar.": "Ieri è rimasto aperto.",
  "Cerrar ayer": "Chiudi ieri",
  "Los 4 innegociables": "I 4 non negoziabili",
  "Los cuatro = día cumplido. No hay medias tintas.": "Tutti e quattro = giornata completata. Niente mezze misure.",
  "Sin comida fuera sin planificar": "Niente pasti fuori non pianificati",
  "El entreno que toque": "L'allenamento del giorno",
  "En la cama antes de las 23:15": "A letto prima delle 23:15",
  "4 piezas de fruta": "4 frutti",
  "Dientes 3 veces": "Denti 3 volte",
  "Cena dejada preparada": "Cena lasciata pronta",
  "Algo de verdura": "Un po' di verdura",
  "Bonus": "Bonus",
  "Cerrar el día": "Chiudi la giornata",
  "Guardar cambios": "Salva modifiche",
  "Corregir": "Correggi",
  "✎ Corregir otro día": "✎ Correggi un altro giorno",
  "✎ Ajustar este horario": "✎ Regola questo orario",
  "✎ Editar ejercicios": "✎ Modifica esercizi",
  "Apuntes del día (opcional)": "Appunti del giorno (facoltativi)",
  "Peso (kg) — 1 vez por semana basta": "Peso (kg) — 1 volta a settimana basta",
  "Racha:": "Serie:",
  "Racha": "Serie",
  "días · Día": "giorni · Giorno",
  "Día · hoy": "Giorno · oggi",
  "Día": "Giorno",
  "Semana": "Settimana",
  "Qué toca hoy": "Cosa tocca oggi",
  "Hoy toca:": "Oggi tocca:",
  "Tocar para registrarlo": "Tocca per registrarlo",
  "El día, hora a hora": "La giornata, ora per ora",
  "Marcar como hecho": "Segna come fatto",
  "Desmarcar todo": "Deseleziona tutto",
  "☑ Para hacer hoy": "☑ Da fare oggi",
  "＋ Cita o imprevisto": "＋ Appuntamento o imprevisto",
  "⏳ Algo quedó a medias": "⏳ Qualcosa è rimasto a metà",
  "🍎 Fruta 1": "🍎 Frutto 1",
  "🍊 Fruta 2": "🍊 Frutto 2",
  "🍌 Fruta 3": "🍌 Frutto 3",
  "🍇 Fruta 4": "🍇 Frutto 4",
  "🪒 Rasurarse": "🪒 Radersi",
  "La del bonus: con esta van las 4 piezas": "Quello del bonus: con questo arrivi a 4",
  "Comida:": "Pranzo:",
  "Cena:": "Cena:",
  "Comer": "Pranzo",
  "Dormir": "Dormire",
  "Levantarte con calma": "Alzarsi con calma",
  "Descanso de verdad": "Riposo vero",
  "Es el día que sostiene la semana": "È il giorno che regge la settimana",
  "Preparar la semana": "Preparare la settimana",
  "Batch cooking (hasta las 13:00)": "Batch cooking (fino alle 13)",
  "Las comidas de la semana, del menú": "I pasti della settimana, dal menù",
  "Platos y cocina recogida": "Piatti fatti, cucina in ordine",
  "Mochila del gimnasio hecha · menú a la vista": "Borsa della palestra pronta · menù in vista",
  "Todo listo. Falta que tú digas YA.": "Tutto pronto. Manca solo il tuo VIA.",
  "START · empezar hoy 💪": "START · comincia oggi 💪",
  "La racha y los puntos del día": "La serie e i punti del giorno",
  "El bote de recompensas": "Il barattolo delle ricompense",
  "La fase de estudio (30 → 60 min)": "La fase di studio (30 → 60 min)",
  "Las semanas 6/7 y los logros": "Le settimane 6/7 e i traguardi",
  "Día 1": "Giorno 1",
  "Un momento, están llegando de Firebase. Tu racha y tus días están guardados. Si esto no avanza, revisa la conexión.":
    "Un attimo, stanno arrivando da Firebase. La tua serie e i tuoi giorni sono salvati. Se non va avanti, controlla la connessione.",
  "Estudio": "Studio",
  "· 30 min (fase 1)": "· 30 min (fase 1)",
  "Estudio: fase 1 · 30 min/día. Sube sola con 2 semanas seguidas a 6 de 7.":
    "Studio: fase 1 · 30 min/giorno. Sale da sola con 2 settimane di fila a 6 su 7.",

  "Guardar el entreno": "Salva l'allenamento",
  "¿De qué día es?": "Di che giorno è?",
  "Si lo apuntas tarde (o pasada la medianoche), pon el día en que entrenaste":
    "Se lo annoti tardi (o dopo mezzanotte), metti il giorno in cui ti sei allenato",
  "Duración (min)": "Durata (min)",
  "reps": "reps",
  "Peso": "Peso",
  "Los kg de la serie 1": "I kg della serie 1",
  "Los kg de la serie 2": "I kg della serie 2",
  "Los kg de la serie 3": "I kg della serie 3",
  "Últimos entrenos": "Ultimi allenamenti",
  "Pierna": "Gambe",
  "Tirón": "Tirata",
  "Empuje": "Spinta",
  "Core + caminata": "Core + camminata",
  "Piscina": "Piscina",
  "Caminata": "Camminata",
  "En casa": "A casa",
  "Cómo se hace": "Come si fa",
  "Plan de serie ·": "Piano base ·",
  "Press banca": "Panca piana",
  "Press de hombro": "Lento avanti",
  "Press de hombro (máquina o mancuernas)": "Lento avanti (macchina o manubri)",
  "Jalón al pecho": "Lat machine",
  "Jalón agarre cerrado (puños mirándose)": "Lat machine presa stretta (pugni di fronte)",
  "Remo en máquina": "Rematore alla macchina",
  "Remo en máquina (la barra hacia ti)": "Rematore alla macchina (barra verso di te)",
  "Remo a una mano con el chaleco": "Rematore a un braccio con il giubbotto",
  "Curl en máquina": "Curl alla macchina",
  "Curl martillo con mancuernas": "Curl a martello con manubri",
  "Curl femoral (tumbado o sentado)": "Leg curl (sdraiato o seduto)",
  "Extensiones de cuádriceps": "Leg extension",
  "Hacka (o prensa)": "Hack squat (o pressa)",
  "Hacka / prensa": "Hack squat / pressa",
  "Peso muerto rumano con mancuernas": "Stacco rumeno con manubri",
  "Gemelos de pie": "Polpacci in piedi",
  "Abductor o aductor (alterna semanas)": "Abduttori o adduttori (alterna le settimane)",
  "Lumbar (espalda baja)": "Lombari",
  "Elevaciones laterales (máquina o mancuernas)": "Alzate laterali (macchina o manubri)",
  "Cruces en polea (alta o baja, alterna)": "Croci ai cavi (alti o bassi, alterna)",
  "Posterior en polea cruzada": "Deltoide posteriore ai cavi incrociati",
  "Tríceps en polea (cuerda o barra, alterna)": "Tricipiti ai cavi (corda o barra, alterna)",
  "Crunch en máquina": "Crunch alla macchina",
  "Elevaciones de piernas (tumbado o colgado)": "Sollevamento gambe (sdraiato o appeso)",
  "Plancha": "Plank",
  "Flexiones": "Piegamenti",
  "Flexiones diamante": "Piegamenti a diamante",
  "Flexiones seguidas": "Piegamenti di fila",
  "Sentadillas con el chaleco": "Squat con il giubbotto",
  "Zancadas alternas": "Affondi alternati",
  "Caminata en cuesta (cinta 10–12 % · 5 km/h)": "Camminata in salita (tapis 10–12 % · 5 km/h)",
  "La primera vez apunta tu peso; desde entonces la app te lo trae puesto y avisa cuando toque subir":
    "La prima volta annota il tuo peso; da lì in poi l'app lo precompila e avvisa quando è ora di salire",
  "Si está imposible: ejercicios 1 y 2 se esperan, del 3 en adelante cualquier máquina del mismo grupo vale, y si no hay manera → piscina. Cuenta igual.":
    "Se è impossibile: gli esercizi 1 e 2 si aspettano, dal 3 in poi va bene qualsiasi macchina dello stesso gruppo, e se non c'è verso → piscina. Conta lo stesso.",
  "El gimnasio estaba lleno": "La palestra era piena",
  "¿Te ha molestado la ingle hoy? 0 = nada · 10 = mucho": "L'inguine ti ha dato fastidio oggi? 0 = per niente · 10 = molto",
  "El aductor con suavidad mientras la ingle esté delicada; si molesta, fuera y punto":
    "Gli adduttori con delicatezza finché l'inguine è sensibile; se dà fastidio, via e basta",
  "Lo único nuevo: glúteo y femoral de verdad. Si la ingle avisa, menos peso y menos recorrido":
    "L'unica novità: glutei e femorali sul serio. Se l'inguine avvisa, meno peso e meno escursione",
  "Si vas justo de tiempo, este es el que se cae": "Se sei di fretta, questo è quello da saltare",
  "~10 min · vale mientras trabajas": "~10 min · va bene mentre lavori",
  "Crear una rutina propia": "Crea una routine tua",
  "＋ Rutina": "＋ Routine",
  "Cambiar": "Cambia",

  "El duelo de la semana": "Il duello della settimana",
  "Puntos de esta semana, de lunes a hoy. Gana quien se cuida — no quien se machaca: los puntos salen de dormir, moverse, comer bien y cumplir lo tuyo. Un día redondo = los 4 innegociables cumplidos. Perder este duelo también es ganar.":
    "I punti di questa settimana, da lunedì a oggi. Vince chi si prende cura di sé — non chi si distrugge: i punti vengono da dormire, muoversi, mangiare bene e mantenere le proprie promesse. Una giornata perfetta = i 4 non negoziabili completati. Perdere questo duello è vincere lo stesso.",
  "Empate": "Pareggio",
  "Puntos": "Punti",
  "Días redondos": "Giornate perfette",
  "Entrenos": "Allenamenti",
  "Semanas 6/7": "Settimane 6/7",
  "El bote": "Il barattolo",
  "bote total": "totale barattolo",
  "disponible para gastar": "disponibile da spendere",
  "· Cada día cumplido suma lo que NO te gastas en comida fuera.": "· Ogni giornata completata somma quello che NON spendi mangiando fuori.",
  "Nueva recompensa": "Nuova ricompensa",
  "Añade recompensas: pavos, piezas del PC, el voucher del AZ-900… Nunca comida.":
    "Aggiungi ricompense: crediti, pezzi del PC, il voucher AZ-900… Mai cibo.",
  "Cuesta (€)": "Costa (€)",
  "Retos de fuerza": "Sfide di forza",
  "Apunta el peso una vez por semana en Hoy → Apuntes del día.": "Annota il peso una volta a settimana in Oggi → Appunti del giorno.",
  "Apunta tu peso en Hoy y salen sus niveles (van en proporción a tu peso).":
    "Annota il tuo peso in Oggi e compaiono i livelli (proporzionali al tuo peso).",
  "Aún sin marca: registra un entreno con este ejercicio. Primer reto:": "Ancora nessun record: registra un allenamento con questo esercizio. Prima sfida:",
  "Valoraciones estimadas con estándares de fuerza internacionales, entre gente que entrena — comparado con la población general estás bastante más arriba. Los retos con kilos van en proporción a tu peso corporal: si tú bajas, ellos bajan contigo.":
    "Valutazioni stimate con standard internazionali di forza, tra chi si allena — rispetto alla popolazione generale sei ben più su. Le sfide coi chili sono proporzionali al tuo peso corporeo: se tu scendi, scendono con te.",
  "🏅 0 medallas": "🏅 0 medaglie",
  "Fuerza — mejor serie por sesión": "Forza — miglior serie per sessione",
  "Peso — hacia 84 kg": "Peso — verso gli 84 kg",
  "objetivo 84": "obiettivo 84",
  "mejor: 0": "record: 0",
  "Logros · 0/18": "Traguardi · 0/18",
  "Primer día cumplido": "Prima giornata completata",
  "Primera semana 6 de 7": "Prima settimana 6 su 7",
  "Primer mes cumplido": "Primo mese completato",
  "Racha de 7 días": "Serie di 7 giorni",
  "Racha de 14 días": "Serie di 14 giorni",
  "Racha de 30 días": "Serie di 30 giorni",
  "10 entrenos": "10 allenamenti",
  "25 entrenos": "25 allenamenti",
  "50 entrenos": "50 allenamenti",
  "Primera piscina": "Prima piscina",
  "Primera subida de peso": "Primo aumento di carico",
  "Subida en 5 ejercicios": "Aumento su 5 esercizi",
  "Primera recompensa canjeada": "Prima ricompensa riscattata",
  "Fase 2 de estudio": "Fase 2 di studio",
  "Fase 4: una hora al día": "Fase 4: un'ora al giorno",
  "Teórico de moto aprobado": "Teoria della moto superata",
  "AZ-900 aprobado": "AZ-900 superato",
  "Carnet A2": "Patente A2",
  "Tasa DGT pagada": "Tassa della motorizzazione pagata",
  "Psicotécnico": "Visita psicotecnica",
  "Práctico de circuito": "Pratica in circuito",
  "Práctico de circulación": "Pratica su strada",
  "Consulta de fisio por la ingle": "Visita dal fisio per l'inguine",
  "Todavía no hay ninguno. El primero es hoy.": "Ancora nessuno. Il primo è oggi.",
  "Ver mi progreso y el bote →": "Vedi i miei progressi e il barattolo →",

  "El menú de la semana": "Il menù della settimana",
  "¿Qué coméis en casa esta semana?": "Cosa mangiate a casa questa settimana?",
  "Hacer el menú de esta semana": "Crea il menù di questa settimana",
  "El menú es": "Il menù è",
  "de casa": "di casa",
  ": el mismo para los dos, se mire desde la app que se mire — nadie cocina dos veces. Marcad juntos lo que os apetezca: con lo marcado salen ahora":
    ": lo stesso per entrambi, da qualunque app lo si guardi — nessuno cucina due volte. Spuntate insieme quello che vi va: con ciò che è spuntato escono ora",
  "8 desayunos, 14 comidas y 15 cenas": "8 colazioni, 14 pranzi e 15 cene",
  "Todavía no hay menú para esta semana. Marcad los ingredientes y dadle al botón: saldrá priorizando lo rápido (AirFryer, horno o pocos pasos), y luego cada día se puede retocar con el lápiz.":
    "Ancora nessun menù per questa settimana. Spuntate gli ingredienti e premete il pulsante: uscirà dando priorità al veloce (friggitrice ad aria, forno o pochi passaggi), e poi ogni giorno si ritocca con la matita.",
  "Haz tu menú de la semana con TUS ingredientes →": "Crea il tuo menù della settimana con i TUOI ingredienti →",
  "Platos vuestros": "I vostri piatti",
  "＋ Plato vuestro": "＋ Piatto vostro",
  "Comida fuera esta semana:": "Pasti fuori questa settimana:",
  "Proteína": "Proteine",
  "Hidratos": "Carboidrati",
  "Verdura": "Verdure",
  "Legumbres": "Legumi",
  "Lácteos y básicos": "Latticini e basici",
  "De postre": "Per dolce",
  "Pollo": "Pollo",
  "Ternera picada": "Macinato di manzo",
  "Lomo de cerdo": "Lonza di maiale",
  "Salchichas": "Salsicce",
  "Bacon": "Pancetta",
  "Chorizo": "Chorizo",
  "Jamón / fiambre de pavo": "Prosciutto / fesa di tacchino",
  "Atún en lata": "Tonno in scatola",
  "Merluza": "Nasello",
  "Salmón": "Salmone",
  "Huevos": "Uova",
  "Arroz": "Riso",
  "Pasta": "Pasta",
  "Patatas": "Patate",
  "Pan": "Pane",
  "Avena": "Avena",
  "Cuscús": "Cuscus",
  "Harina (crepes y pancakes)": "Farina (crêpe e pancake)",
  "Base de pizza": "Base per pizza",
  "Tortillas de trigo (wraps)": "Piadine (wrap)",
  "Tomate frito / triturado": "Passata / polpa di pomodoro",
  "Lechuga (ensalada)": "Lattuga (insalata)",
  "Zanahoria (triturada)": "Carota (grattugiata)",
  "Cebolla (en la salsa)": "Cipolla (nel sugo)",
  "Brócoli (con queso)": "Broccoli (col formaggio)",
  "Calabacín (en crema)": "Zucchine (in vellutata)",
  "Espinacas (trituradas)": "Spinaci (frullati)",
  "Lentejas": "Lenticchie",
  "Garbanzos": "Ceci",
  "Alubias": "Fagioli",
  "Leche": "Latte",
  "Queso": "Formaggio",
  "Yogur griego": "Yogurt greco",
  "Mantequilla": "Burro",
  "ColaCao / Cacaolat": "Cacao solubile",
  "Caldo de pollo": "Brodo di pollo",
  "Fruta (todas)": "Frutta (tutta)",
  "Frutos secos": "Frutta secca",
  "Pasta boloñesa (verdura en la salsa)": "Pasta alla bolognese (verdure nel sugo)",
  "Sándwich integral de pollo": "Panino integrale al pollo",
  "¿Qué falta en casa?": "Cosa manca a casa?",
  "+ Añadir a la lista": "+ Aggiungi alla lista",
  "Elige categoría, escribe y dale a intro · toca para marcar o reponer · mantén pulsado para borrar":
    "Scegli la categoria, scrivi e premi invio · tocca per spuntare o ricomprare · tieni premuto per cancellare",
  "No falta nada ✨": "Non manca niente ✨",
  "Quitar de la lista": "Togli dalla lista",
  "Crear una categoría": "Crea una categoria",
  "Limpieza": "Pulizie",
  "Cosas para la casa": "Cose per casa",
  "Muebles": "Mobili",
  "Electrodomésticos": "Elettrodomestici",

  "La mochila de la oficina": "La borsa dell'ufficio",
  "Repásala la noche de antes (el lunes te lo recuerda el horario) y un vistazo por la mañana. Las marcas se borran solas al día siguiente, listas para la próxima.":
    "Controllala la sera prima (il lunedì te lo ricorda l'orario) e un'occhiata al mattino. Le spunte si cancellano da sole il giorno dopo, pronte per la prossima.",
  "Portátil y cargador": "Portatile e caricatore",
  "Auriculares": "Cuffie",
  "Botella de agua": "Bottiglia d'acqua",
  "Tupper o comida": "Schiscetta o pranzo",
  "Tarjeta o llaves de la oficina": "Badge o chiavi dell'ufficio",
  "Cartera y transporte": "Portafoglio e abbonamento",
  "Ropa de mañana lista": "Vestiti di domani pronti",
  "Para el camino": "Per la strada",
  "¿Algo más que llevar?": "Qualcos'altro da portare?",
  "+ Apuntar regla": "+ Segna il ciclo",
  "Calendario personal": "Calendario personale",
  "＋ Añadir": "＋ Aggiungi",
};

export const PATRONES_IT = [
  [/^Hola, (.+)$/, "Ciao, $1"],
  [/^Límite mensual (.+)$/, "Limite mensile $1"],
  [/^Saldo inicial (.+) · desde (.+)$/, "Saldo iniziale $1 · dal $2"],
  [/^Prestado (.+) · para el (.+)$/, "Prestato $1 · entro il $2"],
  [/^Prestado (.+?) \+ interés (.+?) = debe (.+?) · ya ha pagado (.+)$/, "Prestato $1 + interessi $2 = deve $3 · già pagato $4"],
  [/^Prestado (.+?) \+ interés (.+?) = debe (.+)$/, "Prestato $1 + interessi $2 = deve $3"],
  [/^Prestado (.+?) · ya ha pagado (.+)$/, "Prestato $1 · già pagato $2"],
  [/^Prestado (.+)$/, "Prestato $1"],
  [/^pendiente de (.+)$/, "su $1 da incassare"],
  [/^Pagado este mes: (.+?) \((.+?)\) · Pendiente: (.+)$/, "Pagato questo mese: $1 ($2) · Rimanente: $3"],
  [/^Historial: (\d+) pagos? · (.+) cobrados$/, "Cronologia: $1 pagamenti · $2 incassati"],
  [/^Historial · (.+)$/, "Cronologia · $1"],
  [/^Cobrado en (.+)$/, "Incassato a $1"],
  [/^Total (.+?) — capital (.+?) \+ intereses$/, "Totale $1 — capitale $2 + interessi"],
  [/^Capital (.+?) · interés (.+)$/, "Capitale $1 · interessi $2"],
  [/^Capital (.+)$/, "Capitale $1"],
  [/^Cuadrar · (.+)$/, "Quadra · $1"],
  [/^Abono · (.+)$/, "Pagamento · $1"],
  [/^Liquidar deuda · (.+)$/, "Salda il debito · $1"],
  [/^Interés pagado · (.+)$/, "Interessi pagati · $1"],
  [/^Transferencia enviada a (.+)$/, "Trasferimento inviato a $1"],
  [/^Transferencia recibida de (.+)$/, "Trasferimento ricevuto da $1"],
  [/^Transferencia · (.+)$/, "Trasferimento · $1"],
  [/^Con (.+?) queda$/, "Con $1 è"],
  [/^todo saldado$/, "tutto saldato"],
  [/^: el préstamo se cerrará como Pagado\.$/, ": il prestito verrà chiuso come Pagato."],
  [/^Quedarán por pagar$/, "Resteranno da pagare"],
  [/^Se ajustará$/, "Verrà aggiustato di"],
  [/^para que el saldo diga (.+)\.$/, "perché il saldo dica $1."],
  [/^\(de (.+) en total\)\. Escribe cuánto ha pagado\.$/, "(su $1 in totale). Scrivi quanto ha pagato."],
  [/^\(de (.+?) en total, ya había pagado (.+?)\)\.$/, "(su $1 in totale, $2 già pagati)."],
  [/^Te hemos enviado un email a (.+) para cambiar la contraseña\.$/, "Ti abbiamo inviato un'email a $1 per cambiare la password."],
  [/^(\d+) de (\d+) pantallas?$/, "$1 di $2 schermate"],
  [/^(\d+) de (\d+)$/, "$1 di $2"],
  [/^Debe (.+)$/, "Deve $1"],
  [/^ya ha pagado (.+)$/, "già pagato $1"],
  [/^· ya ha pagado (.+)$/, "· già pagato $1"],
  [/^· para el (.+)$/, "· entro il $1"],
  [/^AHORA · (.+)$/, "ORA · $1"],
  [/^Ahora: (.+)$/, "Ora: $1"],
  [/^Pierna — tus máquinas de siempre$/, "Gambe — le tue solite macchine"],
  [/^Tirón — espalda y bíceps$/, "Tirata — schiena e bicipiti"],
  [/^Empuje — pecho, hombro y tríceps$/, "Spinta — petto, spalle e tricipiti"],
  [/^Caminata \+ core — el día ligero$/, "Camminata + core — il giorno leggero"],
  [/^Piscina con tu hermano$/, "Piscina con tuo fratello"],
  [/^Libre o caminata suave$/, "Libero o camminata tranquilla"],
  [/^Descanso · batch cooking$/, "Riposo · batch cooking"],
  [/^· empezaste el (.+)$/, "· hai iniziato il $1"],
  [/^· media de las (\d+) anteriores: (.+)$/, "· media delle ultime $1: $2"],
  [/^Referencia: (.+)\/día$/, "Riferimento: $1/giorno"],
  [/^(\d+) días? · Día (\d+)$/, "$1 giorni · Giorno $2"],
  [/^Día (\d+)$/, "Giorno $1"],
  [/^mejor: (\d+)$/, "record: $1"],
  [/^objetivo (\d+)$/, "obiettivo $1"],
  [/^🏅 (\d+) medallas?$/, "🏅 $1 medaglie"],
  [/^Logros · (\d+)\/(\d+)$/, "Traguardi · $1/$2"],
  [/^Racha de (\d+) días$/, "Serie di $1 giorni"],
  [/^(\d+) entrenos$/, "$1 allenamenti"],
  [/^Los kg de la serie (\d+)$/, "I kg della serie $1"],
  [/^Faltó: (.+)$/, "Mancava: $1"],
  [/^Día cerrado \(no cumplido\) · (\d+) puntos$/, "Giornata chiusa (non completata) · $1 punti"],
  [/^✓ Día cumplido · (\d+) puntos$/, "✓ Giornata completata · $1 punti"],
  [/^(\d+) puntos$/, "$1 punti"],
  [/^Aún sin marcar: (.+)\. Un toque ahora y el día no se escapa\.$/, "Ancora da spuntare: $1. Un tocco adesso e la giornata non scappa."],
  [/^Cerrando AYER · (.+)$/, "Chiusura di IERI · $1"],
  [/^Corrigiendo · (.+)$/, "Correzione · $1"],
];
