// Português do Brasil — traduzido com carinho, nada de tradutor automático.
// A chave es la frase en español tal y como aparece en la app; si la frase
// cambia en el código, deja de encontrarse aquí y aparece en
// window.__faltantes (la lista de deberes del traductor).
//
// Criterio: vocabulario brasileño de apps de banco/finanzas de verdad
// ("poupança", "empréstimo", "extrato", "salvar"), tratamiento de "você",
// y la misma calidez que tiene el texto en español.

export const DICCIONARIO_PT = {
  // ---------- Acceso ----------
  "Acceso privado": "Acesso privado",
  "Tus finanzas, en un solo lugar.": "Suas finanças, em um só lugar.",
  "Email": "E-mail",
  "Contraseña": "Senha",
  "Entrar": "Entrar",
  "tu@email.com": "voce@email.com",
  "tu@correo.com": "voce@email.com",
  "Cerrar sesión": "Sair",
  "Cargando tus datos…": "Carregando seus dados…",

  // ---------- Menú y secciones ----------
  "Tu día": "Seu dia",
  "Tu dinero": "Seu dinheiro",
  "Hoy": "Hoje",
  "Calendario": "Calendário",
  "Entreno": "Treino",
  "Menú": "Cardápio",
  "Compras": "Compras",
  "Ciclo": "Ciclo",
  "Oficina": "Escritório",
  "Progreso": "Progresso",
  "Dashboard": "Painel",
  "Movimientos": "Movimentações",
  "Cuentas": "Contas",
  "Gastos fijos": "Gastos fixos",
  "Préstamos": "Empréstimos",
  "Metas": "Metas",
  "Gráficos": "Gráficos",
  "Categorías": "Categorias",
  "Cartera": "Carteira",
  "Abrir menú": "Abrir menu",
  "Mi cuenta": "Minha conta",

  // ---------- Comunes ----------
  "Añadir": "Adicionar",
  "+ Añadir": "+ Adicionar",
  "Guardar": "Salvar",
  "Cancelar": "Cancelar",
  "Cerrar": "Fechar",
  "Editar": "Editar",
  "Eliminar": "Excluir",
  "Nombre": "Nome",
  "Fecha": "Data",
  "Importe": "Valor",
  "Importe total": "Valor total",
  "Tipo": "Tipo",
  "Estado": "Status",
  "Cuenta": "Conta",
  "Categoría": "Categoria",
  "Frecuencia": "Frequência",
  "Nota (opcional)": "Observação (opcional)",
  "Icono (opcional)": "Ícone (opcional)",
  "Subcategoría (opcional)": "Subcategoria (opcional)",
  "Total": "Total",
  "Todo": "Tudo",
  "Mes": "Mês",
  "Año": "Ano",
  "Mes anterior": "Mês anterior",
  "Mes siguiente": "Mês seguinte",
  "Ver todas": "Ver todas",
  "Ver todos": "Ver todos",
  "Historial": "Histórico",
  "Activo": "Ativo",
  "Pagado": "Pago",
  "pendiente": "pendente",
  "Debe": "Deve",
  "Importando…": "Importando…",

  // ---------- Días de la semana (calendario) ----------
  "Lun": "Seg",
  "Mar": "Ter",
  "Mié": "Qua",
  "Jue": "Qui",
  "Vie": "Sex",
  "Sáb": "Sáb",
  "Dom": "Dom",

  // ---------- Dashboard ----------
  "Saldo total": "Saldo total",
  "Gastos por categoría · este mes": "Gastos por categoria · este mês",
  "Límites del mes": "Limites do mês",
  "Movimientos recientes": "Movimentações recentes",
  "Préstamos activos": "Empréstimos ativos",
  "Suscripciones activas": "Assinaturas ativas",
  "Top gastos por lugar · este mes": "Top gastos por lugar · este mês",
  "Es tu primera vez aquí": "É a sua primeira vez aqui",
  "Puedo rellenar tus cuentas, categorías, suscripciones fijas y préstamos con los datos que ya me pasaste, para que no tengas que escribirlo todo a mano.":
    "Posso preencher suas contas, categorias, assinaturas fixas e empréstimos com os dados que você já me passou, para não ter que digitar tudo à mão.",
  "Importar mis datos iniciales": "Importar meus dados iniciais",
  "Este mes": "Este mês",
  "Ingresos": "Receitas",
  "Gastos": "Despesas",
  "Ingreso": "Receita",
  "Gasto": "Despesa",
  "Estimado": "Estimado",

  // ---------- Movimientos ----------
  "Añadir movimiento": "Adicionar movimentação",
  "+ Añadir movimiento": "+ Adicionar movimentação",
  "Ingresos del mes": "Receitas do mês",
  "Gastos del mes": "Despesas do mês",
  "Diferencia": "Diferença",
  "Ingresos vs. Gastos este mes": "Receitas vs. despesas este mês",
  "Balance del día": "Saldo do dia",
  "Transferencia entre cuentas": "Transferência entre contas",
  "Transferencia": "Transferência",
  "Cuenta destino": "Conta de destino",
  "Mercadona, Glovo, nómina…": "Mercado, iFood, salário…",
  "Five Guys, Zara…": "Five Guys, Zara…",
  "Editar movimiento": "Editar movimentação",
  "Nuevo movimiento": "Nova movimentação",
  "¿Eliminar este movimiento? El saldo de su cuenta se ajustará al quitarlo.":
    "Excluir esta movimentação? O saldo da conta será ajustado ao removê-la.",

  // ---------- Cuentas ----------
  "+ Añadir cuenta": "+ Adicionar conta",
  "Nueva cuenta": "Nova conta",
  "Editar cuenta": "Editar conta",
  "Saldo inicial": "Saldo inicial",
  "Fecha de ese saldo": "Data desse saldo",
  "Cuenta activa": "Conta ativa",
  "Corriente": "Conta-corrente",
  "Ahorro": "Poupança",
  "Efectivo": "Dinheiro vivo",
  "Otra": "Outra",
  "Sin límite mensual": "Sem limite mensal",
  "Cuadrar": "Acertar saldo",
  "Cuadrar la cuenta": "Acertar a conta",
  "¿Cuánto tienes de verdad?": "Quanto você tem de verdade?",
  "Según la app tienes": "Segundo o app você tem",
  ". Escribe lo que tienes DE VERDAD (lo que dice el banco o el efectivo contado) y el saldo se ajusta solo. Los movimientos no se tocan.":
    ". Digite o que você tem DE VERDADE (o que diz o banco ou o dinheiro contado) e o saldo se ajusta sozinho. As movimentações não são alteradas.",
  "Ya cuadra: no hay nada que ajustar.": "Já bate: não há nada para ajustar.",
  "Copiar ID de Firestore": "Copiar ID do Firestore",
  "¿Eliminar esta cuenta? No se borrarán sus movimientos.":
    "Excluir esta conta? As movimentações dela não serão apagadas.",

  // ---------- Gastos fijos ----------
  "+ Añadir gasto fijo": "+ Adicionar gasto fixo",
  "Nuevo gasto fijo": "Novo gasto fixo",
  "Editar gasto fijo": "Editar gasto fixo",
  "Gasto fijo activo": "Gasto fixo ativo",
  "Mensual": "Mensal",
  "Anual": "Anual",
  "Bimensual": "Bimestral",
  "Trimestral": "Trimestral",
  "Semestral": "Semestral",
  "Precio habitual": "Valor habitual",
  "Gastos fijos por cuenta": "Gastos fixos por conta",
  "Glovo Prime, Préstamo Bankinter, Luz…": "iFood, financiamento, luz…",
  "¿Eliminar este gasto fijo? No se borrarán los gastos ya registrados.":
    "Excluir este gasto fixo? As despesas já registradas não serão apagadas.",

  // ---------- Préstamos ----------
  "+ Nuevo préstamo": "+ Novo empréstimo",
  "Nuevo préstamo": "Novo empréstimo",
  "Editar préstamo": "Editar empréstimo",
  "Pendiente de cobrar": "Pendente de receber",
  "Intereses a tu favor": "Juros a seu favor",
  "Persona": "Pessoa",
  "Nombre de la persona": "Nome da pessoa",
  "Capital prestado": "Valor emprestado",
  "Interés (%)": "Juros (%)",
  "Interés fijo (€, opcional)": "Juros fixos (€, opcional)",
  "Vacío = se calcula con el %": "Vazio = calculado pelo %",
  "Ya pagado hasta ahora (€)": "Já pago até agora (€)",
  "¿Para cuándo debería pagarlo? (opcional)": "Para quando deveria pagar? (opcional)",
  "Notas del préstamo (opcional)": "Observações do empréstimo (opcional)",
  "Los detalles para tenerlo controlado: qué acordasteis, cuándo prometió pagar, si dejó algo a cuenta…":
    "Os detalhes para manter o controle: o que combinaram, quando prometeu pagar, se deixou algo adiantado…",
  "¿De qué cuenta sale el dinero?": "De qual conta sai o dinheiro?",
  "No descontarlo de ninguna cuenta": "Não descontar de nenhuma conta",
  "¿Qué día se lo diste?": "Em que dia você emprestou?",
  "El capital sale de esa cuenta y cuenta como gasto del día: ese dinero ya no lo tienes. Cuando te lo devuelvan, entrará como ingreso.":
    "O valor sai dessa conta e conta como despesa do dia: esse dinheiro já não está com você. Quando devolverem, entrará como receita.",
  "± Ha pagado una parte": "± Pagou uma parte",
  "💰 Ha pagado todo lo pendiente (liquidar)": "💰 Pagou tudo o que faltava (quitar)",
  "¿Cuánto ha pagado?": "Quanto pagou?",
  "¿A qué cuenta entra?": "Em qual conta entra?",
  "Registrar el abono": "Registrar o pagamento",
  ". Escribe cuánto ha pagado.": ". Digite quanto pagou.",
  "Liquidar y cerrar préstamo": "Quitar e encerrar empréstimo",
  "Le quedan por pagar": "Ainda faltam pagar",
  "(capital + interés). Esto registra un ingreso por el total y cierra el préstamo como Pagado.":
    "(valor + juros). Isto registra uma receita pelo total e encerra o empréstimo como Pago.",
  "Esto registra un ingreso por el total y cierra el préstamo como Pagado.":
    "Isto registra uma receita pelo total e encerra o empréstimo como Pago.",
  "Préstamo cerrado.": "Empréstimo encerrado.",
  "— saldado": "— quitado",
  "¿Eliminar este préstamo? Los pagos ya registrados se quedan en Movimientos (ese dinero entró de verdad). Solo si nunca cobró nada, se borra también el gasto de cuando salió el dinero.":
    "Excluir este empréstimo? Os pagamentos já registrados ficam em Movimentações (esse dinheiro entrou de verdade). Só se nunca recebeu nada, a despesa de quando o dinheiro saiu também é apagada.",
  "Abono": "Pagamento",
  "Cuota del plan": "Parcela do plano",
  "Liquidación": "Quitação",
  "Interés": "Juros",
  "Pago": "Pagamento",

  // ---------- Metas ----------
  "+ Nueva meta": "+ Nova meta",
  "Nueva meta": "Nova meta",
  "Editar meta": "Editar meta",
  "Crear la meta": "Criar a meta",
  "¿Para qué ahorras?": "Para que você está poupando?",
  "¿Cuánto necesitas?": "Quanto você precisa?",
  "¿Para cuándo? (opcional)": "Para quando? (opcional)",
  "Viaje a Bolivia, arreglar el baño…": "Viagem, arrumar o banheiro…",
  "Huchas para lo que quieres conseguir: un viaje, una reparación, un capricho. El dinero sigue en tus cuentas — aquí solo lo apartas.":
    "Cofrinhos para o que você quer conquistar: uma viagem, um conserto, um mimo. O dinheiro continua nas suas contas — aqui você só o separa.",
  "Todavía no tienes ninguna meta. Un viaje, una reparación de casa, un capricho grande… ponle nombre y una cantidad, y ve apartando.":
    "Você ainda não tem nenhuma meta. Uma viagem, um conserto em casa, um mimo grande… dê um nome e um valor, e vá separando.",
  "¿Eliminar esta meta? El dinero sigue en tus cuentas — solo se borra la hucha.":
    "Excluir esta meta? O dinheiro continua nas suas contas — só o cofrinho é apagado.",
  "¿Borrar esta aportación?": "Excluir este aporte?",

  // ---------- Gráficos ----------
  "Total de gastos": "Total de despesas",
  "Total de ingresos": "Total de receitas",
  "Gastos por categoría": "Despesas por categoria",
  "Ingresos por categoría": "Receitas por categoria",
  "Gastos por lugar": "Despesas por lugar",
  "Buscar: Five Guys, KFC, Taco Bell…": "Buscar: Five Guys, KFC, Taco Bell…",

  // ---------- Categorías ----------
  "+ Añadir categoría": "+ Adicionar categoria",
  "Nueva categoría": "Nova categoria",
  "Editar categoría": "Editar categoria",
  "Límite mensual (opcional)": "Limite mensal (opcional)",
  "Fijo": "Fixo",
  "Variable": "Variável",
  "Ocio": "Lazer",
  "PrestamoDado": "Empréstimo dado",
  "Comida a domicilio": "Comida por aplicativo",
  "¿Eliminar esta categoría? Sus movimientos no se borran: quedarán como 'sin categoría'.":
    "Excluir esta categoria? As movimentações não são apagadas: ficarão como 'sem categoria'.",

  // ---------- Mi cuenta ----------
  "Sesión iniciada con Firebase Auth": "Sessão iniciada com o Firebase Auth",
  "Cambiar contraseña": "Alterar senha",
  "Idioma": "Idioma",
  "El idioma de toda la app en este dispositivo.": "O idioma de todo o app neste dispositivo.",
  "Temas": "Temas",
  "Cambia el aspecto de toda la app. «Original» la deja como estaba.":
    "Mude o visual de todo o app. «Escuro (original)» deixa como estava.",
  "Configuración": "Configurações",
  "Ver la guía de la app otra vez": "Ver o guia do app de novo",
  "Exportar mis datos": "Exportar meus dados",
  "Importar desde una copia": "Importar de uma cópia",
  "Datos importados correctamente.": "Dados importados com sucesso.",
  "No se pudo importar el archivo. ¿Es una copia válida exportada desde aquí?":
    "Não foi possível importar o arquivo. É uma cópia válida exportada daqui?",
  "Esto añadirá todo lo que haya en el archivo a tus datos actuales (no borra nada existente). ¿Continuar?":
    "Isto adicionará tudo o que houver no arquivo aos seus dados atuais (não apaga nada existente). Continuar?",
  "No se pudo enviar el email. Inténtalo de nuevo.": "Não foi possível enviar o e-mail. Tente de novo.",
  "No se pudo guardar. Inténtalo de nuevo.": "Não foi possível salvar. Tente de novo.",

  // ---------- Temas (nombres y grupos del selector) ----------
  "Oscuro (original)": "Escuro (original)",
  "Claro": "Claro",
  "Por defecto": "Padrão",
  "Países": "Países",
  "España": "Espanha",
  "Bolivia": "Bolívia",
  "Brasil": "Brasil",
  "Italia": "Itália",
  "Francia": "França",
  "Rosa pastel": "Rosa pastel",
  "Español": "Español",
  "Português (Brasil)": "Português (Brasil)",

  // ---------- Guía de bienvenida ----------
  "¡Bienvenido! 👋": "Bem-vindo! 👋",
  "Esta es tu app: tu día a día y tu dinero, en un solo sitio y a tu manera. Te enseño lo básico en cuatro pasos — medio minuto.":
    "Este é o seu app: seu dia a dia e seu dinheiro, em um só lugar e do seu jeito. Vou te mostrar o básico em quatro passos — meio minuto.",
  "El menú": "O menu",
  "Aquí está TODO, en dos bloques: «Tu día» (rutina, calendario, comidas…) y «Tu dinero» (cuentas, movimientos, préstamos…). Ninguna pantalla escondida.":
    "Aqui está TUDO, em dois blocos: «Seu dia» (rotina, calendário, refeições…) e «Seu dinheiro» (contas, movimentações, empréstimos…). Nenhuma tela escondida.",
  "Tu cuenta y tus colores": "Sua conta e suas cores",
  "Desde aquí eliges el tema de la app — claro u oscuro, o uno con carácter (países y más) — y gestionas tu perfil.":
    "Aqui você escolhe o tema do app — claro ou escuro, ou um com personalidade (países e mais) — e gerencia o seu perfil.",
  "Tuya de verdad": "Seu de verdade",
  "Toca todo sin miedo: cualquier cosa que borre algo te pregunta antes y te dice qué va a pasar. Y si algo no encaja con tu vida, se cambia — para eso es tuya. ¡A por ello!":
    "Toque em tudo sem medo: qualquer coisa que apague algo pergunta antes e diz o que vai acontecer. E se algo não combinar com a sua vida, a gente muda — para isso o app é seu. Bora!",
  "Saltar": "Pular",
  "Siguiente →": "Próximo →",
  "¡Listo!": "Pronto!",

  // ---------- Otros dinámicos ----------
  "Balance": "Saldo",
  "sin fecha": "sem data",
  "Sin categoría": "Sem categoria",
  "sin categoría": "sem categoria",
};

// Patrones: para los textos que llevan datos dentro (números, nombres,
// fechas). $1, $2… conservan esos datos tal cual.
export const PATRONES_PT = [
  [/^Hola, (.+)$/, "Olá, $1"],
  [/^Límite mensual (.+)$/, "Limite mensal $1"],
  [/^Saldo inicial (.+) · desde (.+)$/, "Saldo inicial $1 · desde $2"],
  [/^Prestado (.+) · para el (.+)$/, "Emprestado $1 · até $2"],
  [/^Prestado (.+?) \+ interés (.+?) = debe (.+?) · ya ha pagado (.+)$/, "Emprestado $1 + juros $2 = deve $3 · já pagou $4"],
  [/^Prestado (.+?) \+ interés (.+?) = debe (.+)$/, "Emprestado $1 + juros $2 = deve $3"],
  [/^Prestado (.+?) · ya ha pagado (.+)$/, "Emprestado $1 · já pagou $2"],
  [/^Prestado (.+)$/, "Emprestado $1"],
  [/^pendiente de (.+)$/, "pendente de $1"],
  [/^Pagado este mes: (.+?) \((.+?)\) · Pendiente: (.+)$/, "Pago este mês: $1 ($2) · Pendente: $3"],
  [/^Historial: (\d+) pagos? · (.+) cobrados$/, "Histórico: $1 pagamentos · $2 recebidos"],
  [/^Historial · (.+)$/, "Histórico · $1"],
  [/^Cuadrar · (.+)$/, "Acertar saldo · $1"],
  [/^Abono · (.+)$/, "Pagamento · $1"],
  [/^Liquidar deuda · (.+)$/, "Quitar dívida · $1"],
  [/^Interés pagado · (.+)$/, "Juros pagos · $1"],
  [/^Transferencia enviada a (.+)$/, "Transferência enviada para $1"],
  [/^Transferencia recibida de (.+)$/, "Transferência recebida de $1"],
  [/^Transferencia · (.+)$/, "Transferência · $1"],
  [/^Con (.+?) queda$/, "Com $1 fica"],
  [/^todo saldado$/, "tudo quitado"],
  [/^: el préstamo se cerrará como Pagado\.$/, ": o empréstimo será encerrado como Pago."],
  [/^Quedarán por pagar$/, "Ainda faltarão pagar"],
  [/^Se ajustará$/, "Será ajustado"],
  [/^para que el saldo diga (.+)\.$/, "para o saldo dizer $1."],
  [/^\(de (.+) en total\)\. Escribe cuánto ha pagado\.$/, "(de $1 no total). Digite quanto pagou."],
  [/^\(de (.+?) en total, ya había pagado (.+?)\)\.$/, "(de $1 no total, já tinha pagado $2)."],
  [/^Te hemos enviado un email a (.+) para cambiar la contraseña\.$/, "Enviamos um e-mail para $1 para alterar a senha."],
  [/^(\d+) de (\d+) pantallas?$/, "$1 de $2 telas"],
  [/^(\d+) de (\d+)$/, "$1 de $2"],
  [/^Debe (.+)$/, "Deve $1"],
  [/^ya ha pagado (.+)$/, "já pagou $1"],
  [/^· ya ha pagado (.+)$/, "· já pagou $1"],
  [/^· para el (.+)$/, "· até $1"],
];
