// Português do Brasil — traduzido com carinho, nada de tradutor automático.
// A chave es la frase en español tal y como aparece en la app; si la frase
// cambia en el código, deja de encontrarse aquí y aparece en
// window.__faltantes (la lista de deberes del traductor).
//
// Criterio: vocabulario brasileño de apps de banco/finanzas de verdad
// ("poupança", "empréstimo", "extrato", "salvar"), tratamiento de "você",
// y la misma calidez que tiene el texto en español.

export const DICCIONARIO_PT = {
  // ---------- Acceso ----------
  "Acceso privado": "Acesso privado",
  "Tus finanzas, en un solo lugar.": "Suas finanças, em um só lugar.",
  "Email": "E-mail",
  "Contraseña": "Senha",
  "Entrar": "Entrar",
  "tu@email.com": "voce@email.com",
  "tu@correo.com": "voce@email.com",
  "Cerrar sesión": "Sair",
  "Cargando tus datos…": "Carregando seus dados…",

  // ---------- Menú y secciones ----------
  "Tu día": "Seu dia",
  "Tu dinero": "Seu dinheiro",
  "Hoy": "Hoje",
  "Calendario": "Calendário",
  "Entreno": "Treino",
  "Menú": "Cardápio",
  "Compras": "Compras",
  "Ciclo": "Ciclo",
  "Oficina": "Escritório",
  "Progreso": "Progresso",
  "Dashboard": "Painel",
  "Movimientos": "Movimentações",
  "Cuentas": "Contas",
  "Gastos fijos": "Gastos fixos",
  "Préstamos": "Empréstimos",
  "Metas": "Metas",
  "Gráficos": "Gráficos",
  "Categorías": "Categorias",
  "Cartera": "Carteira",
  // ---------- Cartera · glosario y avisos ----------
  "Posición": "Posição",
  "Último precio": "Último preço",
  "Variación": "Variação",
  "Cuántas participaciones tienes de esa cosa. Puede ser un número con decimales: 0,5 participaciones de un ETF es la mitad de una, y es completamente normal — se compra por euros, no por unidades enteras.":
    "Quantas cotas você tem daquilo. Pode ser um número com decimais: 0,5 cota de um ETF é metade de uma, e é completamente normal — compra-se por euros, não por unidades inteiras.",
  "Lo que cuesta UNA participación ahora mismo. Tu dinero es este precio multiplicado por tu posición. Sube y baja constantemente; no hace falta mirarlo cada día.":
    "O que custa UMA cota agora mesmo. Seu dinheiro é este preço multiplicado pela sua posição. Sobe e desce o tempo todo; não precisa olhar todo dia.",
  "Cuánto ha cambiado el precio. 'Hoy' compara con ayer: es ruido, sube y baja sin razón que te importe. 'Desde la compra' compara con lo que pagaste: esa es la única que dice si vas ganando o perdiendo de verdad.":
    "Quanto o preço mudou. 'Hoje' compara com ontem: é ruído, sobe e desce sem razão que importe. 'Desde a compra' compara com o que você pagou: essa é a única que diz se você está ganhando ou perdendo de verdade.",
  "¿Qué es un ETF?":
    "O que é um ETF?",
  "Una cesta con cientos o miles de empresas dentro. Comprar un ETF 'mundial' es comprar un trocito de las mayores empresas del planeta de golpe. Si una quiebra, ni lo notas. Por eso es la forma más tranquila de empezar: no hay que acertar cuál ganará.":
    "Uma cesta com centenas ou milhares de empresas dentro. Comprar um ETF 'mundial' é comprar um pedacinho das maiores empresas do planeta de uma vez. Se uma quebra, você nem nota. Por isso é o jeito mais tranquilo de começar: não precisa acertar qual vai ganhar.",
  "(Acc) y (Dist)":
    "(Acc) e (Dist)",
  "Acc = acumulación: los dividendos que pagan las empresas se reinvierten solos dentro del fondo, y crece más rápido. Dist = distribución: te los pagan en efectivo. Para acumular a largo plazo, Acc suele convenir más en España (no pagas impuestos por dividendos que no cobras).":
    "Acc = acumulação: os dividendos que as empresas pagam são reinvestidos sozinhos dentro do fundo, e ele cresce mais rápido. Dist = distribuição: você os recebe em dinheiro. Para acumular no longo prazo, Acc costuma convir mais na Espanha (você não paga imposto por dividendos que não recebe).",
  "Lo más volátil de esta pantalla: puede caer un 50 % en meses y también subirlo. Regla simple: que sea solo una parte pequeña de la cartera y nunca dinero que puedas necesitar.":
    "O mais volátil desta tela: pode cair 50 % em meses e também subir isso. Regra simples: que seja só uma parte pequena da carteira e nunca dinheiro de que você possa precisar.",
  "¿Qué es esta estimación?":
    "O que é esta estimativa?",
  "Parte de lo que tienes invertido AHORA MISMO y calcula qué haría el mercado con ello si diera de media ese % al año (interés compuesto). La aportación mensual es opcional: a 0 ves solo crecer lo tuyo; ponle algo para jugar con '¿y si además aporto?'. La bolsa mundial ha dado ~7 % anual de media histórica, con años de −20 % y de +25 % por el camino. Es para hacerse una idea, no una promesa.":
    "Parte do que você tem investido AGORA MESMO e calcula o que o mercado faria com isso se desse em média esse % ao ano (juros compostos). O aporte mensal é opcional: em 0 você vê só o seu crescer; coloque algo para brincar com 'e se eu também aportar?'. A bolsa mundial deu ~7 % ao ano de média histórica, com anos de −20 % e de +25 % pelo caminho. É para ter uma ideia, não uma promessa.",
  "Las señales":
    "Os sinais",
  "Reglas fijas sobre TUS números: concentración, caídas grandes, precios sin actualizar. No predicen nada — nadie puede — pero avisan de lo que a cualquiera se le pasaría por alto.":
    "Regras fixas sobre os SEUS números: concentração, quedas grandes, preços sem atualizar. Não preveem nada — ninguém pode — mas avisam do que qualquer um deixaria passar.",
  "El símbolo":
    "O símbolo",
  "El código con el que la app busca el precio automáticamente. Acciones de EE. UU.: su ticker (AAPL, AMZN…) con la clave de Finnhub. Cripto: su id de CoinGecko en minúsculas (bitcoin, ethereum). Los ETF europeos no están en el plan gratuito: su precio se copia de Trade Republic con el lápiz, y todo lo demás se calcula igual.":
    "O código com que o app busca o preço automaticamente. Ações dos EUA: seu ticker (AAPL, AMZN…) com a chave do Finnhub. Cripto: seu id do CoinGecko em minúsculas (bitcoin, ethereum). Os ETF europeus não estão no plano gratuito: o preço se copia do Trade Republic com o lápis, e todo o resto se calcula igual.",
  "Sin criptomonedas apuntadas. Si compras bitcoin en Trade Republic, apúntalo aquí y su precio se refresca solo.":
    "Nenhuma criptomoeda anotada. Se você comprar bitcoin no Trade Republic, anote aqui e o preço se atualiza sozinho.",
  "Todavía nada. Cuando compres tu primer ETF o acción en Trade Republic, apúntalo con + Añadir: qué es, cuántas participaciones y a qué precio.":
    "Nada ainda. Quando comprar seu primeiro ETF ou ação no Trade Republic, anote com + Adicionar: o que é, quantas cotas e a que preço.",
  "Todavía no hay nada invertido, así que de momento no hay nada que proyectar. En cuanto apuntes tu primera compra, aquí verás lo que podría llegar a ser con los años. Si quieres jugar mientras tanto, pon una aportación al mes.":
    "Ainda não há nada investido, então por enquanto não há nada para projetar. Assim que anotar sua primeira compra, aqui você verá o que poderia chegar a ser com os anos. Se quiser brincar enquanto isso, coloque um aporte por mês.",
  "Pocas posiciones y ningún fondo indexado. Un ETF mundial (tipo MSCI World) es la forma más simple de diversificar sin pensar.":
    "Poucas posições e nenhum fundo indexado. Um ETF mundial (tipo MSCI World) é o jeito mais simples de diversificar sem pensar.",
  "Hay precios sin actualizar desde hace más de una semana: la ganancia que ves puede no ser la real.":
    "Há preços sem atualizar há mais de uma semana: o ganho que você vê pode não ser o real.",
  "No se pudo guardar. ¿Están publicadas las reglas nuevas de Firebase?":
    "Não foi possível salvar. As regras novas do Firebase estão publicadas?",
  "Clave de Finnhub (gratis en finnhub.io → Get free API key). Se guarda una vez y sirve para refrescar acciones de EE. UU.:":
    "Chave do Finnhub (grátis em finnhub.io → Get free API key). Guarda-se uma vez e serve para atualizar ações dos EUA:",
  // ---------- Cartera · vista ----------
  "Editar posición": "Editar posição",
  "Nueva posición": "Nova posição",
  "Elegir de la lista (opcional)": "Escolher da lista (opcional)",
  "— Escribir a mano —": "— Escrever à mão —",
  "ETF / fondo": "ETF / fundo",
  "Acción": "Ação",
  "Cripto": "Cripto",
  "Símbolo (opcional)": "Símbolo (opcional)",
  "Participaciones": "Cotas",
  "Precio de compra (€/ud)": "Preço de compra (€/cota)",
  "Precio actual (€/ud)": "Preço atual (€/cota)",
  "Vacío = el de compra": "Vazio = o de compra",
  "El símbolo cotiza en…": "O símbolo cota em…",
  "Dólares (EE. UU.)": "Dólares (EUA)",
  "Euros": "Euros",
  "Cuenta de valores": "Conta de valores",
  "Criptomonedas": "Criptomoedas",
  "Instrumento": "Instrumento",
  "Desde la compra": "Desde a compra",
  "Variación hoy": "Variação hoje",
  "↻ Actualizar": "↻ Atualizar",
  "+ Añadir": "+ Adicionar",
  "Señales": "Sinais",
  "— hoy sin dato": "— hoje sem dado",
  "Toca una fila para editarla. Último precio": "Toque em uma linha para editá-la. Último preço",
  "· ETF": "· ETF",
  "· (Acc)/(Dist)": "· (Acc)/(Dist)",
  "· Cripto": "· Cripto",
  "poner clave de Finnhub": "colocar chave do Finnhub",
  "¿Cuánto podría llegar a ser?": "Quanto poderia chegar a ser?",
  "Parte de lo que tienes invertido ahora mismo:": "Parte do que você tem investido agora mesmo:",
  ". La aportación al mes es opcional — a 0, ves solo lo que haría el mercado con lo tuyo.": ". O aporte mensal é opcional — em 0, você vê só o que o mercado faria com o seu.",
  "Aportación al mes (€, opcional)": "Aporte por mês (€, opcional)",
  "Rentabilidad anual estimada": "Rentabilidade anual estimada",
  "Con el mercado": "Com o mercado",
  "Solo aportado": "Só o aportado",
  "¿Eliminar esta posición de la cartera?": "Excluir esta posição da carteira?",
  "Actualizando…": "Atualizando…",
  "y tendrías": "e você teria",
  "¿Qué es esto?": "O que é isto?",
  "Entendido": "Entendi",
  // ---------- Cartera · aportaciones ----------
  "Aportación":
    "Aporte",
  "Dinero nuevo que metes en algo que ya tienes — la compra de cada mes. Apuntas cuánto metes y a qué precio estaba ese día: la app calcula las participaciones (dinero ÷ precio), las suma a tu posición y te lleva la cuenta EXACTA de lo que has puesto en cada sitio. Lo ganado o perdido siempre se compara contra ese total real.":
    "Dinheiro novo que você coloca em algo que já tem — a compra de cada mês. Você anota quanto colocou e o preço daquele dia: o app calcula as cotas (dinheiro ÷ preço), soma à sua posição e mantém a conta EXATA do que você colocou em cada lugar. O ganho ou a perda sempre se compara com esse total real.",
  "Aportaciones":
    "Aportes",
  "+ Apuntar aportación":
    "+ Anotar aporte",
  "Posición inicial":
    "Posição inicial",
  "Sin aportaciones apuntadas todavía. Cada vez que metas dinero, apúntalo aquí y el total invertido será exacto.":
    "Nenhum aporte anotado ainda. Cada vez que colocar dinheiro, anote aqui e o total investido será exato.",
  "Cuánto metes (€)":
    "Quanto você coloca (€)",
  "Precio por unidad ese día (€)":
    "Preço por cota naquele dia (€)",
  "Apuntar":
    "Anotar",
  "¿Quitar esta aportación? Se restan sus participaciones y su dinero de la posición.":
    "Tirar este aporte? Suas cotas e seu dinheiro serão subtraídos da posição.",
  "Quitar":
    "Tirar",
  "Abrir menú": "Abrir menu",
  "Mi cuenta": "Minha conta",

  // ---------- Comunes ----------
  "Añadir": "Adicionar",
  "+ Añadir": "+ Adicionar",
  "Guardar": "Salvar",
  "Cancelar": "Cancelar",
  "Cerrar": "Fechar",
  "Editar": "Editar",
  "Eliminar": "Excluir",
  "Nombre": "Nome",
  "Fecha": "Data",
  "Importe": "Valor",
  "Importe total": "Valor total",
  "Tipo": "Tipo",
  "Estado": "Status",
  "Cuenta": "Conta",
  "Categoría": "Categoria",
  "Frecuencia": "Frequência",
  "Nota (opcional)": "Observação (opcional)",
  "Icono (opcional)": "Ícone (opcional)",
  "Subcategoría (opcional)": "Subcategoria (opcional)",
  "Total": "Total",
  "Todo": "Tudo",
  "Mes": "Mês",
  "Año": "Ano",
  "Mes anterior": "Mês anterior",
  "Mes siguiente": "Mês seguinte",
  "Ver todas": "Ver todas",
  "Ver todos": "Ver todos",
  "Historial": "Histórico",
  "Activo": "Ativo",
  "Pagado": "Pago",
  "pendiente": "pendente",
  "Debe": "Deve",
  "Importando…": "Importando…",

  // ---------- Días de la semana (calendario) ----------
  "Lun": "Seg",
  "Mar": "Ter",
  "Mié": "Qua",
  "Jue": "Qui",
  "Vie": "Sex",
  "Sáb": "Sáb",
  "Dom": "Dom",

  // ---------- Dashboard ----------
  "Saldo total": "Saldo total",
  "Gastos por categoría · este mes": "Gastos por categoria · este mês",
  "Toca una porción para ver de qué gastos sale.": "Toque em uma fatia para ver de quais despesas ela vem.",
  "Total del mes": "Total do mês",
  "Si alguno no cuadra (repetido o con la fecha de otro mes), corrígelo tocando su día en Movimientos.":
    "Se algum não bater (repetido ou com a data de outro mês), corrija tocando no dia dele em Movimentações.",
  "Límites del mes": "Limites do mês",
  "Movimientos recientes": "Movimentações recentes",
  "Préstamos activos": "Empréstimos ativos",
  "Suscripciones activas": "Assinaturas ativas",
  "Top gastos por lugar · este mes": "Top gastos por lugar · este mês",
  "Es tu primera vez aquí": "É a sua primeira vez aqui",
  "Puedo rellenar tus cuentas, categorías, suscripciones fijas y préstamos con los datos que ya me pasaste, para que no tengas que escribirlo todo a mano.":
    "Posso preencher suas contas, categorias, assinaturas fixas e empréstimos com os dados que você já me passou, para não ter que digitar tudo à mão.",
  "Importar mis datos iniciales": "Importar meus dados iniciais",
  "Este mes": "Este mês",
  "Ingresos": "Receitas",
  "Gastos": "Despesas",
  "Ingreso": "Receita",
  "Gasto": "Despesa",
  "Estimado": "Estimado",

  // ---------- Movimientos ----------
  "Añadir movimiento": "Adicionar movimentação",
  "+ Añadir movimiento": "+ Adicionar movimentação",
  "Ingresos del mes": "Receitas do mês",
  "Gastos del mes": "Despesas do mês",
  "Diferencia": "Diferença",
  "Ingresos vs. Gastos este mes": "Receitas vs. despesas este mês",
  "Balance del día": "Saldo do dia",
  "Transferencia entre cuentas": "Transferência entre contas",
  "Transferencia": "Transferência",
  "Cuenta destino": "Conta de destino",
  "Mercadona, Glovo, nómina…": "Mercado, iFood, salário…",
  "Five Guys, Zara…": "Five Guys, Zara…",
  "Editar movimiento": "Editar movimentação",
  "Nuevo movimiento": "Nova movimentação",
  "¿Eliminar este movimiento? El saldo de su cuenta se ajustará al quitarlo.":
    "Excluir esta movimentação? O saldo da conta será ajustado ao removê-la.",

  // ---------- Cuentas ----------
  "+ Añadir cuenta": "+ Adicionar conta",
  "Nueva cuenta": "Nova conta",
  "Editar cuenta": "Editar conta",
  "Saldo inicial": "Saldo inicial",
  "Fecha de ese saldo": "Data desse saldo",
  "Cuenta activa": "Conta ativa",
  "Corriente": "Conta-corrente",
  "Ahorro": "Poupança",
  "Efectivo": "Dinheiro vivo",
  "Otra": "Outra",
  "Sin límite mensual": "Sem limite mensal",
  "Cuadrar": "Acertar saldo",
  "Cuadrar la cuenta": "Acertar a conta",
  "¿Cuánto tienes de verdad?": "Quanto você tem de verdade?",
  "Según la app tienes": "Segundo o app você tem",
  ". Escribe lo que tienes DE VERDAD (lo que dice el banco o el efectivo contado) y el saldo se ajusta solo. Los movimientos no se tocan.":
    ". Digite o que você tem DE VERDADE (o que diz o banco ou o dinheiro contado) e o saldo se ajusta sozinho. As movimentações não são alteradas.",
  "Ya cuadra: no hay nada que ajustar.": "Já bate: não há nada para ajustar.",
  "Copiar ID de Firestore": "Copiar ID do Firestore",
  "¿Eliminar esta cuenta? No se borrarán sus movimientos.":
    "Excluir esta conta? As movimentações dela não serão apagadas.",

  // ---------- Gastos fijos ----------
  "+ Añadir gasto fijo": "+ Adicionar gasto fixo",
  "Nuevo gasto fijo": "Novo gasto fixo",
  "Editar gasto fijo": "Editar gasto fixo",
  "Gasto fijo activo": "Gasto fixo ativo",
  "Mensual": "Mensal",
  "Anual": "Anual",
  "Bimensual": "Bimestral",
  "Trimestral": "Trimestral",
  "Semestral": "Semestral",
  "Precio habitual": "Valor habitual",
  "Gastos fijos por cuenta": "Gastos fixos por conta",
  "Glovo Prime, Préstamo Bankinter, Luz…": "iFood, financiamento, luz…",
  "¿Eliminar este gasto fijo? No se borrarán los gastos ya registrados.":
    "Excluir este gasto fixo? As despesas já registradas não serão apagadas.",

  // ---------- Préstamos ----------
  "+ Nuevo préstamo": "+ Novo empréstimo",
  "Nuevo préstamo": "Novo empréstimo",
  "Editar préstamo": "Editar empréstimo",
  "Pendiente de cobrar": "Pendente de receber",
  "Intereses a tu favor": "Juros a seu favor",
  "Persona": "Pessoa",
  "Nombre de la persona": "Nome da pessoa",
  "Capital prestado": "Valor emprestado",
  "Interés (%)": "Juros (%)",
  "Interés fijo (€, opcional)": "Juros fixos (€, opcional)",
  "Vacío = se calcula con el %": "Vazio = calculado pelo %",
  "Ya pagado hasta ahora (€)": "Já pago até agora (€)",
  "¿Para cuándo debería pagarlo? (opcional)": "Para quando deveria pagar? (opcional)",
  "Notas del préstamo (opcional)": "Observações do empréstimo (opcional)",
  "Los detalles para tenerlo controlado: qué acordasteis, cuándo prometió pagar, si dejó algo a cuenta…":
    "Os detalhes para manter o controle: o que combinaram, quando prometeu pagar, se deixou algo adiantado…",
  "¿De qué cuenta sale el dinero?": "De qual conta sai o dinheiro?",
  "No descontarlo de ninguna cuenta": "Não descontar de nenhuma conta",
  "¿Qué día se lo diste?": "Em que dia você emprestou?",
  "El capital sale de esa cuenta y cuenta como gasto del día: ese dinero ya no lo tienes. Cuando te lo devuelvan, entrará como ingreso.":
    "O valor sai dessa conta e conta como despesa do dia: esse dinheiro já não está com você. Quando devolverem, entrará como receita.",
  "± Ha pagado una parte": "± Pagou uma parte",
  "💰 Ha pagado todo lo pendiente (liquidar)": "💰 Pagou tudo o que faltava (quitar)",
  "¿Cuánto ha pagado?": "Quanto pagou?",
  "¿A qué cuenta entra?": "Em qual conta entra?",
  "Registrar el abono": "Registrar o pagamento",
  ". Escribe cuánto ha pagado.": ". Digite quanto pagou.",
  "Liquidar y cerrar préstamo": "Quitar e encerrar empréstimo",
  "Le quedan por pagar": "Ainda faltam pagar",
  "(capital + interés). Esto registra un ingreso por el total y cierra el préstamo como Pagado.":
    "(valor + juros). Isto registra uma receita pelo total e encerra o empréstimo como Pago.",
  "Esto registra un ingreso por el total y cierra el préstamo como Pagado.":
    "Isto registra uma receita pelo total e encerra o empréstimo como Pago.",
  "Préstamo cerrado.": "Empréstimo encerrado.",
  "— saldado": "— quitado",
  "¿Eliminar este préstamo? Los pagos ya registrados se quedan en Movimientos (ese dinero entró de verdad). Solo si nunca cobró nada, se borra también el gasto de cuando salió el dinero.":
    "Excluir este empréstimo? Os pagamentos já registrados ficam em Movimentações (esse dinheiro entrou de verdade). Só se nunca recebeu nada, a despesa de quando o dinheiro saiu também é apagada.",
  "Abono": "Pagamento",
  "Cuota del plan": "Parcela do plano",
  "Liquidación": "Quitação",
  "Interés": "Juros",
  "Pago": "Pagamento",

  "Cobrado este mes ▾": "Recebido este mês ▾",
  "Intereses este mes ▾": "Juros este mês ▾",
  "Toca para ver el desglose por persona": "Toque para ver por pessoa",
  "Este mes todavía no has cobrado ningún pago.": "Este mês você ainda não recebeu nenhum pagamento.",
  "Listo": "Pronto",
  "(tu ganancia). Cada cobro se reparte según su préstamo: en uno de 100 € al 20 %, de cada 30 € cobrados, 5 € son interés.":
    "(seu ganho). Cada pagamento se divide conforme o empréstimo: em um de 100 € a 20 %, de cada 30 € recebidos, 5 € são juros.",

  // ---------- Metas ----------
  "+ Nueva meta": "+ Nova meta",
  "Nueva meta": "Nova meta",
  "Editar meta": "Editar meta",
  "Crear la meta": "Criar a meta",
  "¿Para qué ahorras?": "Para que você está poupando?",
  "¿Cuánto necesitas?": "Quanto você precisa?",
  "¿Para cuándo? (opcional)": "Para quando? (opcional)",
  "Viaje a Bolivia, arreglar el baño…": "Viagem, arrumar o banheiro…",
  "Huchas para lo que quieres conseguir: un viaje, una reparación, un capricho. El dinero sigue en tus cuentas — aquí solo lo apartas.":
    "Cofrinhos para o que você quer conquistar: uma viagem, um conserto, um mimo. O dinheiro continua nas suas contas — aqui você só o separa.",
  "Todavía no tienes ninguna meta. Un viaje, una reparación de casa, un capricho grande… ponle nombre y una cantidad, y ve apartando.":
    "Você ainda não tem nenhuma meta. Uma viagem, um conserto em casa, um mimo grande… dê um nome e um valor, e vá separando.",
  "¿Eliminar esta meta? El dinero sigue en tus cuentas — solo se borra la hucha.":
    "Excluir esta meta? O dinheiro continua nas suas contas — só o cofrinho é apagado.",
  "¿Borrar esta aportación?": "Excluir este aporte?",

  // ---------- Gráficos ----------
  "Total de gastos": "Total de despesas",
  "Total de ingresos": "Total de receitas",
  "Gastos por categoría": "Despesas por categoria",
  "Ingresos por categoría": "Receitas por categoria",
  "Gastos por lugar": "Despesas por lugar",
  "Buscar: Five Guys, KFC, Taco Bell…": "Buscar: Five Guys, KFC, Taco Bell…",

  // ---------- Categorías ----------
  "+ Añadir categoría": "+ Adicionar categoria",
  "Nueva categoría": "Nova categoria",
  "Editar categoría": "Editar categoria",
  "Límite mensual (opcional)": "Limite mensal (opcional)",
  "Fijo": "Fixo",
  "Variable": "Variável",
  "Ocio": "Lazer",
  "PrestamoDado": "Empréstimo dado",
  "Comida a domicilio": "Comida por aplicativo",
  "¿Eliminar esta categoría? Sus movimientos no se borran: quedarán como 'sin categoría'.":
    "Excluir esta categoria? As movimentações não são apagadas: ficarão como 'sem categoria'.",

  // ---------- Mi cuenta ----------
  "Sesión iniciada con Firebase Auth": "Sessão iniciada com o Firebase Auth",
  "Cambiar contraseña": "Alterar senha",
  "Idioma": "Idioma",
  "El idioma de toda la app en este dispositivo.": "O idioma de todo o app neste dispositivo.",
  "Temas": "Temas",
  "Cambia el aspecto de toda la app. «Original» la deja como estaba.":
    "Mude o visual de todo o app. «Escuro (original)» deixa como estava.",
  "Configuración": "Configurações",
  "Ver la guía de la app otra vez": "Ver o guia do app de novo",
  "Exportar mis datos": "Exportar meus dados",
  "Importar desde una copia": "Importar de uma cópia",
  "Datos importados correctamente.": "Dados importados com sucesso.",
  "No se pudo importar el archivo. ¿Es una copia válida exportada desde aquí?":
    "Não foi possível importar o arquivo. É uma cópia válida exportada daqui?",
  "Esto añadirá todo lo que haya en el archivo a tus datos actuales (no borra nada existente). ¿Continuar?":
    "Isto adicionará tudo o que houver no arquivo aos seus dados atuais (não apaga nada existente). Continuar?",
  "No se pudo enviar el email. Inténtalo de nuevo.": "Não foi possível enviar o e-mail. Tente de novo.",
  "No se pudo guardar. Inténtalo de nuevo.": "Não foi possível salvar. Tente de novo.",

  // ---------- Temas (nombres y grupos del selector) ----------
  "Oscuro (original)": "Escuro (original)",
  "Claro": "Claro",
  "Por defecto": "Padrão",
  "Países": "Países",
  "España": "Espanha",
  "Bolivia": "Bolívia",
  "Brasil": "Brasil",
  "Italia": "Itália",
  "Francia": "França",
  "Rosa pastel": "Rosa pastel",
  "Español": "Español",
  "Português (Brasil)": "Português (Brasil)",

  // ---------- Guía de bienvenida ----------
  "¡Bienvenido! 👋": "Bem-vindo! 👋",
  "Esta es tu app: tu día a día y tu dinero, en un solo sitio y a tu manera. Te enseño lo básico en cuatro pasos — medio minuto.":
    "Este é o seu app: seu dia a dia e seu dinheiro, em um só lugar e do seu jeito. Vou te mostrar o básico em quatro passos — meio minuto.",
  "El menú": "O menu",
  "Aquí está TODO, en dos bloques: «Tu día» (rutina, calendario, comidas…) y «Tu dinero» (cuentas, movimientos, préstamos…). Ninguna pantalla escondida.":
    "Aqui está TUDO, em dois blocos: «Seu dia» (rotina, calendário, refeições…) e «Seu dinheiro» (contas, movimentações, empréstimos…). Nenhuma tela escondida.",
  "Tu cuenta y tus colores": "Sua conta e suas cores",
  "Desde aquí eliges el tema de la app — claro u oscuro, o uno con carácter (países y más) — y gestionas tu perfil.":
    "Aqui você escolhe o tema do app — claro ou escuro, ou um com personalidade (países e mais) — e gerencia o seu perfil.",
  "Tuya de verdad": "Seu de verdade",
  "Toca todo sin miedo: cualquier cosa que borre algo te pregunta antes y te dice qué va a pasar. Y si algo no encaja con tu vida, se cambia — para eso es tuya. ¡A por ello!":
    "Toque em tudo sem medo: qualquer coisa que apague algo pergunta antes e diz o que vai acontecer. E se algo não combinar com a sua vida, a gente muda — para isso o app é seu. Bora!",
  "Saltar": "Pular",
  "Siguiente →": "Próximo →",
  "¡Listo!": "Pronto!",

  // ---------- Otros dinámicos ----------
  "Balance": "Saldo",
  "sin fecha": "sem data",
  "Sin categoría": "Sem categoria",
  "sin categoría": "sem categoria",

  // ---------- Vida · Hoy ----------
  "Ayer quedó sin cerrar.": "Ontem ficou sem fechar.",
  "Cerrar ayer": "Fechar ontem",
  "Los 4 innegociables": "Os 4 inegociáveis",
  "Los cuatro = día cumplido. No hay medias tintas.": "Os quatro = dia cumprido. Sem meias-medidas.",
  "Sin comida fuera sin planificar": "Sem comer fora sem planejar",
  "El entreno que toque": "O treino do dia",
  "En la cama antes de las 23:15": "Na cama antes das 23h15",
  "4 piezas de fruta": "4 frutas",
  "Dientes 3 veces": "Dentes 3 vezes",
  "Cena dejada preparada": "Jantar deixado pronto",
  "Algo de verdura": "Um pouco de verdura",
  "Bonus": "Bônus",
  "Cerrar el día": "Fechar o dia",
  "Guardar cambios": "Salvar alterações",
  "Corregir": "Corrigir",
  "✎ Corregir otro día": "✎ Corrigir outro dia",
  "✎ Ajustar este horario": "✎ Ajustar este horário",
  "✎ Editar ejercicios": "✎ Editar exercícios",
  "Apuntes del día (opcional)": "Anotações do dia (opcional)",
  "Peso (kg) — 1 vez por semana basta": "Peso (kg) — 1 vez por semana basta",
  "Racha:": "Sequência:",
  "Racha": "Sequência",
  "días · Día": "dias · Dia",
  "Día · hoy": "Dia · hoje",
  "Día": "Dia",
  "Semana": "Semana",
  "Qué toca hoy": "O que toca hoje",
  "Hoy toca:": "Hoje toca:",
  "Tocar para registrarlo": "Toque para registrar",
  "El día, hora a hora": "O dia, hora a hora",
  "Marcar como hecho": "Marcar como feito",
  "Desmarcar todo": "Desmarcar tudo",
  "☑ Para hacer hoy": "☑ Para fazer hoje",
  "＋ Cita o imprevisto": "＋ Compromisso ou imprevisto",
  "⏳ Algo quedó a medias": "⏳ Algo ficou pela metade",
  "🍎 Fruta 1": "🍎 Fruta 1",
  "🍊 Fruta 2": "🍊 Fruta 2",
  "🍌 Fruta 3": "🍌 Fruta 3",
  "🍇 Fruta 4": "🍇 Fruta 4",
  "🪒 Rasurarse": "🪒 Fazer a barba",
  "La del bonus: con esta van las 4 piezas": "A do bônus: com esta são as 4 frutas",
  "Comida:": "Almoço:",
  "Cena:": "Jantar:",
  "Comer": "Almoçar",
  "Dormir": "Dormir",
  "Levantarte con calma": "Levantar com calma",
  "Descanso de verdad": "Descanso de verdade",
  "Es el día que sostiene la semana": "É o dia que sustenta a semana",
  "Preparar la semana": "Preparar a semana",
  "Batch cooking (hasta las 13:00)": "Batch cooking (até as 13h)",
  "Las comidas de la semana, del menú": "As refeições da semana, do cardápio",
  "Platos y cocina recogida": "Louça e cozinha arrumadas",
  "Mochila del gimnasio hecha · menú a la vista": "Mochila da academia pronta · cardápio à vista",
  "Todo listo. Falta que tú digas YA.": "Tudo pronto. Só falta você dizer JÁ.",
  "START · empezar hoy 💪": "START · começar hoje 💪",
  "La racha y los puntos del día": "A sequência e os pontos do dia",
  "El bote de recompensas": "O pote de recompensas",
  "La fase de estudio (30 → 60 min)": "A fase de estudo (30 → 60 min)",
  "Las semanas 6/7 y los logros": "As semanas 6/7 e as conquistas",
  "Día 1": "Dia 1",
  "Un momento, están llegando de Firebase. Tu racha y tus días están guardados. Si esto no avanza, revisa la conexión.":
    "Um momento, estão chegando do Firebase. Sua sequência e seus dias estão salvos. Se isto não avançar, verifique a conexão.",
  "Estudio": "Estudo",
  "· 30 min (fase 1)": "· 30 min (fase 1)",
  "Estudio: fase 1 · 30 min/día. Sube sola con 2 semanas seguidas a 6 de 7.":
    "Estudo: fase 1 · 30 min/dia. Sobe sozinha com 2 semanas seguidas em 6 de 7.",

  // ---------- Vida · Entreno ----------
  "Guardar el entreno": "Salvar o treino",
  "¿De qué día es?": "De que dia é?",
  "Si lo apuntas tarde (o pasada la medianoche), pon el día en que entrenaste":
    "Se anotar tarde (ou passada a meia-noite), coloque o dia em que treinou",
  "Duración (min)": "Duração (min)",
  "reps": "reps",
  "Peso": "Peso",
  "Los kg de la serie 1": "Os kg da série 1",
  "Los kg de la serie 2": "Os kg da série 2",
  "Los kg de la serie 3": "Os kg da série 3",
  "Últimos entrenos": "Últimos treinos",
  "Pierna": "Perna",
  "Tirón": "Puxada",
  "Empuje": "Empurrada",
  "Core + caminata": "Core + caminhada",
  "Piscina": "Piscina",
  "Caminata": "Caminhada",
  "En casa": "Em casa",
  "Cómo se hace": "Como se faz",
  "Plan de serie ·": "Plano padrão ·",
  "Press banca": "Supino reto",
  "Press de hombro": "Desenvolvimento de ombro",
  "Press de hombro (máquina o mancuernas)": "Desenvolvimento (máquina ou halteres)",
  "Jalón al pecho": "Puxada alta",
  "Jalón agarre cerrado (puños mirándose)": "Puxada pegada fechada (punhos de frente)",
  "Remo en máquina": "Remada na máquina",
  "Remo en máquina (la barra hacia ti)": "Remada na máquina (barra até você)",
  "Remo a una mano con el chaleco": "Remada unilateral com o colete",
  "Curl en máquina": "Rosca na máquina",
  "Curl martillo con mancuernas": "Rosca martelo com halteres",
  "Curl femoral (tumbado o sentado)": "Mesa flexora (deitado ou sentado)",
  "Extensiones de cuádriceps": "Cadeira extensora",
  "Hacka (o prensa)": "Hack (ou leg press)",
  "Hacka / prensa": "Hack / leg press",
  "Peso muerto rumano con mancuernas": "Levantamento terra romeno com halteres",
  "Gemelos de pie": "Panturrilha em pé",
  "Abductor o aductor (alterna semanas)": "Abdutor ou adutor (alterne as semanas)",
  "Lumbar (espalda baja)": "Lombar",
  "Elevaciones laterales (máquina o mancuernas)": "Elevações laterais (máquina ou halteres)",
  "Cruces en polea (alta o baja, alterna)": "Crossover na polia (alta ou baixa, alterne)",
  "Posterior en polea cruzada": "Posterior na polia cruzada",
  "Tríceps en polea (cuerda o barra, alterna)": "Tríceps na polia (corda ou barra, alterne)",
  "Crunch en máquina": "Abdominal na máquina",
  "Elevaciones de piernas (tumbado o colgado)": "Elevação de pernas (deitado ou na barra)",
  "Plancha": "Prancha",
  "Flexiones": "Flexões",
  "Flexiones diamante": "Flexões diamante",
  "Flexiones seguidas": "Flexões seguidas",
  "Sentadillas con el chaleco": "Agachamentos com o colete",
  "Zancadas alternas": "Afundos alternados",
  "Caminata en cuesta (cinta 10–12 % · 5 km/h)": "Caminhada em subida (esteira 10–12 % · 5 km/h)",
  "La primera vez apunta tu peso; desde entonces la app te lo trae puesto y avisa cuando toque subir":
    "Na primeira vez anote seu peso; depois o app já traz preenchido e avisa quando for hora de subir",
  "Si está imposible: ejercicios 1 y 2 se esperan, del 3 en adelante cualquier máquina del mismo grupo vale, y si no hay manera → piscina. Cuenta igual.":
    "Se estiver impossível: exercícios 1 e 2 se esperam, do 3 em diante qualquer máquina do mesmo grupo vale, e se não der → piscina. Conta igual.",
  "El gimnasio estaba lleno": "A academia estava cheia",
  "¿Te ha molestado la ingle hoy? 0 = nada · 10 = mucho": "A virilha incomodou hoje? 0 = nada · 10 = muito",
  "El aductor con suavidad mientras la ingle esté delicada; si molesta, fuera y punto":
    "O adutor com suavidade enquanto a virilha estiver sensível; se incomodar, tira e pronto",
  "Lo único nuevo: glúteo y femoral de verdad. Si la ingle avisa, menos peso y menos recorrido":
    "A única novidade: glúteo e posterior de verdade. Se a virilha avisar, menos peso e menos amplitude",
  "Si vas justo de tiempo, este es el que se cae": "Se o tempo estiver curto, este é o que sai",
  "~10 min · vale mientras trabajas": "~10 min · vale enquanto trabalha",
  "Crear una rutina propia": "Criar uma rotina própria",
  "＋ Rutina": "＋ Rotina",
  "Cambiar": "Trocar",

  // ---------- Vida · Progreso ----------
  "El duelo de la semana": "O duelo da semana",
  "Puntos de esta semana, de lunes a hoy. Gana quien se cuida — no quien se machaca: los puntos salen de dormir, moverse, comer bien y cumplir lo tuyo. Un día redondo = los 4 innegociables cumplidos. Perder este duelo también es ganar.":
    "Pontos desta semana, de segunda até hoje. Ganha quem se cuida — não quem se destrói: os pontos vêm de dormir, se mexer, comer bem e cumprir o seu. Um dia redondo = os 4 inegociáveis cumpridos. Perder este duelo também é ganhar.",
  "Empate": "Empate",
  "Puntos": "Pontos",
  "Días redondos": "Dias redondos",
  "Entrenos": "Treinos",
  "Semanas 6/7": "Semanas 6/7",
  "El bote": "O pote",
  "bote total": "pote total",
  "disponible para gastar": "disponível para gastar",
  "· Cada día cumplido suma lo que NO te gastas en comida fuera.": "· Cada dia cumprido soma o que você NÃO gasta comendo fora.",
  "Nueva recompensa": "Nova recompensa",
  "Añade recompensas: pavos, piezas del PC, el voucher del AZ-900… Nunca comida.":
    "Adicione recompensas: créditos, peças do PC, o voucher do AZ-900… Nunca comida.",
  "Cuesta (€)": "Custa (€)",
  "Retos de fuerza": "Desafios de força",
  "Apunta el peso una vez por semana en Hoy → Apuntes del día.": "Anote o peso uma vez por semana em Hoje → Anotações do dia.",
  "Apunta tu peso en Hoy y salen sus niveles (van en proporción a tu peso).":
    "Anote seu peso em Hoje e os níveis aparecem (são proporcionais ao seu peso).",
  "Aún sin marca: registra un entreno con este ejercicio. Primer reto:": "Ainda sem marca: registre um treino com este exercício. Primeiro desafio:",
  "Valoraciones estimadas con estándares de fuerza internacionales, entre gente que entrena — comparado con la población general estás bastante más arriba. Los retos con kilos van en proporción a tu peso corporal: si tú bajas, ellos bajan contigo.":
    "Avaliações estimadas com padrões internacionais de força, entre gente que treina — comparado com a população geral você está bem acima. Os desafios com quilos são proporcionais ao seu peso corporal: se você desce, eles descem com você.",
  "🏅 0 medallas": "🏅 0 medalhas",
  "Fuerza — mejor serie por sesión": "Força — melhor série por sessão",
  "Peso — hacia 84 kg": "Peso — rumo aos 84 kg",
  "objetivo 84": "meta 84",
  "mejor: 0": "melhor: 0",
  "Logros · 0/18": "Conquistas · 0/18",
  "Primer día cumplido": "Primeiro dia cumprido",
  "Primera semana 6 de 7": "Primeira semana 6 de 7",
  "Primer mes cumplido": "Primeiro mês cumprido",
  "Racha de 7 días": "Sequência de 7 dias",
  "Racha de 14 días": "Sequência de 14 dias",
  "Racha de 30 días": "Sequência de 30 dias",
  "10 entrenos": "10 treinos",
  "25 entrenos": "25 treinos",
  "50 entrenos": "50 treinos",
  "Primera piscina": "Primeira piscina",
  "Primera subida de peso": "Primeira subida de carga",
  "Subida en 5 ejercicios": "Subida em 5 exercícios",
  "Primera recompensa canjeada": "Primeira recompensa resgatada",
  "Fase 2 de estudio": "Fase 2 de estudo",
  "Fase 4: una hora al día": "Fase 4: uma hora por dia",
  "Teórico de moto aprobado": "Teórico da moto aprovado",
  "AZ-900 aprobado": "AZ-900 aprovado",
  "Carnet A2": "Habilitação A2",
  "Tasa DGT pagada": "Taxa do Detran paga",
  "Psicotécnico": "Exame psicotécnico",
  "Práctico de circuito": "Prática de circuito",
  "Práctico de circulación": "Prática de rua",
  "Consulta de fisio por la ingle": "Consulta de fisio pela virilha",
  "Todavía no hay ninguno. El primero es hoy.": "Ainda não há nenhum. O primeiro é hoje.",
  "Ver mi progreso y el bote →": "Ver meu progresso e o pote →",

  // ---------- Vida · Menú y compras ----------
  "El menú de la semana": "O cardápio da semana",
  "¿Qué coméis en casa esta semana?": "O que vocês comem em casa esta semana?",
  "Hacer el menú de esta semana": "Fazer o cardápio desta semana",
  "El menú es": "O cardápio é",
  "de casa": "da casa",
  ": el mismo para los dos, se mire desde la app que se mire — nadie cocina dos veces. Marcad juntos lo que os apetezca: con lo marcado salen ahora":
    ": o mesmo para os dois, seja qual for o app de onde se olhe — ninguém cozinha duas vezes. Marquem juntos o que der vontade: com o que está marcado saem agora",
  "8 desayunos, 14 comidas y 15 cenas": "8 cafés da manhã, 14 almoços e 15 jantares",
  "Todavía no hay menú para esta semana. Marcad los ingredientes y dadle al botón: saldrá priorizando lo rápido (AirFryer, horno o pocos pasos), y luego cada día se puede retocar con el lápiz.":
    "Ainda não há cardápio para esta semana. Marquem os ingredientes e apertem o botão: sairá priorizando o rápido (AirFryer, forno ou poucos passos), e depois cada dia pode ser retocado com o lápis.",
  "Haz tu menú de la semana con TUS ingredientes →": "Faça seu cardápio da semana com os SEUS ingredientes →",
  "Platos vuestros": "Pratos de vocês",
  "＋ Plato vuestro": "＋ Prato de vocês",
  "Comida fuera esta semana:": "Comida de fora esta semana:",
  "Proteína": "Proteína",
  "Hidratos": "Carboidratos",
  "Verdura": "Verduras",
  "Legumbres": "Leguminosas",
  "Lácteos y básicos": "Laticínios e básicos",
  "De postre": "De sobremesa",
  "Pollo": "Frango",
  "Ternera picada": "Carne moída",
  "Lomo de cerdo": "Lombo de porco",
  "Salchichas": "Salsichas",
  "Bacon": "Bacon",
  "Chorizo": "Linguiça",
  "Jamón / fiambre de pavo": "Presunto / peito de peru",
  "Atún en lata": "Atum em lata",
  "Merluza": "Merluza",
  "Salmón": "Salmão",
  "Huevos": "Ovos",
  "Arroz": "Arroz",
  "Pasta": "Macarrão",
  "Patatas": "Batatas",
  "Pan": "Pão",
  "Avena": "Aveia",
  "Cuscús": "Cuscuz",
  "Harina (crepes y pancakes)": "Farinha (crepes e panquecas)",
  "Base de pizza": "Massa de pizza",
  "Tortillas de trigo (wraps)": "Tortilhas de trigo (wraps)",
  "Tomate frito / triturado": "Molho de tomate",
  "Lechuga (ensalada)": "Alface (salada)",
  "Zanahoria (triturada)": "Cenoura (ralada)",
  "Cebolla (en la salsa)": "Cebola (no molho)",
  "Brócoli (con queso)": "Brócolis (com queijo)",
  "Calabacín (en crema)": "Abobrinha (em creme)",
  "Espinacas (trituradas)": "Espinafre (triturado)",
  "Lentejas": "Lentilhas",
  "Garbanzos": "Grão-de-bico",
  "Alubias": "Feijão",
  "Leche": "Leite",
  "Queso": "Queijo",
  "Yogur griego": "Iogurte grego",
  "Mantequilla": "Manteiga",
  "ColaCao / Cacaolat": "Achocolatado",
  "Caldo de pollo": "Caldo de galinha",
  "Fruta (todas)": "Frutas (todas)",
  "Frutos secos": "Castanhas e nozes",
  "Pasta boloñesa (verdura en la salsa)": "Macarrão à bolonhesa (verdura no molho)",
  "Sándwich integral de pollo": "Sanduíche integral de frango",
  "¿Qué falta en casa?": "O que está faltando em casa?",
  "+ Añadir a la lista": "+ Adicionar à lista",
  "Elige categoría, escribe y dale a intro · toca para marcar o reponer · mantén pulsado para borrar":
    "Escolha a categoria, escreva e dê enter · toque para marcar ou repor · segure para apagar",
  "No falta nada ✨": "Não falta nada ✨",
  "Quitar de la lista": "Tirar da lista",
  "Crear una categoría": "Criar uma categoria",
  "Limpieza": "Limpeza",
  "Cosas para la casa": "Coisas para a casa",
  "Muebles": "Móveis",
  "Electrodomésticos": "Eletrodomésticos",

  // ---------- Vida · Oficina ----------
  "La mochila de la oficina": "A mochila do escritório",
  "Repásala la noche de antes (el lunes te lo recuerda el horario) y un vistazo por la mañana. Las marcas se borran solas al día siguiente, listas para la próxima.":
    "Revise na noite anterior (na segunda o horário lembra você) e uma olhada de manhã. As marcas se apagam sozinhas no dia seguinte, prontas para a próxima.",
  "Portátil y cargador": "Notebook e carregador",
  "Auriculares": "Fones de ouvido",
  "Botella de agua": "Garrafa de água",
  "Tupper o comida": "Marmita ou comida",
  "Tarjeta o llaves de la oficina": "Cartão ou chaves do escritório",
  "Cartera y transporte": "Carteira e transporte",
  "Ropa de mañana lista": "Roupa de amanhã pronta",
  "Para el camino": "Para o caminho",
  "¿Algo más que llevar?": "Algo mais para levar?",
  "+ Apuntar regla": "+ Anotar menstruação",
  "Calendario personal": "Calendário pessoal",
  "＋ Añadir": "＋ Adicionar",
};

// Patrones: para los textos que llevan datos dentro (números, nombres,
// fechas). $1, $2… conservan esos datos tal cual.
export const PATRONES_PT = [
  [/^"(.+)" es el (\d+) % de tu cartera\. Mucho peso en una sola cosa: si cae, cae todo contigo\.$/, "\"$1\" é $2 % da sua carteira. Muito peso em uma coisa só: se ela cai, cai tudo com você."],
  [/^Más de la mitad de la cartera es cripto \((\d+) %\)\. Es lo más volátil que hay: que no sea dinero que puedas necesitar\.$/, "Mais da metade da carteira é cripto ($1 %). É o mais volátil que existe: que não seja dinheiro de que você possa precisar."],
  [/^"(.+)" cae un (\d+) %\. Antes de vender por miedo, recuerda por qué la compraste: vender abajo convierte una caída en una pérdida\.$/, "\"$1\" cai $2 %. Antes de vender por medo, lembre por que comprou: vender embaixo transforma uma queda em uma perda."],
  [/^(.+ %\)) desde la compra$/, "$1 desde a compra"],
  [/^(.+) uds · (.+) \(precio de compra\)$/, "$1 cotas · $2 (preço de compra)"],
  [/^(.+) uds · (.+)$/, "$1 cotas · $2"],
  [/^(.+) uds$/, "$1 cotas"],
  [/^Años: (\d+)$/, "Anos: $1"],
  [/^Partiendo de (.+) y aportando (.+) al mes: en (\d+) años habrías aportado$/, "Partindo de $1 e aportando $2 por mês: em $3 anos você teria aportado"],
  [/^si el mercado diera un (\d+) % anual de media\.$/, "se o mercado desse $1 % ao ano em média."],
  [/^Tus (.+) de hoy, sin aportar nada más, serían$/, "Seus $1 de hoje, sem aportar mais nada, seriam"],
  [/^en (\d+) años si el mercado diera un (\d+) % anual de media\.$/, "em $1 anos se o mercado desse $2 % ao ano em média."],
  [/^✓ (\d+) precio actualizado\.$/, "✓ $1 preço atualizado."],
  [/^✓ (\d+) precios actualizados\.$/, "✓ $1 preços atualizados."],
  [/^Invertido (.+)$/, "Investido $1"],
  [/^Has metido (.+) en total$/, "Você colocou $1 no total"],
  [/^Aportación a (.+)$/, "Aporte em $1"],
  [/^Eso son (.+) participaciones\.$/, "Isso dá $1 cotas."],
  [/^Gastos de esta categoría · (.+)$/, "Despesas desta categoria · $1"],
  [/^Hola, (.+)$/, "Olá, $1"],
  [/^Límite mensual (.+)$/, "Limite mensal $1"],
  [/^Saldo inicial (.+) · desde (.+)$/, "Saldo inicial $1 · desde $2"],
  [/^Prestado (.+) · para el (.+)$/, "Emprestado $1 · até $2"],
  [/^Prestado (.+?) \+ interés (.+?) = debe (.+?) · ya ha pagado (.+)$/, "Emprestado $1 + juros $2 = deve $3 · já pagou $4"],
  [/^Prestado (.+?) \+ interés (.+?) = debe (.+)$/, "Emprestado $1 + juros $2 = deve $3"],
  [/^Prestado (.+?) · ya ha pagado (.+)$/, "Emprestado $1 · já pagou $2"],
  [/^Prestado (.+)$/, "Emprestado $1"],
  [/^pendiente de (.+)$/, "pendente de $1"],
  [/^Pagado este mes: (.+?) \((.+?)\) · Pendiente: (.+)$/, "Pago este mês: $1 ($2) · Pendente: $3"],
  [/^Historial: (\d+) pagos? · (.+) cobrados$/, "Histórico: $1 pagamentos · $2 recebidos"],
  [/^Historial · (.+)$/, "Histórico · $1"],
  [/^Cobrado en (.+)$/, "Recebido em $1"],
  [/^Total (.+?) — capital (.+?) \+ intereses$/, "Total $1 — capital $2 + juros"],
  [/^Capital (.+?) · interés (.+)$/, "Capital $1 · juros $2"],
  [/^Capital (.+)$/, "Capital $1"],
  [/^Cuadrar · (.+)$/, "Acertar saldo · $1"],
  [/^Abono · (.+)$/, "Pagamento · $1"],
  [/^Liquidar deuda · (.+)$/, "Quitar dívida · $1"],
  [/^Interés pagado · (.+)$/, "Juros pagos · $1"],
  [/^Transferencia enviada a (.+)$/, "Transferência enviada para $1"],
  [/^Transferencia recibida de (.+)$/, "Transferência recebida de $1"],
  [/^Transferencia · (.+)$/, "Transferência · $1"],
  [/^Con (.+?) queda$/, "Com $1 fica"],
  [/^todo saldado$/, "tudo quitado"],
  [/^: el préstamo se cerrará como Pagado\.$/, ": o empréstimo será encerrado como Pago."],
  [/^Quedarán por pagar$/, "Ainda faltarão pagar"],
  [/^Se ajustará$/, "Será ajustado"],
  [/^para que el saldo diga (.+)\.$/, "para o saldo dizer $1."],
  [/^\(de (.+) en total\)\. Escribe cuánto ha pagado\.$/, "(de $1 no total). Digite quanto pagou."],
  [/^\(de (.+?) en total, ya había pagado (.+?)\)\.$/, "(de $1 no total, já tinha pagado $2)."],
  [/^Te hemos enviado un email a (.+) para cambiar la contraseña\.$/, "Enviamos um e-mail para $1 para alterar a senha."],
  [/^(\d+) de (\d+) pantallas?$/, "$1 de $2 telas"],
  [/^(\d+) de (\d+)$/, "$1 de $2"],
  [/^Debe (.+)$/, "Deve $1"],
  [/^ya ha pagado (.+)$/, "já pagou $1"],
  [/^· ya ha pagado (.+)$/, "· já pagou $1"],
  [/^· para el (.+)$/, "· até $1"],
  // ---------- Vida ----------
  [/^AHORA · (.+)$/, "AGORA · $1"],
  [/^Ahora: (.+)$/, "Agora: $1"],
  [/^Pierna — tus máquinas de siempre$/, "Perna — suas máquinas de sempre"],
  [/^Tirón — espalda y bíceps$/, "Puxada — costas e bíceps"],
  [/^Empuje — pecho, hombro y tríceps$/, "Empurrada — peito, ombro e tríceps"],
  [/^Caminata \+ core — el día ligero$/, "Caminhada + core — o dia leve"],
  [/^Piscina con tu hermano$/, "Piscina com seu irmão"],
  [/^Libre o caminata suave$/, "Livre ou caminhada leve"],
  [/^Descanso · batch cooking$/, "Descanso · batch cooking"],
  [/^· empezaste el (.+)$/, "· você começou em $1"],
  [/^· media de las (\d+) anteriores: (.+)$/, "· média das $1 anteriores: $2"],
  [/^Referencia: (.+)\/día$/, "Referência: $1/dia"],
  [/^(\d+) días? · Día (\d+)$/, "$1 dias · Dia $2"],
  [/^Día (\d+)$/, "Dia $1"],
  [/^mejor: (\d+)$/, "melhor: $1"],
  [/^objetivo (\d+)$/, "meta $1"],
  [/^🏅 (\d+) medallas?$/, "🏅 $1 medalhas"],
  [/^Logros · (\d+)\/(\d+)$/, "Conquistas · $1/$2"],
  [/^Racha de (\d+) días$/, "Sequência de $1 dias"],
  [/^(\d+) entrenos$/, "$1 treinos"],
  [/^Los kg de la serie (\d+)$/, "Os kg da série $1"],
  [/^Faltó: (.+)$/, "Faltou: $1"],
  [/^Día cerrado \(no cumplido\) · (\d+) puntos$/, "Dia fechado (não cumprido) · $1 pontos"],
  [/^✓ Día cumplido · (\d+) puntos$/, "✓ Dia cumprido · $1 pontos"],
  [/^(\d+) puntos$/, "$1 pontos"],
  [/^Aún sin marcar: (.+)\. Un toque ahora y el día no se escapa\.$/, "Ainda sem marcar: $1. Um toque agora e o dia não escapa."],
  [/^Cerrando AYER · (.+)$/, "Fechando ONTEM · $1"],
  [/^Corrigiendo · (.+)$/, "Corrigindo · $1"],
];
