// Français — écrit à la main, qualité d'app native. Mêmes clés que pt.js.
export const DICCIONARIO_FR = {
  "Acceso privado": "Accès privé",
  "Tus finanzas, en un solo lugar.": "Tes finances, au même endroit.",
  "Email": "E-mail",
  "Contraseña": "Mot de passe",
  "Entrar": "Se connecter",
  "tu@email.com": "toi@email.com",
  "tu@correo.com": "toi@email.com",
  "Cerrar sesión": "Se déconnecter",
  "Cargando tus datos…": "Chargement de tes données…",

  "Tu día": "Ta journée",
  "Tu dinero": "Ton argent",
  "Hoy": "Aujourd'hui",
  "Calendario": "Calendrier",
  "Entreno": "Entraînement",
  "Menú": "Menus",
  "Compras": "Courses",
  "Ciclo": "Cycle",
  "Oficina": "Bureau",
  "Progreso": "Progrès",
  "Dashboard": "Tableau de bord",
  "Movimientos": "Opérations",
  "Cuentas": "Comptes",
  "Gastos fijos": "Dépenses fixes",
  "Préstamos": "Prêts",
  "Metas": "Objectifs",
  "Gráficos": "Graphiques",
  "Categorías": "Catégories",
  "Cartera": "Portefeuille",
  "Abrir menú": "Ouvrir le menu",
  "Mi cuenta": "Mon compte",

  "Añadir": "Ajouter",
  "+ Añadir": "+ Ajouter",
  "Guardar": "Enregistrer",
  "Cancelar": "Annuler",
  "Cerrar": "Fermer",
  "Editar": "Modifier",
  "Eliminar": "Supprimer",
  "Nombre": "Nom",
  "Fecha": "Date",
  "Importe": "Montant",
  "Importe total": "Montant total",
  "Tipo": "Type",
  "Estado": "Statut",
  "Cuenta": "Compte",
  "Categoría": "Catégorie",
  "Frecuencia": "Fréquence",
  "Nota (opcional)": "Note (facultatif)",
  "Icono (opcional)": "Icône (facultatif)",
  "Subcategoría (opcional)": "Sous-catégorie (facultatif)",
  "Total": "Total",
  "Todo": "Tout",
  "Mes": "Mois",
  "Año": "Année",
  "Mes anterior": "Mois précédent",
  "Mes siguiente": "Mois suivant",
  "Ver todas": "Tout voir",
  "Ver todos": "Tout voir",
  "Historial": "Historique",
  "Activo": "Actif",
  "Pagado": "Payé",
  "pendiente": "à recevoir",
  "Debe": "Doit",
  "Importando…": "Importation…",

  "Lun": "Lun",
  "Mar": "Mar",
  "Mié": "Mer",
  "Jue": "Jeu",
  "Vie": "Ven",
  "Sáb": "Sam",
  "Dom": "Dim",

  "Saldo total": "Solde total",
  "Gastos por categoría · este mes": "Dépenses par catégorie · ce mois-ci",
  "Toca una porción para ver de qué gastos sale.": "Touchez une part pour voir de quelles dépenses elle provient.",
  "Total del mes": "Total du mois",
  "Si alguno no cuadra (repetido o con la fecha de otro mes), corrígelo tocando su día en Movimientos.":
    "Si l'une ne colle pas (en double ou datée d'un autre mois), corrigez-la en touchant son jour dans Opérations.",
  "Límites del mes": "Limites du mois",
  "Movimientos recientes": "Opérations récentes",
  "Préstamos activos": "Prêts en cours",
  "Suscripciones activas": "Abonnements actifs",
  "Top gastos por lugar · este mes": "Top dépenses par lieu · ce mois-ci",
  "Es tu primera vez aquí": "C'est ta première fois ici",
  "Puedo rellenar tus cuentas, categorías, suscripciones fijas y préstamos con los datos que ya me pasaste, para que no tengas que escribirlo todo a mano.":
    "Je peux remplir tes comptes, catégories, abonnements fixes et prêts avec les données que tu m'as déjà passées, pour que tu n'aies pas tout à taper à la main.",
  "Importar mis datos iniciales": "Importer mes données de départ",
  "Este mes": "Ce mois-ci",
  "Ingresos": "Revenus",
  "Gastos": "Dépenses",
  "Ingreso": "Revenu",
  "Gasto": "Dépense",
  "Estimado": "Estimé",

  "Añadir movimiento": "Ajouter une opération",
  "+ Añadir movimiento": "+ Ajouter une opération",
  "Ingresos del mes": "Revenus du mois",
  "Gastos del mes": "Dépenses du mois",
  "Diferencia": "Différence",
  "Ingresos vs. Gastos este mes": "Revenus vs dépenses ce mois-ci",
  "Balance del día": "Bilan du jour",
  "Transferencia entre cuentas": "Virement entre comptes",
  "Transferencia": "Virement",
  "Cuenta destino": "Compte de destination",
  "Mercadona, Glovo, nómina…": "Courses, livraison, salaire…",
  "Five Guys, Zara…": "Five Guys, Zara…",
  "Editar movimiento": "Modifier l'opération",
  "Nuevo movimiento": "Nouvelle opération",
  "¿Eliminar este movimiento? El saldo de su cuenta se ajustará al quitarlo.":
    "Supprimer cette opération ? Le solde du compte s'ajustera en la retirant.",

  "+ Añadir cuenta": "+ Ajouter un compte",
  "Nueva cuenta": "Nouveau compte",
  "Editar cuenta": "Modifier le compte",
  "Saldo inicial": "Solde initial",
  "Fecha de ese saldo": "Date de ce solde",
  "Cuenta activa": "Compte actif",
  "Corriente": "Compte courant",
  "Ahorro": "Épargne",
  "Efectivo": "Espèces",
  "Otra": "Autre",
  "Sin límite mensual": "Sans limite mensuelle",
  "Cuadrar": "Ajuster le solde",
  "Cuadrar la cuenta": "Ajuster le compte",
  "¿Cuánto tienes de verdad?": "Combien as-tu vraiment ?",
  "Según la app tienes": "D'après l'app tu as",
  ". Escribe lo que tienes DE VERDAD (lo que dice el banco o el efectivo contado) y el saldo se ajusta solo. Los movimientos no se tocan.":
    ". Écris ce que tu as VRAIMENT (ce que dit la banque, ou les espèces comptées) et le solde s'ajuste tout seul. Les opérations ne sont pas touchées.",
  "Ya cuadra: no hay nada que ajustar.": "C'est déjà juste : rien à ajuster.",
  "Copiar ID de Firestore": "Copier l'ID Firestore",
  "¿Eliminar esta cuenta? No se borrarán sus movimientos.":
    "Supprimer ce compte ? Ses opérations ne seront pas effacées.",

  "+ Añadir gasto fijo": "+ Ajouter une dépense fixe",
  "Nuevo gasto fijo": "Nouvelle dépense fixe",
  "Editar gasto fijo": "Modifier la dépense fixe",
  "Gasto fijo activo": "Dépense fixe active",
  "Mensual": "Mensuelle",
  "Anual": "Annuelle",
  "Bimensual": "Tous les deux mois",
  "Trimestral": "Trimestrielle",
  "Semestral": "Semestrielle",
  "Precio habitual": "Prix habituel",
  "Gastos fijos por cuenta": "Dépenses fixes par compte",
  "Glovo Prime, Préstamo Bankinter, Luz…": "Streaming, crédit auto, électricité…",
  "¿Eliminar este gasto fijo? No se borrarán los gastos ya registrados.":
    "Supprimer cette dépense fixe ? Les dépenses déjà enregistrées ne seront pas effacées.",

  "+ Nuevo préstamo": "+ Nouveau prêt",
  "Nuevo préstamo": "Nouveau prêt",
  "Editar préstamo": "Modifier le prêt",
  "Pendiente de cobrar": "Reste à encaisser",
  "Intereses a tu favor": "Intérêts en ta faveur",
  "Persona": "Personne",
  "Nombre de la persona": "Nom de la personne",
  "Capital prestado": "Montant prêté",
  "Interés (%)": "Intérêts (%)",
  "Interés fijo (€, opcional)": "Intérêts fixes (€, facultatif)",
  "Vacío = se calcula con el %": "Vide = calculé avec le %",
  "Ya pagado hasta ahora (€)": "Déjà payé à ce jour (€)",
  "¿Para cuándo debería pagarlo? (opcional)": "Pour quand devrait-il payer ? (facultatif)",
  "Notas del préstamo (opcional)": "Notes du prêt (facultatif)",
  "Los detalles para tenerlo controlado: qué acordasteis, cuándo prometió pagar, si dejó algo a cuenta…":
    "Les détails pour garder le contrôle : ce que vous avez convenu, quand il a promis de payer, s'il a laissé un acompte…",
  "¿De qué cuenta sale el dinero?": "De quel compte sort l'argent ?",
  "No descontarlo de ninguna cuenta": "Ne le déduire d'aucun compte",
  "¿Qué día se lo diste?": "Quel jour l'as-tu prêté ?",
  "El capital sale de esa cuenta y cuenta como gasto del día: ese dinero ya no lo tienes. Cuando te lo devuelvan, entrará como ingreso.":
    "Le montant sort de ce compte et compte comme dépense du jour : cet argent n'est plus à toi. Quand on te le rendra, il rentrera comme revenu.",
  "± Ha pagado una parte": "± Il a payé une partie",
  "💰 Ha pagado todo lo pendiente (liquidar)": "💰 Il a tout payé (solder)",
  "¿Cuánto ha pagado?": "Combien a-t-il payé ?",
  "¿A qué cuenta entra?": "Sur quel compte ça rentre ?",
  "Registrar el abono": "Enregistrer le paiement",
  ". Escribe cuánto ha pagado.": ". Écris combien il a payé.",
  "Liquidar y cerrar préstamo": "Solder et clôturer le prêt",
  "Le quedan por pagar": "Il lui reste à payer",
  "(capital + interés). Esto registra un ingreso por el total y cierra el préstamo como Pagado.":
    "(capital + intérêts). Ceci enregistre un revenu pour le total et clôture le prêt comme Payé.",
  "Esto registra un ingreso por el total y cierra el préstamo como Pagado.":
    "Ceci enregistre un revenu pour le total et clôture le prêt comme Payé.",
  "Préstamo cerrado.": "Prêt clôturé.",
  "— saldado": "— soldé",
  "¿Eliminar este préstamo? Los pagos ya registrados se quedan en Movimientos (ese dinero entró de verdad). Solo si nunca cobró nada, se borra también el gasto de cuando salió el dinero.":
    "Supprimer ce prêt ? Les paiements enregistrés restent dans Opérations (cet argent est vraiment rentré). Seulement s'il n'a jamais rien remboursé, la dépense de sortie de l'argent est effacée aussi.",
  "Abono": "Paiement",
  "Cuota del plan": "Échéance du plan",
  "Liquidación": "Solde final",
  "Interés": "Intérêts",
  "Pago": "Paiement",
  "Cobrado este mes ▾": "Encaissé ce mois-ci ▾",
  "Intereses este mes ▾": "Intérêts ce mois-ci ▾",
  "Toca para ver el desglose por persona": "Touche pour voir le détail par personne",
  "Este mes todavía no has cobrado ningún pago.": "Ce mois-ci tu n'as encore encaissé aucun paiement.",
  "Listo": "OK",
  "(tu ganancia). Cada cobro se reparte según su préstamo: en uno de 100 € al 20 %, de cada 30 € cobrados, 5 € son interés.":
    "(ton gain). Chaque encaissement se répartit selon son prêt : sur 100 € à 20 %, sur chaque 30 € encaissés, 5 € sont des intérêts.",

  "+ Nueva meta": "+ Nouvel objectif",
  "Nueva meta": "Nouvel objectif",
  "Editar meta": "Modifier l'objectif",
  "Crear la meta": "Créer l'objectif",
  "¿Para qué ahorras?": "Pour quoi épargnes-tu ?",
  "¿Cuánto necesitas?": "Combien te faut-il ?",
  "¿Para cuándo? (opcional)": "Pour quand ? (facultatif)",
  "Viaje a Bolivia, arreglar el baño…": "Un voyage, refaire la salle de bain…",
  "Huchas para lo que quieres conseguir: un viaje, una reparación, un capricho. El dinero sigue en tus cuentas — aquí solo lo apartas.":
    "Des tirelires pour ce que tu veux obtenir : un voyage, une réparation, un plaisir. L'argent reste sur tes comptes — ici tu le mets juste de côté.",
  "Todavía no tienes ninguna meta. Un viaje, una reparación de casa, un capricho grande… ponle nombre y una cantidad, y ve apartando.":
    "Tu n'as encore aucun objectif. Un voyage, une réparation, un grand plaisir… donne-lui un nom et un montant, et mets de côté.",
  "¿Eliminar esta meta? El dinero sigue en tus cuentas — solo se borra la hucha.":
    "Supprimer cet objectif ? L'argent reste sur tes comptes — seule la tirelire est effacée.",
  "¿Borrar esta aportación?": "Supprimer ce versement ?",

  "Total de gastos": "Total des dépenses",
  "Total de ingresos": "Total des revenus",
  "Gastos por categoría": "Dépenses par catégorie",
  "Ingresos por categoría": "Revenus par catégorie",
  "Gastos por lugar": "Dépenses par lieu",
  "Buscar: Five Guys, KFC, Taco Bell…": "Rechercher : Five Guys, KFC, Taco Bell…",

  "+ Añadir categoría": "+ Ajouter une catégorie",
  "Nueva categoría": "Nouvelle catégorie",
  "Editar categoría": "Modifier la catégorie",
  "Límite mensual (opcional)": "Limite mensuelle (facultatif)",
  "Fijo": "Fixe",
  "Variable": "Variable",
  "Ocio": "Loisirs",
  "PrestamoDado": "Prêt accordé",
  "Comida a domicilio": "Livraison de repas",
  "¿Eliminar esta categoría? Sus movimientos no se borran: quedarán como 'sin categoría'.":
    "Supprimer cette catégorie ? Ses opérations ne sont pas effacées : elles resteront « sans catégorie ».",

  "Sesión iniciada con Firebase Auth": "Session ouverte avec Firebase Auth",
  "Cambiar contraseña": "Changer le mot de passe",
  "Idioma": "Langue",
  "El idioma de toda la app en este dispositivo.": "La langue de toute l'app sur cet appareil.",
  "Temas": "Thèmes",
  "Cambia el aspecto de toda la app. «Original» la deja como estaba.":
    "Change l'apparence de toute l'app. « Sombre (original) » la remet comme avant.",
  "Configuración": "Réglages",
  "Ver la guía de la app otra vez": "Revoir le guide de l'app",
  "Exportar mis datos": "Exporter mes données",
  "Importar desde una copia": "Importer depuis une sauvegarde",
  "Datos importados correctamente.": "Données importées avec succès.",
  "No se pudo importar el archivo. ¿Es una copia válida exportada desde aquí?":
    "Impossible d'importer le fichier. Est-ce une sauvegarde valide exportée d'ici ?",
  "Esto añadirá todo lo que haya en el archivo a tus datos actuales (no borra nada existente). ¿Continuar?":
    "Ceci ajoutera tout le contenu du fichier à tes données actuelles (rien d'existant n'est effacé). Continuer ?",
  "No se pudo enviar el email. Inténtalo de nuevo.": "L'e-mail n'a pas pu être envoyé. Réessaie.",
  "No se pudo guardar. Inténtalo de nuevo.": "Impossible d'enregistrer. Réessaie.",

  "Oscuro (original)": "Sombre (original)",
  "Claro": "Clair",
  "Por defecto": "Par défaut",
  "Países": "Pays",
  "España": "Espagne",
  "Bolivia": "Bolivie",
  "Brasil": "Brésil",
  "Italia": "Italie",
  "Francia": "France",
  "Rosa pastel": "Rose pastel",
  "Español": "Español",
  "Português (Brasil)": "Português (Brasil)",

  "¡Bienvenido! 👋": "Bienvenue ! 👋",
  "Esta es tu app: tu día a día y tu dinero, en un solo sitio y a tu manera. Te enseño lo básico en cuatro pasos — medio minuto.":
    "Voici ton app : ton quotidien et ton argent, au même endroit et à ta façon. Je te montre l'essentiel en quatre étapes — trente secondes.",
  "El menú": "Le menu",
  "Aquí está TODO, en dos bloques: «Tu día» (rutina, calendario, comidas…) y «Tu dinero» (cuentas, movimientos, préstamos…). Ninguna pantalla escondida.":
    "TOUT est ici, en deux blocs : « Ta journée » (routine, calendrier, repas…) et « Ton argent » (comptes, opérations, prêts…). Aucun écran caché.",
  "Tu cuenta y tus colores": "Ton compte et tes couleurs",
  "Desde aquí eliges el tema de la app — claro u oscuro, o uno con carácter (países y más) — y gestionas tu perfil.":
    "D'ici tu choisis le thème de l'app — clair ou sombre, ou un avec du caractère (pays et plus) — et tu gères ton profil.",
  "Tuya de verdad": "Vraiment à toi",
  "Toca todo sin miedo: cualquier cosa que borre algo te pregunta antes y te dice qué va a pasar. Y si algo no encaja con tu vida, se cambia — para eso es tuya. ¡A por ello!":
    "Touche à tout sans crainte : tout ce qui efface quelque chose te demande d'abord et te dit ce qui va se passer. Et si quelque chose ne colle pas à ta vie, on le change — c'est pour ça qu'elle est à toi. Fonce !",
  "Saltar": "Passer",
  "Siguiente →": "Suivant →",
  "¡Listo!": "Terminé !",

  "Balance": "Bilan",
  "sin fecha": "sans date",
  "Sin categoría": "Sans catégorie",
  "sin categoría": "sans catégorie",

  "Ayer quedó sin cerrar.": "Hier est resté ouvert.",
  "Cerrar ayer": "Clôturer hier",
  "Los 4 innegociables": "Les 4 non négociables",
  "Los cuatro = día cumplido. No hay medias tintas.": "Les quatre = journée réussie. Pas de demi-mesure.",
  "Sin comida fuera sin planificar": "Pas de resto non prévu",
  "El entreno que toque": "L'entraînement du jour",
  "En la cama antes de las 23:15": "Au lit avant 23 h 15",
  "4 piezas de fruta": "4 fruits",
  "Dientes 3 veces": "Dents 3 fois",
  "Cena dejada preparada": "Dîner laissé prêt",
  "Algo de verdura": "Un peu de légumes",
  "Bonus": "Bonus",
  "Cerrar el día": "Clôturer la journée",
  "Guardar cambios": "Enregistrer les changements",
  "Corregir": "Corriger",
  "✎ Corregir otro día": "✎ Corriger un autre jour",
  "✎ Ajustar este horario": "✎ Ajuster cet horaire",
  "✎ Editar ejercicios": "✎ Modifier les exercices",
  "Apuntes del día (opcional)": "Notes du jour (facultatif)",
  "Peso (kg) — 1 vez por semana basta": "Poids (kg) — 1 fois par semaine suffit",
  "Racha:": "Série :",
  "Racha": "Série",
  "días · Día": "jours · Jour",
  "Día · hoy": "Jour · aujourd'hui",
  "Día": "Jour",
  "Semana": "Semaine",
  "Qué toca hoy": "Au programme aujourd'hui",
  "Hoy toca:": "Aujourd'hui :",
  "Tocar para registrarlo": "Touche pour l'enregistrer",
  "El día, hora a hora": "La journée, heure par heure",
  "Marcar como hecho": "Marquer comme fait",
  "Desmarcar todo": "Tout décocher",
  "☑ Para hacer hoy": "☑ À faire aujourd'hui",
  "＋ Cita o imprevisto": "＋ Rendez-vous ou imprévu",
  "⏳ Algo quedó a medias": "⏳ Quelque chose est resté à moitié",
  "🍎 Fruta 1": "🍎 Fruit 1",
  "🍊 Fruta 2": "🍊 Fruit 2",
  "🍌 Fruta 3": "🍌 Fruit 3",
  "🍇 Fruta 4": "🍇 Fruit 4",
  "🪒 Rasurarse": "🪒 Se raser",
  "La del bonus: con esta van las 4 piezas": "Celui du bonus : avec celui-ci ça fait les 4",
  "Comida:": "Déjeuner :",
  "Cena:": "Dîner :",
  "Comer": "Déjeuner",
  "Dormir": "Dormir",
  "Levantarte con calma": "Se lever tranquillement",
  "Descanso de verdad": "Vrai repos",
  "Es el día que sostiene la semana": "C'est le jour qui tient la semaine",
  "Preparar la semana": "Préparer la semaine",
  "Batch cooking (hasta las 13:00)": "Batch cooking (jusqu'à 13 h)",
  "Las comidas de la semana, del menú": "Les repas de la semaine, du menu",
  "Platos y cocina recogida": "Vaisselle faite, cuisine rangée",
  "Mochila del gimnasio hecha · menú a la vista": "Sac de sport prêt · menu en vue",
  "Todo listo. Falta que tú digas YA.": "Tout est prêt. Il ne manque que ton GO.",
  "START · empezar hoy 💪": "START · commencer aujourd'hui 💪",
  "La racha y los puntos del día": "La série et les points du jour",
  "El bote de recompensas": "La cagnotte des récompenses",
  "La fase de estudio (30 → 60 min)": "La phase d'étude (30 → 60 min)",
  "Las semanas 6/7 y los logros": "Les semaines 6/7 et les succès",
  "Día 1": "Jour 1",
  "Un momento, están llegando de Firebase. Tu racha y tus días están guardados. Si esto no avanza, revisa la conexión.":
    "Un instant, ça arrive de Firebase. Ta série et tes journées sont sauvegardées. Si ça n'avance pas, vérifie la connexion.",
  "Estudio": "Étude",
  "· 30 min (fase 1)": "· 30 min (phase 1)",
  "Estudio: fase 1 · 30 min/día. Sube sola con 2 semanas seguidas a 6 de 7.":
    "Étude : phase 1 · 30 min/jour. Elle monte toute seule après 2 semaines de suite à 6 sur 7.",

  "Guardar el entreno": "Enregistrer la séance",
  "¿De qué día es?": "De quel jour est-elle ?",
  "Si lo apuntas tarde (o pasada la medianoche), pon el día en que entrenaste":
    "Si tu la notes tard (ou après minuit), mets le jour où tu t'es entraîné",
  "Duración (min)": "Durée (min)",
  "reps": "reps",
  "Peso": "Poids",
  "Los kg de la serie 1": "Les kg de la série 1",
  "Los kg de la serie 2": "Les kg de la série 2",
  "Los kg de la serie 3": "Les kg de la série 3",
  "Últimos entrenos": "Dernières séances",
  "Pierna": "Jambes",
  "Tirón": "Tirage",
  "Empuje": "Poussée",
  "Core + caminata": "Gainage + marche",
  "Piscina": "Piscine",
  "Caminata": "Marche",
  "En casa": "À la maison",
  "Cómo se hace": "Comment faire",
  "Plan de serie ·": "Plan de base ·",
  "Press banca": "Développé couché",
  "Press de hombro": "Développé épaules",
  "Press de hombro (máquina o mancuernas)": "Développé épaules (machine ou haltères)",
  "Jalón al pecho": "Tirage vertical",
  "Jalón agarre cerrado (puños mirándose)": "Tirage prise serrée (poings face à face)",
  "Remo en máquina": "Rowing machine",
  "Remo en máquina (la barra hacia ti)": "Rowing machine (la barre vers toi)",
  "Remo a una mano con el chaleco": "Rowing à un bras avec le gilet",
  "Curl en máquina": "Curl machine",
  "Curl martillo con mancuernas": "Curl marteau aux haltères",
  "Curl femoral (tumbado o sentado)": "Leg curl (allongé ou assis)",
  "Extensiones de cuádriceps": "Leg extension",
  "Hacka (o prensa)": "Hack squat (ou presse)",
  "Hacka / prensa": "Hack squat / presse",
  "Peso muerto rumano con mancuernas": "Soulevé de terre roumain aux haltères",
  "Gemelos de pie": "Mollets debout",
  "Abductor o aductor (alterna semanas)": "Abducteurs ou adducteurs (alterne les semaines)",
  "Lumbar (espalda baja)": "Lombaires",
  "Elevaciones laterales (máquina o mancuernas)": "Élévations latérales (machine ou haltères)",
  "Cruces en polea (alta o baja, alterna)": "Croisés à la poulie (haute ou basse, alterne)",
  "Posterior en polea cruzada": "Arrière d'épaule à la poulie croisée",
  "Tríceps en polea (cuerda o barra, alterna)": "Triceps à la poulie (corde ou barre, alterne)",
  "Crunch en máquina": "Crunch machine",
  "Elevaciones de piernas (tumbado o colgado)": "Relevés de jambes (allongé ou suspendu)",
  "Plancha": "Planche",
  "Flexiones": "Pompes",
  "Flexiones diamante": "Pompes diamant",
  "Flexiones seguidas": "Pompes d'affilée",
  "Sentadillas con el chaleco": "Squats avec le gilet",
  "Zancadas alternas": "Fentes alternées",
  "Caminata en cuesta (cinta 10–12 % · 5 km/h)": "Marche en côte (tapis 10–12 % · 5 km/h)",
  "La primera vez apunta tu peso; desde entonces la app te lo trae puesto y avisa cuando toque subir":
    "La première fois, note ton poids ; ensuite l'app le pré-remplit et prévient quand il faut monter",
  "Si está imposible: ejercicios 1 y 2 se esperan, del 3 en adelante cualquier máquina del mismo grupo vale, y si no hay manera → piscina. Cuenta igual.":
    "Si c'est bondé : les exercices 1 et 2 s'attendent, à partir du 3 n'importe quelle machine du même groupe convient, et sinon → piscine. Ça compte pareil.",
  "El gimnasio estaba lleno": "La salle était bondée",
  "¿Te ha molestado la ingle hoy? 0 = nada · 10 = mucho": "L'aine t'a gêné aujourd'hui ? 0 = pas du tout · 10 = beaucoup",
  "El aductor con suavidad mientras la ingle esté delicada; si molesta, fuera y punto":
    "Les adducteurs en douceur tant que l'aine est fragile ; si ça gêne, on enlève, point",
  "Lo único nuevo: glúteo y femoral de verdad. Si la ingle avisa, menos peso y menos recorrido":
    "La seule nouveauté : du vrai travail fessiers et ischios. Si l'aine se manifeste, moins de poids et moins d'amplitude",
  "Si vas justo de tiempo, este es el que se cae": "Si tu manques de temps, c'est celui-là qu'on saute",
  "~10 min · vale mientras trabajas": "~10 min · ça marche pendant que tu travailles",
  "Crear una rutina propia": "Créer sa propre routine",
  "＋ Rutina": "＋ Routine",
  "Cambiar": "Changer",

  "El duelo de la semana": "Le duel de la semaine",
  "Puntos de esta semana, de lunes a hoy. Gana quien se cuida — no quien se machaca: los puntos salen de dormir, moverse, comer bien y cumplir lo tuyo. Un día redondo = los 4 innegociables cumplidos. Perder este duelo también es ganar.":
    "Les points de la semaine, de lundi à aujourd'hui. Celui qui prend soin de lui gagne — pas celui qui se détruit : les points viennent de dormir, bouger, bien manger et tenir ses promesses. Une journée parfaite = les 4 non négociables réussis. Perdre ce duel, c'est gagner aussi.",
  "Empate": "Égalité",
  "Puntos": "Points",
  "Días redondos": "Journées parfaites",
  "Entrenos": "Séances",
  "Semanas 6/7": "Semaines 6/7",
  "El bote": "La cagnotte",
  "bote total": "cagnotte totale",
  "disponible para gastar": "disponible à dépenser",
  "· Cada día cumplido suma lo que NO te gastas en comida fuera.": "· Chaque journée réussie ajoute ce que tu n'as PAS dépensé au resto.",
  "Nueva recompensa": "Nouvelle récompense",
  "Añade recompensas: pavos, piezas del PC, el voucher del AZ-900… Nunca comida.":
    "Ajoute des récompenses : crédits de jeu, pièces du PC, le voucher AZ-900… Jamais de nourriture.",
  "Cuesta (€)": "Coûte (€)",
  "Retos de fuerza": "Défis de force",
  "Apunta el peso una vez por semana en Hoy → Apuntes del día.": "Note ton poids une fois par semaine dans Aujourd'hui → Notes du jour.",
  "Apunta tu peso en Hoy y salen sus niveles (van en proporción a tu peso).":
    "Note ton poids dans Aujourd'hui et les niveaux apparaissent (proportionnels à ton poids).",
  "Aún sin marca: registra un entreno con este ejercicio. Primer reto:": "Pas encore de record : enregistre une séance avec cet exercice. Premier défi :",
  "Valoraciones estimadas con estándares de fuerza internacionales, entre gente que entrena — comparado con la población general estás bastante más arriba. Los retos con kilos van en proporción a tu peso corporal: si tú bajas, ellos bajan contigo.":
    "Évaluations estimées avec les standards de force internationaux, parmi les gens qui s'entraînent — comparé à la population générale tu es bien au-dessus. Les défis en kilos sont proportionnels à ton poids : si tu descends, ils descendent avec toi.",
  "🏅 0 medallas": "🏅 0 médaille",
  "Fuerza — mejor serie por sesión": "Force — meilleure série par séance",
  "Peso — hacia 84 kg": "Poids — vers 84 kg",
  "objetivo 84": "objectif 84",
  "mejor: 0": "record : 0",
  "Logros · 0/18": "Succès · 0/18",
  "Primer día cumplido": "Première journée réussie",
  "Primera semana 6 de 7": "Première semaine à 6 sur 7",
  "Primer mes cumplido": "Premier mois réussi",
  "Racha de 7 días": "Série de 7 jours",
  "Racha de 14 días": "Série de 14 jours",
  "Racha de 30 días": "Série de 30 jours",
  "10 entrenos": "10 séances",
  "25 entrenos": "25 séances",
  "50 entrenos": "50 séances",
  "Primera piscina": "Première piscine",
  "Primera subida de peso": "Première montée de charge",
  "Subida en 5 ejercicios": "Montée sur 5 exercices",
  "Primera recompensa canjeada": "Première récompense utilisée",
  "Fase 2 de estudio": "Phase 2 d'étude",
  "Fase 4: una hora al día": "Phase 4 : une heure par jour",
  "Teórico de moto aprobado": "Code moto réussi",
  "AZ-900 aprobado": "AZ-900 réussi",
  "Carnet A2": "Permis A2",
  "Tasa DGT pagada": "Taxe du permis payée",
  "Psicotécnico": "Examen psychotechnique",
  "Práctico de circuito": "Plateau réussi",
  "Práctico de circulación": "Circulation réussie",
  "Consulta de fisio por la ingle": "Consultation kiné pour l'aine",
  "Todavía no hay ninguno. El primero es hoy.": "Aucun pour l'instant. Le premier, c'est aujourd'hui.",
  "Ver mi progreso y el bote →": "Voir mon progrès et la cagnotte →",

  "El menú de la semana": "Le menu de la semaine",
  "¿Qué coméis en casa esta semana?": "Que mangez-vous à la maison cette semaine ?",
  "Hacer el menú de esta semana": "Faire le menu de la semaine",
  "El menú es": "Le menu est",
  "de casa": "du foyer",
  ": el mismo para los dos, se mire desde la app que se mire — nadie cocina dos veces. Marcad juntos lo que os apetezca: con lo marcado salen ahora":
    ": le même pour les deux, quelle que soit l'app d'où on regarde — personne ne cuisine deux fois. Cochez ensemble ce qui vous fait envie : avec ce qui est coché sortent maintenant",
  "8 desayunos, 14 comidas y 15 cenas": "8 petits-déjeuners, 14 déjeuners et 15 dîners",
  "Todavía no hay menú para esta semana. Marcad los ingredientes y dadle al botón: saldrá priorizando lo rápido (AirFryer, horno o pocos pasos), y luego cada día se puede retocar con el lápiz.":
    "Pas encore de menu cette semaine. Cochez les ingrédients et appuyez sur le bouton : il sortira en priorisant le rapide (AirFryer, four ou peu d'étapes), puis chaque jour se retouche avec le crayon.",
  "Haz tu menú de la semana con TUS ingredientes →": "Fais ton menu de la semaine avec TES ingrédients →",
  "Platos vuestros": "Vos plats à vous",
  "＋ Plato vuestro": "＋ Plat à vous",
  "Comida fuera esta semana:": "Restos cette semaine :",
  "Proteína": "Protéines",
  "Hidratos": "Féculents",
  "Verdura": "Légumes",
  "Legumbres": "Légumineuses",
  "Lácteos y básicos": "Laitages et basiques",
  "De postre": "En dessert",
  "Pollo": "Poulet",
  "Ternera picada": "Bœuf haché",
  "Lomo de cerdo": "Filet de porc",
  "Salchichas": "Saucisses",
  "Bacon": "Bacon",
  "Chorizo": "Chorizo",
  "Jamón / fiambre de pavo": "Jambon / blanc de dinde",
  "Atún en lata": "Thon en boîte",
  "Merluza": "Colin",
  "Salmón": "Saumon",
  "Huevos": "Œufs",
  "Arroz": "Riz",
  "Pasta": "Pâtes",
  "Patatas": "Pommes de terre",
  "Pan": "Pain",
  "Avena": "Flocons d'avoine",
  "Cuscús": "Couscous",
  "Harina (crepes y pancakes)": "Farine (crêpes et pancakes)",
  "Base de pizza": "Pâte à pizza",
  "Tortillas de trigo (wraps)": "Tortillas de blé (wraps)",
  "Tomate frito / triturado": "Sauce tomate / concassée",
  "Lechuga (ensalada)": "Laitue (salade)",
  "Zanahoria (triturada)": "Carotte (râpée)",
  "Cebolla (en la salsa)": "Oignon (dans la sauce)",
  "Brócoli (con queso)": "Brocoli (au fromage)",
  "Calabacín (en crema)": "Courgette (en velouté)",
  "Espinacas (trituradas)": "Épinards (mixés)",
  "Lentejas": "Lentilles",
  "Garbanzos": "Pois chiches",
  "Alubias": "Haricots",
  "Leche": "Lait",
  "Queso": "Fromage",
  "Yogur griego": "Yaourt grec",
  "Mantequilla": "Beurre",
  "ColaCao / Cacaolat": "Chocolat en poudre",
  "Caldo de pollo": "Bouillon de volaille",
  "Fruta (todas)": "Fruits (tous)",
  "Frutos secos": "Fruits secs",
  "Pasta boloñesa (verdura en la salsa)": "Pâtes bolognaise (légumes dans la sauce)",
  "Sándwich integral de pollo": "Sandwich complet au poulet",
  "¿Qué falta en casa?": "Qu'est-ce qui manque à la maison ?",
  "+ Añadir a la lista": "+ Ajouter à la liste",
  "Elige categoría, escribe y dale a intro · toca para marcar o reponer · mantén pulsado para borrar":
    "Choisis la catégorie, écris et valide · touche pour cocher ou racheter · reste appuyé pour effacer",
  "No falta nada ✨": "Rien ne manque ✨",
  "Quitar de la lista": "Retirer de la liste",
  "Crear una categoría": "Créer une catégorie",
  "Limpieza": "Ménage",
  "Cosas para la casa": "Pour la maison",
  "Muebles": "Meubles",
  "Electrodomésticos": "Électroménager",

  "La mochila de la oficina": "Le sac du bureau",
  "Repásala la noche de antes (el lunes te lo recuerda el horario) y un vistazo por la mañana. Las marcas se borran solas al día siguiente, listas para la próxima.":
    "Vérifie-le la veille au soir (le lundi, l'horaire te le rappelle) et un coup d'œil le matin. Les coches s'effacent toutes seules le lendemain, prêtes pour la prochaine fois.",
  "Portátil y cargador": "Ordi et chargeur",
  "Auriculares": "Écouteurs",
  "Botella de agua": "Bouteille d'eau",
  "Tupper o comida": "Lunchbox ou repas",
  "Tarjeta o llaves de la oficina": "Badge ou clés du bureau",
  "Cartera y transporte": "Portefeuille et titre de transport",
  "Ropa de mañana lista": "Vêtements de demain prêts",
  "Para el camino": "Pour la route",
  "¿Algo más que llevar?": "Autre chose à emporter ?",
  "+ Apuntar regla": "+ Noter les règles",
  "Calendario personal": "Calendrier personnel",
  "＋ Añadir": "＋ Ajouter",
};

export const PATRONES_FR = [
  [/^Gastos de esta categoría · (.+)$/, "Dépenses de cette catégorie · $1"],
  [/^Hola, (.+)$/, "Salut, $1"],
  [/^Límite mensual (.+)$/, "Limite mensuelle $1"],
  [/^Saldo inicial (.+) · desde (.+)$/, "Solde initial $1 · depuis $2"],
  [/^Prestado (.+) · para el (.+)$/, "Prêté $1 · pour le $2"],
  [/^Prestado (.+?) \+ interés (.+?) = debe (.+?) · ya ha pagado (.+)$/, "Prêté $1 + intérêts $2 = doit $3 · déjà payé $4"],
  [/^Prestado (.+?) \+ interés (.+?) = debe (.+)$/, "Prêté $1 + intérêts $2 = doit $3"],
  [/^Prestado (.+?) · ya ha pagado (.+)$/, "Prêté $1 · déjà payé $2"],
  [/^Prestado (.+)$/, "Prêté $1"],
  [/^pendiente de (.+)$/, "sur $1 à recevoir"],
  [/^Pagado este mes: (.+?) \((.+?)\) · Pendiente: (.+)$/, "Payé ce mois-ci : $1 ($2) · Restant : $3"],
  [/^Historial: (\d+) pagos? · (.+) cobrados$/, "Historique : $1 paiements · $2 encaissés"],
  [/^Historial · (.+)$/, "Historique · $1"],
  [/^Cobrado en (.+)$/, "Encaissé en $1"],
  [/^Total (.+?) — capital (.+?) \+ intereses$/, "Total $1 — capital $2 + intérêts"],
  [/^Capital (.+?) · interés (.+)$/, "Capital $1 · intérêts $2"],
  [/^Capital (.+)$/, "Capital $1"],
  [/^Cuadrar · (.+)$/, "Ajuster · $1"],
  [/^Abono · (.+)$/, "Paiement · $1"],
  [/^Liquidar deuda · (.+)$/, "Solder la dette · $1"],
  [/^Interés pagado · (.+)$/, "Intérêts payés · $1"],
  [/^Transferencia enviada a (.+)$/, "Virement envoyé vers $1"],
  [/^Transferencia recibida de (.+)$/, "Virement reçu de $1"],
  [/^Transferencia · (.+)$/, "Virement · $1"],
  [/^Con (.+?) queda$/, "Avec $1 c'est"],
  [/^todo saldado$/, "tout soldé"],
  [/^: el préstamo se cerrará como Pagado\.$/, " : le prêt sera clôturé comme Payé."],
  [/^Quedarán por pagar$/, "Il restera à payer"],
  [/^Se ajustará$/, "Ce sera ajusté de"],
  [/^para que el saldo diga (.+)\.$/, "pour que le solde affiche $1."],
  [/^\(de (.+) en total\)\. Escribe cuánto ha pagado\.$/, "(sur $1 au total). Écris combien il a payé."],
  [/^\(de (.+?) en total, ya había pagado (.+?)\)\.$/, "(sur $1 au total, $2 déjà payés)."],
  [/^Te hemos enviado un email a (.+) para cambiar la contraseña\.$/, "Nous avons envoyé un e-mail à $1 pour changer le mot de passe."],
  [/^(\d+) de (\d+) pantallas?$/, "$1 sur $2 écrans"],
  [/^(\d+) de (\d+)$/, "$1 sur $2"],
  [/^Debe (.+)$/, "Doit $1"],
  [/^ya ha pagado (.+)$/, "déjà payé $1"],
  [/^· ya ha pagado (.+)$/, "· déjà payé $1"],
  [/^· para el (.+)$/, "· pour le $1"],
  [/^AHORA · (.+)$/, "MAINTENANT · $1"],
  [/^Ahora: (.+)$/, "Maintenant : $1"],
  [/^Pierna — tus máquinas de siempre$/, "Jambes — tes machines habituelles"],
  [/^Tirón — espalda y bíceps$/, "Tirage — dos et biceps"],
  [/^Empuje — pecho, hombro y tríceps$/, "Poussée — pecs, épaules et triceps"],
  [/^Caminata \+ core — el día ligero$/, "Marche + gainage — le jour léger"],
  [/^Piscina con tu hermano$/, "Piscine avec ton frère"],
  [/^Libre o caminata suave$/, "Libre ou marche tranquille"],
  [/^Descanso · batch cooking$/, "Repos · batch cooking"],
  [/^· empezaste el (.+)$/, "· tu as commencé le $1"],
  [/^· media de las (\d+) anteriores: (.+)$/, "· moyenne des $1 dernières : $2"],
  [/^Referencia: (.+)\/día$/, "Référence : $1/jour"],
  [/^(\d+) días? · Día (\d+)$/, "$1 jours · Jour $2"],
  [/^Día (\d+)$/, "Jour $1"],
  [/^mejor: (\d+)$/, "record : $1"],
  [/^objetivo (\d+)$/, "objectif $1"],
  [/^🏅 (\d+) medallas?$/, "🏅 $1 médailles"],
  [/^Logros · (\d+)\/(\d+)$/, "Succès · $1/$2"],
  [/^Racha de (\d+) días$/, "Série de $1 jours"],
  [/^(\d+) entrenos$/, "$1 séances"],
  [/^Los kg de la serie (\d+)$/, "Les kg de la série $1"],
  [/^Faltó: (.+)$/, "Il manquait : $1"],
  [/^Día cerrado \(no cumplido\) · (\d+) puntos$/, "Journée clôturée (non réussie) · $1 points"],
  [/^✓ Día cumplido · (\d+) puntos$/, "✓ Journée réussie · $1 points"],
  [/^(\d+) puntos$/, "$1 points"],
  [/^Aún sin marcar: (.+)\. Un toque ahora y el día no se escapa\.$/, "Pas encore coché : $1. Un geste maintenant et la journée ne s'échappe pas."],
  [/^Cerrando AYER · (.+)$/, "Clôture d'HIER · $1"],
  [/^Corrigiendo · (.+)$/, "Correction · $1"],
];
